### ISSUE TITLE
Impossible to copy mailto: URLs

### ISSUE THREAD

**Issue by l29ah** [MoonchildProductions/UXP#1009]
http://vger.kernel.org/vger-lists.html
Right-clicking on any `subscribe` URL results only allow copying the e-mail address instead of the full URL that includes a subject.

**Comment by JustOff** [comment]
I believe this is absolutely correct behavior for the "Copy Email Address" action.

**Comment by wolfbeast** [comment]
A `mailto:` hyperlink is not actually a URL, since it doesn't point to a resource located on a network. It's a URI with a different scheme that does not have the same form as a URL and therefore doesn't represent such a link. The browser doesn't offer to copy the URI as a whole because there is no reasonable use for it as a link. It does offer to extract the useful part out of it, which is the e-mail address.

If you want it to be read and parsed as a whole, left-click it and let it be handed off to whatever external application handles `mailto:` schemes.
