### ISSUE TITLE
 Allow incremental GC when keepAtoms is set

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#1056]
https://bugzilla.mozilla.org/show_bug.cgi?id=1213977

This improvement would allow incremental GC when keepAtoms is set.

jsgc.cpp and jsgc.h parts of patch can be directly applied to UXP.

**Comment by wolfbeast** [comment]
I don't think this is safe to do.

**Comment by wolfbeast** [comment]
@win7-7 Please provide an explanation why you think this would help to begin with and why effectively a safety check being removed would be OK to do, or, if you don't know, please close this issue, thanks.

**Comment by mattatobin** [comment]
If moebius moved forward like originally planned, we would have this patch and likely not even know it unless it caused an issue.

So we should consider that tidbit. However, I can't speak to the desirability of taking this in.

**Comment by win7-7** [comment]
According Mozilla telemetry https://bugzilla.mozilla.org/show_bug.cgi?id=1314828 this is one of reason for GC pauses.

**Comment by mattatobin** [comment]
But is it according to the real world. I don't trust performance sabotaging telemetry.

**Comment by wolfbeast** [comment]
@mattatobin The patch also doesn't apply as-is to our code base (I looked at it) so if we'd want this then we'd most likely have to look at needing more of that post-esr refactoring storm.
Just removing the check might be detrimental (it was put there for a reason, after all, unless that reasoning was incorrect).

@win7-7 Not sweeping the atoms zone in an incremental GC means it will trigger a non-incremental GC eventually to sweep that zone, which will cause a pause visible in ubench (because it exercises the GC more than any page would). 

---

You can't just sweep everything incrementally; what if new atoms are allocated while the GC is in progress? I'd say you'd create the risk of a crash unless they are otherwise protected -- that's why I don't think this is safe to do, but I may be wrong if that is protected another way.

You can _try_ removing the atoms check in `gc::IsIncrementalGCUnsafe` and see what it does when torturing the garbage collector, but if it is in any way influencing stability then it's definitely a no-go.

**Comment by win7-7** [comment]
I think in case of removing atoms check causing risk of crash this issue can be closed. While I don't see clear stability problems yet while testing this if stability is at risk in any way then this isn't good to do.
