### ISSUE TITLE
Fix XRENDER bottleneck

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1061]
This should have been created when the issue was first brought up that, although xrender works (#341 ) , it suffers from a serious bottleneck.

Most of the discussion about this was communicated in private e-mail with @stefanbaur which ended up basically with "we'll have someone investigate the cause and come up with a PR" which took a few months.

It was found that the performance issue was created by fully redrawing scrolled surfaces after a delta is sent through via remote X. It wasn't until the PR was offered to our repo that we were informed about the actual issue underlying this. See also the information on the PR (#1060 )

**Comment by wolfbeast** [comment]
Copying the explanation from the PR ( @Ionic ):

Mozilla tried to enable XRENDER support with backends other than Cairo
in 286348:e13aaaaf1962 /
https://hg.mozilla.org/mozilla-central/rev/e13aaaaf1962 - at least until
they decided to completely remove XRENDER support.

The change looked innocent enough, but actually turned out to do exactly
the opposite: it forcefully enabled image offscreen surfaces with GTK2
when it was previously disabled (since
gfxPrefs::UseImageOffscreenSurfaces() will always return true) and, by
extension, disabled the XRENDER-based functionality by creating a
non-Xlib surface.

Interestingly, a previously enabled double buffering check was also
disabled by this, but since the comment for this was diverging with the
code, that behavior just sounds like yet another bug.

Instead of disabling image offscreen surfaces (at least when using the
GTK2 backend), let's force the creation of Xlib-based image surfaces
when XRENDER support is enabled. This will let UXP use the more
common/modern code paths, but also make scrolling much faster again. Too
fast scrolling may induce tearing (if not smoothed), but on the other
hand performs much better in remote computing contexts.

As an added benefit, GTK3-based builds should roughly behave the same
way. Further tests with the GTK3-backend enabled will be required in the
future.

**Comment by wolfbeast** [comment]
@Ionic Looking at the linked BZ bug and commit for it, it'd probably be a good idea to reintroduce some of those cairo checks for xrender usage too, considering people can use Skia by choice as a rendering back-end and that will likely break if trying to use Xlib surfaces (I think?).

**Comment by Ionic** [comment]
Yeah, sorry, bisecting wasn't exactly easy. I've started a first bisecting run for FF45..52 months ago, ran it through 15 bisection steps or so, fixing issues along the way by backporting commits (mostly GCC 6 incompatibilities or stuff they broke in-between and only fixed later in the history, but stuff like that happens in every repository, so no hard feelings on that), while manually testing the scrolling behavior in a remote session. I came up with a pretty much useless result in the first run, since I essentially bisected back to a commit that disabled XRENDER by default.

I then started a second bisecting run - this time making sure that the `gfx.xrender.enabled` pref is always set to enabled and not just the default value which might flip around as Mozilla sees fit - and came up with the mentioned commit a few days ago.

> @Ionic Looking at the linked BZ bug and commit for it, it'd probably be a good idea to reintroduce some of those cairo checks for xrender usage too

Being able to use the XRENDER extension with both Cairo and Skia actually sounds like a worthwhile addition to me. I don't know how well it would work with Skia (since at least PM by default doesn't use it, right? When was the possibility to use Skia introduced? Only for Basilisk or also for PM?), but in general, any usage of plain pixmaps/bitmaps will slow down performance a lot - at least remotely. Locally it shouldn't make a whole lot of difference regarding how much you hammer the X server with updates (especially in an OpenGL context, where blending of images should be very, very fast), since the general overhead and latency is pretty low, essentially determined by the latency and the throughput available of the system memory. Remotely, though, latencies are orders of magnitude higher of course and replacing whole images with a lot of pixels by a small amount of rather simple XRENDER operations will behave a lot better. I'm not saying that the remote desktop technologies are great and a lot of speedup could probably be also gained by removing round-trips for X calls (think of buffering data on the remote side if it comes in too fast from the application and only sending an accumulated operation over the link, which then only needs to be processed once), buuuuuut we're probably not there yet and it's not a trivial task to implement, so I wouldn't hold my breath on that.

> considering people can use Skia by choice as a rendering back-end and that will likely break if trying to use Xlib surfaces (I think?).

I'd be surprised if Skia couldn't use surfaces that are compatible with Xlib, but that's just an educated guess. There must have been a reason (good or bad) why Mozilla removed XRENDER support, I haven't actually followed that procedure, though, and information seems to be spread over a lot of different bug reports, commits etc.

>  I'm assuming you've tested the result in your own builds before offering up the PR. Please let me know if you've tested both Pale Moon and Basilisk or not, and if not, could you make and test builds of both browsers, getting feedback on both GTK2 and GTK3 use, here?

I've tested GTK2-based PM 28.4.1 builds with two patches backported so far, after doing most development/testing with mozilla-central. Knowing that Basilisk is using GTK3 is great - until now I only knew that PM is using GTK2 by default and I didn't bother to build it against GTK3 since I didn't know if it would even compile correctly against that backend. I can of course also try to test GTK2- and GTK3-builds side by side in a remote session and see how they behave, maybe even Basilisk, although I currently only have an automated Debian-based build solution for PM so far. Doing a few manual Basilisk builds shouldn't be too difficult, though, since that's what I've done all the time with M-C.

So far, no local tests have been conducted with the patched PM version, but to be honest I cannot believe that this change would cause any regressions. It's a fair point that it might, though, since we have to keep the OpenGL-accelerated surfaces in mind, which might degrade to non-accelerated if the surface is somehow not OpenGL-compatible.

Given that XRENDER is still enabled by default in PM, though, and versions 27 and lower essentially already used the Xlib-based surfaces all the time and people haven't complained, I don't see a lot of potential breakage.

**Comment by trav90** [comment]
> So far, no local tests have been conducted with the patched PM version

@Ionic even though the patch may be fairly low risk I'd still like to see the results of some tests. As Tobin mentioned in #1060 we need to know the impact on both GTK2 and GTK3 both with and without xrender enabled.

**Comment by mattatobin** [comment]
U'd be surprised what could be an issue.. Tycho and older versions of Firefox are no indication here.

**Comment by stefanbaur** [comment]
Hi folks, just popping in here real quick - is there a particular set of tests that we should run?
Currently, we used a Dutch and a German IT news web site, and Twitter, to check if the scrolling speeds differ.
We should be able to start testing around May 8th, sorry for that delay, but I'm out of the country for most of next week (we have a booth at LinuxWeeks Austria in Vienna) and will have to catch up with work first, once I return. But after that, we can set up two identical machines so we can do side-by-side testing for local as well as remote sessions.
-Stefan

**Comment by mattatobin** [comment]
Just.. Before and After Patch on GTK2 and 3 (you can just use Pale Moon compiled for both) with Cairo and Skia in general desktop browsing situations. Facebook, Google, Youtube, etc. Look for if post-patch it doesn't seem to run as well or crashes and such.

So build GTK2 and 3 versions of Pale Moon with and without the patch and compare them in general with Cairo and Skia as the used backend verify with `about:troubleshooting` with xrender enabled and disabled.

This is just basic general usage function, performance, and stability testing. You don't need identical machines in fact use different machines and test those things with those factors on machines with different hardware.

**Comment by stefanbaur** [comment]
Well, for the local performance tests, it's nice to have 2 identical machines side by side, so you can tell the speed difference just by looking at the screens. But yes, for stability testing, we should be using different hardware. Will take that into account, thanks for the reminder.

**Comment by mattatobin** [comment]
Computers can have more than one monitor ;)

**Comment by stefanbaur** [comment]
Running two instances on the same machine carries some risks, like accidentally loading the same instance twice and wondering why you see no difference. Happened to @Ionic during our previous tests, luckily I caught it. ;-)
And I think there's more that could go wrong, at least in theory. So since we have two identical machines at our disposal, we'll just play it safe for the performance tests.

**Comment by wolfbeast** [comment]
> I don't know how well it would work with Skia (since at least PM by default doesn't use it, right? When was the possibility to use Skia introduced? Only for Basilisk or also for PM?

We've had Skia for Content as an option for a long while but it wasn't actually stable enough for such use until UXP. All of this is Goanna platform code so applies to any application, including Basilisk.
That said I've dropped Skia from the default back-end selections, preferring our in-tree cairo on all applicable platforms (Windows and Linux). Skia remains used for canvas because of its speed.

> I'd be surprised if Skia couldn't use surfaces that are compatible with Xlib, but that's just an educated guess. 

Which is exactly why this needs to be tested :)
Enabling skia for content should be as simple as changing `gfx.content.azure.backends` and adding `skia` to it, e.g. `skia,cairo` (browser restart required). You can verify with help -> troubleshooting information to see which back-end is used.

**Comment by wolfbeast** [comment]
Per e-mail discussion, marking this as assigned to Ionic and eligible for a bounty.

**Comment by Ionic** [comment]
Btw, just for reference (took me a few minutes to figure that out): it looks like `about:troubleshooting` was renamed to `about:support`.

**Comment by wolfbeast** [comment]
It has always been about:support. But in the menu (which is the normal way anyone would access it), it's called "Troubleshooting information"

**Comment by mattatobin** [comment]
Yeah sorry for the confusion there.

**Comment by wolfbeast** [comment]
How are we on testing the results of this on *nix? I'd prefer to move this forward and it should be in 28.6.0 as a stable and fully tested change.

**Comment by Ionic** [comment]
I've built 28.5.0 and a patched 28.5.0 GTK-2-based version yesterday, @stefanbaur has setup some testing environment (or is still doing so) and we will probably begin testing shortly. And now I just realized that I have to make another two builds that are based on GTK 3, so I screwed up on that one.

Because this change also affects Windows (the GTK interface is used on both Linux and Windows), can I ask for the favor of you supplying unofficial patched GTK 2 and GTK 3 versions, including an unofficial unpatched 28.5.0 GTK 3 version for Windows? I don't have any build infrastructure for Windows and no experience with either the required toolchain or the build process on Windows.

**Comment by kn-yami** [comment]
>the GTK interface is used on both Linux and Windows

Are you sure about this? AFAIK the Windows version uses only Win32 APIs and XUL/XBL to handle the interface.

**Comment by Ionic** [comment]
I've seen comments referring to Windows like "WINNT", but maybe I was wrong.

The patch only really changes content ifdef'd `MOZ_X11`, though, so forget about the Windows stuff. No need to test that. Brainfart on my end.

**Comment by wolfbeast** [comment]
There's no GTK on Windows. Native widgets are used. Also as you already noticed yourself it's in an X11 specific block so it'd be preprocessed out on Windows builds.

**Comment by stefanbaur** [comment]
@wolfbeast:
> Enabling skia for content should be as simple as changing `gfx.content.azure.backends` and adding `skia` to it, e.g. `skia,cairo` (browser restart required). You can verify with help -> troubleshooting information to see which back-end is used.
[...]
> Ah but the crux is that v27 and lower never used Skia for content by default either. Even so, the check in place at the time (before the "bad commit" by Mozilla) had explicit checks for cairo being in use. I just want to make sure that those cairo checks aren't necessary (if skia works with xlib surfaces then that's great, but if not...) to prevent a pretty massive footgun.

So I've run some tests on Linux *locally*, with gfx.content.azure.backends in the default setting (cairo), and with gfx.content.azure.backends manually set to "skia" (that's skia only, not skia, cairo).
The only difference I saw was when I was using the cursor keys to scroll up and down. "Jumps" using Home/End and PageUp/PageDown were unaffected.

With Cairo, the cursor key scolling took a little longer on the Pale Moon start page, especially when in zoom mode (7 times Ctrl and + key) *after* the patch.
Also, a local news web site showed some rectangular areas of larger images being updated with a slight delay when scrolling with the cursor keys - but only when the screen orientation was 90° to the left (maybe hardware acceleration doesn't work/doesn't work as well with rotated screens?) AND the window was zoomed in (again, 7 times).
YouTube video playback was OK in both modes. Scrolling with the cursor keys was again a tad bit slower with the patch applied.
A google results page when googling for "pale moon" was unaffected - it scrolled equally fast both with and without the patch, at 100% zoom as well as zoomed in.
Now here's the funny part, after all the above tests coming back either unaffected or just slightly slower with the patch applied, Facebook actually scrolls a tad bit faster with the patch applied. (I didn't try zooming in there, though - their page layout with all the annoying popups is already a mess at 100% zoom).

With gfx.content.azure.backends forced to skia only, there was no difference between before and after for the local tests, so I'm guessing the code path in question is not getting executed at all.

Should I test with gfx.content.azure.backends set to "skia,cairo" as well? Or should I move on to testing things over a remote connection?

-Stefan

**Comment by wolfbeast** [comment]
Large zoom level responsiveness isn't a big issue, and is actually expected because Skia simply handles very large texture surfaces more efficiently.

> Should I test with gfx.content.azure.backends set to "skia,cairo" as well? Or should I move on to testing things over a remote connection?

There's no point in testing that if you've already individually tested both! I'd say have a test over remote, and if nothing disastrous happens we can merge and call this solved.

**Comment by stefanbaur** [comment]
Ah, nice. Well, I've been testing GTK2 so far; GTK3 still needs to be tested, too.
Oh, and do we also need to test with gfx.xrender.enabled manually set to false?

**Comment by wolfbeast** [comment]
You can give it a casual test with xrender to false, but since that will bypass this code path, I think, it won't really have much influence at all.
Also, remotely I think Skia will perform poorly, but we'll have to see if it actually caters to this kind of use or not. The main issue is that I don't want this to cause crashes or similar critical behavior. If it does then this change needs to be preffed so people can set it up as-needed.

**Comment by stefanbaur** [comment]
GTK3 Cairo results, local use: Same as GTK2, only that Facebook is now also a tad bit slower, like the other sites we tested, and the local news site doesn't have the update delay for larger image sections any more.
GTK3 Skia results, local use: Same as GTK2.

Regarding xrender:
We originally asked you to keep xrender enabled because we believed that alone was enough to keep the remote performance unchanged.
if it turns out that with our patch, things are a tad bit slower in general when used locally, then maybe we could tie in our change with the xrender pref - you switch your xrender default from true to false, and remote users could turn it back on - also enabling our patch in the process.
Just an idea, though, and would need some further testing how xrender = false affects local rendering speed. Especially as this would mean a much larger test matrix - I'd have to repeat the GTK2 and GTK3 tests with both cairo and skia with xrender = false, for both local and remote usage.

**Comment by mattatobin** [comment]
So is local rendering slower with your patch?

**Comment by stefanbaur** [comment]
Yes, but as explained above, it's only noticeable when you use the arrow keys to scroll. There's a short lag, basically, the unpatched version hits the top or bottom of the page when the patched one is still one "scrolling distance" away.

PageUp/PageDown scroll speeds are unaffected.

**Comment by mattatobin** [comment]
What about mouse wheel scrolling.

Why is xrender enabled by default?

**Comment by stefanbaur** [comment]
The problem with mouse wheel scrolling is that I can't do side-by-side testing as I don't have two mice of the same make / model, so I can't be sure they're sending the same amount of scroll impulses per spin, and even if I had, it's hard to hit the same amount of clicks when spinning. I *think* mouse wheel scrolling triggers PageUp/PageDown commands, though ...

And I believe xrender is enabled by default because we asked you to keep that setting. (It was a Firefox default once, but they changed it, some time after you forked.)

**Comment by mattatobin** [comment]
Scrolling with the mouse is the primary method of scrolling. Keyboard is seconday to that.

Do your best.

**Comment by stefanbaur** [comment]
Okay, so on Linux / X Window System, scroll wheel movements correspond to a press of mouse buttons 4 resp. 5 (4 is up, 5 is down).
There's a tool called "xdotool" that can be used to fake mouse and keyboard input. I guess I could script that to send a predefined number of "scroll wheel clicks", thus guaranteeing I always send the same amount of clicks in the same time frame ... will see what I can do.

**Comment by mattatobin** [comment]
JUST do it manually with a before and after patch.. It doesn't have to be absolutely scientific. End users aren't gonna be scientific with their mouse.

**Comment by stefanbaur** [comment]
Manually doing a fast scroll through a facebook page feels pretty much the same on GTK3/Cairo, with or without patch. I'm still curious if I can get that xdotool thingie to work for this purpose so we have repeatable behavior.

**Comment by mattatobin** [comment]
What about the other sites you were using as test cases?

**Comment by stefanbaur** [comment]
Okay, so now I'm doing automated tests:
Move the mouse arrow too coordinates 200/400 (relative to PM window)
Jump to the top of the page using the "Home" key
Wait 5 seconds to make sure the page has finished loading
Issue 150 "scroll wheel down" commands with a delay of 100 milliseconds (simulating a fast scroll)
sleep 5 seconds (to have a visual cue as to when the scrolling down commands stopped)
Issue 152 "scroll wheel up" commands, again with a delay of 100 milliseconds
(the 2 more are so that we still hit the top even if some content expanded something - might need more)
I run this on two machines next to each other, so I can tell if one finishes earlier.

Current test run: GTK3, Cairo, local environment.
https://palemoon.start.me/de, zoomed in 7 times: slight flickering in the top overlay bar ("Pale Moon/Sign In/Customize") and the cookie notification overlay bar during scrolling (after patch), but same speed. (if I don't zoom in, the page isn't long enough to offer a scroll bar)
For the local news site: Same speed.
For YouTube: Needed to change cursor position to 1200/400 so the scroll commands are issued over the video suggestion list. Same speed.
For the Google results page: also needed 1200/400 cursor position. Same speed - maybe a fraction of a second faster after the patch, but it's really hard to catch the difference, that's how close the results are to each other.
Facebook looked pretty much the same as well. Can't test any more - they're blocking my IP now for accessing their page too often. xD

**Comment by wolfbeast** [comment]
Honestly, it's already clear that performance wise it makes no significant difference. Not sure what else you had planned in that corner but just skip it. I'm more interested in stability when using skia. as stated in my last reply here it depends on that if we need to pref this or not.

**Comment by mattatobin** [comment]
When I read it, performance was no change to slower. Slower isn't acceptable, is it?

**Comment by wolfbeast** [comment]
Slower is acceptable if it's within reasonable bounds and it clearly is. we're talking a corner case at 7x zoomed in (which stresses the X server more than anything else, most likely) and even then it's _barely_ a thing. In normal use that means it won't be noticeable.

With all this sidetracking with testing methodology that's all unnecessary (we don't care about 0.5% loss or gain like Mozilla) we're losing focus.

What is important? Performance should be similar, and it is.
Stability should not be impacted, which is what I want to know in combination with the choice of Skia. We already know the default cairo is good since it's been in use like that FOR YEARS.

**Comment by stefanbaur** [comment]
Quick Update: Still testing locally using the automated script, on GTK3. No difference when skia is selected, or when xrender=false is selected, so I think it is safe to say that this code path is not used at all in these modes.

Moving on to the remote tests.

**Comment by stefanbaur** [comment]
So here are the results from the remote tests, both automated and manually. I had 2 identical servers and 2 identical clients, all on an old 10MBit/s hub, so less than 5MBit/s per connection (due to inevitable collisions on un-switched Ethernet). Each client was connected to one server.
In this situation, Skia is noticeably slower than Cairo.
With Cairo enabled, the comparison between patched and unpatched, clearly shows that the patch works.
While the automated tests show that the time to scroll from the top of a page to the bottom and back up is roughly the same between patched and unpatched, the animations are way smoother with the patch.
Without the patch, it feels like watching a video where frames are being dropped.
Also, when scrolling manually, with the unpatched version, it feels like there's a chain between the scroll wheel and the screen, and that chain has too much slack - and a massive sprocket/flywheel (think "inertia", once spinning). With the patched version, there might be a short lag when you first move the scroll wheel, but after that, wheel and screen movement feel pretty much in sync. You stop moving the wheel, the screen stops scrolling almost instantly. The unpatched version "overshoots the target", so to speak.
I think I should also test the patched version on both servers, but with one having xrender=true and the other xrender=false, to see if that makes any noticeable difference.

**Comment by wolfbeast** [comment]
Good, looks like there are no negatives to taking this as-is then. I'll be merging this patch; not sure when @trav90 can make another Linux unstable build, but it should be good to toss out to a wider audience.

**Comment by stefanbaur** [comment]
I just decided to run @Ionic's build on my personal laptop. What I'm noticing there is that I'm seeing the default "X" icon instead of the Palemoon moon icon in the taskbar. This is the patched GTK3 build. Could this be because he's not using your officially-authorized build infrastructure, or am I seeing a bug here?

**Comment by trav90** [comment]
I plan to build a new Linux unstable build within the next day or two.

**Comment by Ionic** [comment]
Okay, we've got a problem now.

@stefanbaur tested some more and experienced some graphics artifacts with this patch (with both GTK2 and GTK3) - but not when XRENDER is disabled or without these changes, so this has to be a regression. According to him, it's quite pronounced in Google Street View (at least in some places) when moving the mouse cursor quickly and leads to screen refreshes with weird stripes.

I wasn't able to reproduce that problem neither on my own system via a stretch-chroot and nVidia's binary driver, nor remotely. In his case, though, a common factor in all his machines seems to be Intel graphics hardware (some hybrid stuff, but that goes through the Intel framebuffer anyway), so maybe it's only visible with Intel HW.

Hence we've got two options:
  - revert the change
  - disable XRENDER by default - users who want to use PM in remote settings can just enable it again in about:config

The latter probably makes most sense, since XRENDER doesn't give any meaningful benefits to users running PM locally, but is also cumbersome since I'd like to fix the issue anyway if possible and make XRENDER the default again. Flipflopping this setting sounds... meh.

I don't know what exactly is causing that, but I have a hunch. Before Mozilla's "bad" patch, double buffering was always activated (on Linux) even if XRENDER was in use. After that patch, it was always deactivated because image offscreen surfaces were always activated. I already mentioned that the double buffering checking code smells funny (**comments** said that DB is supposed to be disabled when XRENDER is enabled, but the code did something different). Since DB is now always disabled due to offscreen image surfaces always being enabled and I haven't changed that code in any way, maybe we need to re-enable it when using XRENDER.

**Comment by wolfbeast** [comment]
I suggest you look into fixing the issue at hand. Disabling xrender by default can always be done if it's still an issue when we're close to a release. Your deadline will be a month from now but please try to get to this asap if you already have an idea where this problem lies. I do think double-buffering is something that should always be done when possible since it will promote visual/perceptual stability and smoothness.

**Comment by mattatobin** [comment]
How is it a problem if the user in an edge condition has to flip a preference?

**Comment by stefanbaur** [comment]
It wouldn't be a problem for our "edge condition" users.
The thing is that right now, Pale Moon defaults to xrender=true. To avoid the issue for the average Linux user of Pale Moon, you'd have to change the default to xrender=false.
The question is if you really want to force a new default setting on your average Linux users - especially if there's a chance it could be reverted back to xrender=true with the release after that one.
Having a default value flipflopping around between releases is something that an average user might not expect. So if we can fix the double buffering issue before we hit your release freeze, and thus leave xrender=true as default for the foreseeable future, that would be more end-user friendly, I'd say. But, just my 0.02€. We're just "guests" in your project, you guys make the rules.

**Comment by mattatobin** [comment]
Well I am just sayting that is what preferences as well as the release notes are for.

The Phoenix-based browsers pull up the release notes on every upgrade. Though I don't think it is a big deal if the pref gets flipped off then back on in the course of releases because it would get mentioned in the release notes.

Now comes as the deal you said earlier. Given xrender does no favors for non-remote users should it be enabled by default even if this snag is resolved? Should it have been enabled by default to begin with?

I don't know. I also don't know if I should override gre and disable it on my projects in default application preferences.

**Comment by stefanbaur** [comment]
Valid questions - which I am not qualified to answer, lacking both a coding background in general as well as knowledge of the Mozilla source code Pale Moon is based on. @wolfbeast, @Ionic - what's your take on this?

**Comment by mattatobin** [comment]
Dude, we have FIVE allied projects going across three enties with four in post-release production and one in development. It isn't just Pale Moon.

**Comment by stefanbaur** [comment]
... which makes me even less qualified to answer your questions. ;)

**Comment by wolfbeast** [comment]
@mattatobin Our default was false when we just started out on our fork. I set it to true to cater to remote usage because it went both ways: enabling xrender had no benefits, but also no detrimental effects for local users. This catered to everyone at the time. If this is a problem for local users with this patch to solve the bottleneck for remote users, then the situation changes.

2 options:
1. Fix the Intel/hybrid issue with the patch in place, and leave xrender enabled by default.
2. Don't fix it, and set xrender default to false, to be enabled by remote users (or remote-focused products) as-needed.

**Comment by stefanbaur** [comment]
Sooo ... aim for solution 1; if @Ionic can't fix it in time, use solution 2. Sounds like a plan.

**Comment by mattatobin** [comment]
Works for me.

**Comment by stefanbaur** [comment]
Hi,

@Ionic provided me with two new test builds, one GTK2, one GTK3.
I've tested both locally and remote, and they're looking good.
I did *not* do side-by-side testing this time, but I did visit all the pages I used for the original tests, as well as Google Street View. The nasty flicker in local mode is gone in both builds, and yet both scroll nicely via remote. For all tests, I tested scrolling manually, using the scroll wheel, using the PgUp/PgDown keys, and the UpArrow/DownArrow keys.
Unless you want me to re-test with skia instead of cairo, or do side-by-side tests again, I'd say we're done here, and @Ionic merely needs to send you the changes.

-Stefan

**Comment by mattatobin** [comment]
Well as Moonchild said, as long as skia doesn't crash or suffer too badly from the change I think we are fine on that front.

What about the intel/hybrid issue?

**Comment by stefanbaur** [comment]
The intel/hybrid issue was the flickering in Google Street View, that's why I tested it. Looks fixed.

**Comment by mattatobin** [comment]
Cool! Well, I have no outstanding issues so consider the "Tobin Factor" satisfied. If issues crop up in the future we can always tell people to flip the pref off and/or flip it by default in an update.

**Comment by adeshkp** [comment]
I also encountered flickering while scrolling on the latest master. I don't have a hybrid setup but my computer uses (old, older..) Intel graphics and build is GTK2. As mentioned above, after setting xrender to false, it went away. I didn't try to bisect but this must be it.

I'm glad @Ionic has found a proper solution for this.
