### ISSUE TITLE
Can't install https Everywhre on Basilisk-Browser

### ISSUE THREAD

**Issue by cokeflash** [MoonchildProductions/UXP#1079]
Hi!

How can I install "https Everywhere on Basilisk-Browser"?

See picture:
[url=https://postimg.cc/jLsrQ8ck][img]https://i.postimg.cc/jLsrQ8ck/null-can-t-install.jpg[/img][/url]

It says...

(null) could not be installed because Basilisk does not support WebExtensions...

How can I fix that?

How can I install https Everywhere on Basilisk?

Please help, thanks!

**Comment by Ascrod** [comment]
Please use the [forums](https://forum.palemoon.org) for questions like this. The bugtracker is for tracking verified (or probable) bugs, not for general Q and A.

To answer your question, the problem is exactly what it says on the tin. Basilisk does not support WebExtensions, and I'm guessing that you are trying to install the HTTPS Everywhere add-on from Mozilla's add-ons site, which only provides WebExtensions. You will need to use a version of HTTPS Everywhere that is not written with WebExtensions.
