### ISSUE TITLE
PM28.5.0 - linux/ppc64: compile time error: static assertion failed

### ISSUE THREAD

**Issue by rpxrpxrpx** [MoonchildProductions/UXP#1092]
Compiling PM 28.5.0 stops because several static assertions fail. This was no problem in versions: 28.3.0, 28.4.0, 28.4.1

>/usr/src/UXP-PM28.5.0_Release/js/src/gc/Heap.h:935:1: error: static assertion failed: Ensure our ChunkBitmap actually covers all arenas.
146:24.72  static_assert(ArenaBitmapBytes * ArenasPerChunk == sizeof(ChunkBitmap),
146:24.72  ^~~~~~~~~~~~~
146:24.72 /usr/src/UXP-PM28.5.0_Release/js/src/gc/Heap.h:948:1: error: static assertion failed: If the chunk padding is larger than an arena, we should have one more arena.
146:24.72  static_assert(ChunkPadSize < BytesPerArenaWithHeader,
146:24.72  ^~~~~~~~~~~~~
146:24.72 /usr/src/UXP-PM28.5.0_Release/js/src/gc/Heap.h:960:41: error: size of array ‘padding’ is negative
146:24.72      uint8_t         padding[ChunkPadSize];
146:24.72                                          ^

**Envionment** 
OS: Debian sid, PPC64
Compiler: gcc 7.4.0
Sourcecode: UXP-PM28.5.0_Release.tar.gz

**Investigation so far**
- The assertion instructions are also in the source code of version 28.4.1. But there they do not trigger errors. (I have no idea why? Maybe other gcc flags from Makefile?)
- the ".mozconfig" files were almost the same (difference in target directory MOZ_OBJDIR)
- I unsuccessfully tried to insert some sprintf-Statements to see the current values of *ArenaBitmapBytes*, *ArenasPerChunk* and *ChunkBitmap* but the compiler did not like my code. I appreciate any suggestions for this.
- a complete logfile is attached to this post.

Thank you for reading this.

[logfile2.txt](https://github.com/MoonchildProductions/UXP/files/3191206/logfile2.txt)

**Comment by g4jc** [comment]
Don't have a PPC64 available to test with, but "error: size of array ‘foo’ is negative" is commonly caused by attempting to compile ppc32 builds (-m32) on ppc64 (-m64) .

To quote a [similar](https://bugs.winehq.org/show_bug.cgi?id=28981) bug report:

> Debian/sparc64 has a 32-bit userland anyway and you need -m64 to tell gcc you don't want to compile for 32-bit.

**Comment by mattatobin** [comment]
You have to realize that our ability to help with AltArch is limited because we don't have the hardware to test on. However, @g4jc may be correct.

That being said, in the future, your first stop should be the Pale Moon forums NOT the repository issue tracker.

**Comment by rpxrpxrpx** [comment]
Thank you for the hint with (-m32) and (-m64). I will check on the Makefiles in the different releases.

> That being said, in the future, your first stop should be the Pale Moon forums NOT the repository issue tracker.

Sorry, I did not know that. The last time I posted a linux/ppc64 bug and its fix in the palemoon forum there was a corresponding issue in this tracker afterwards. So I thought it would be a good idea to post here directly. Thanks for the hint.

**Comment by wolfbeast** [comment]
The last time you posted is the workflow it should be :) 
You skipped a few necessary steps this time.

1. Forum posts, discussion about a potential bug
2. Confirmation of the bug being on our side (also on the forum)
3. An issue is created to track it
4. Issue is handled/resolved

Steps 1 and 2 are important because it keeps our issue tracker free from general questions, build config errors, OS config/distro bugs, other PEBCAK errors, etc. etc. etc.

**Comment by mattatobin** [comment]
One reason for this policy is that beyond Pale Moon and Basilisk specific bugs, the Unified XUL Platform is used beyond just the Moonchild Productions applications produced.

Keeping the issue tracker focused to tangible development issues and progression of changes and actions promotes clairity for all those involved and may be affected by them.

Otherwise it would be as Moonchild describes and would indeed be of a higher noise level for those not dealing with issues that affect just one application. That too will be remedied in the future by splitting off MCP application specific code to their own repos.

**Comment by wolfbeast** [comment]
Regression from #186
