### ISSUE TITLE
Code Cleanup: Removal of keygen element

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1103]
The KEYGEN element was [removed from HTML spec](https://github.com/w3c/html/issues/43) and never properly implemented in the first place per the proposed removal ticket in [m-c 1315460](https://bugzilla.mozilla.org/show_bug.cgi?id=1315460). It apparently has at least one obscure user (per bug ticket), but as we already removed the "[Cert-O-Matic Root CA](https://bugzilla.mozilla.org/show_bug.cgi?id=1426672) server" component during the NSS updates, I'm pretty sure it is buggy dead code.

The cleanup would give us a a little over 1046 deletions.

The path for this removal is:
* [m-c 1334694 - remove token arguments from nsIX509CertDB.importPKCS12File and exportPKCS12File](https://bugzilla.mozilla.org/show_bug.cgi?id=1334694)
* [m-c 1315460 - Remove support for HTML Keygen](https://bugzilla.mozilla.org/show_bug.cgi?id=1315460)

Patch: [1](https://paste.debian.net/plainh/f4263dc8), [2](https://paste.debian.net/plainh/d8cc75de/)
Build Passing.

**Comment by mattatobin** [comment]
I don't see why we should remove it and DAMN SURE not remove it from nss.

**Comment by g4jc** [comment]
As per above, our version of NSS already has Cert-O-Matic removed it from NSS, so there are no removals from NSS required.

Removal Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1426672
Removal Commit: https://hg.mozilla.org/projects/nss/rev/6c058f8139640e7e150e79073ebcc815a8aeaf79

Our code base: http://xref.palemoon.org/uxp-trunk/search?string=Cert-O-Matic&find=

**Comment by mattatobin** [comment]
Then since it was busted by nss update the html bit can go.

Proceed unless the Moonchild has anything to add.

**Comment by wolfbeast** [comment]
No

Cert-O-Matic is certcgi which has nothing at all to do with `<keygen>`. The keygen tag works perfectly in Pale Moon and I'd like to keep it that way at least for the time being. It's only deprecated because people were pushing js WebCrypto instead, but there's nothing wrong with the key generator, and NSS still fully supports it.

Also, you were just echoing what other people have incorrectly said. It WAS properly implemented in Firefox, but it was placed in the parser so potentially the wrong component for this.
Firefox can keep hobbling after Chrome with removal of useful features all it wants, doesn't mean WE are going to.

See it in action:
https://www.html.am/tags/html-keygen-tag.cfm

**Comment by wolfbeast** [comment]
As long as this works (and I know for a fact it's actually still in use on some websites), I'm seeing no reason to keep this issue open or have any intent to remove it.

As was made painfully clear recently, the "HTML Living Standard" state of things does not provide any reasonable basis to drop features or even consider them a state to aim for, since they both (WhatWG as well as W3C) have become nothing but mirrors of What Google Does™.
Let's keep our development reactive in the case of HTML.

**Comment by mattatobin** [comment]
I should have looked into it more before agreeing with something I initially felt sounded retarded. Oh well. Glad we aren't removing a perfectly working thing-a-ma-bob!
