### ISSUE TITLE
Punycode issue with Anchor Element 

### ISSUE THREAD

**Issue by dhoko** [MoonchildProductions/UXP#1125]
Hey :wave: 

I don't know if it's the right place to report this issue but I didn't find a button on the website to report an issue, and there was this link here https://github.com/MoonchildProductions/Pale-Moon

So what's the issue ? The encoding of links inside the Anchor Element, which is not correct cf

```js
{
  const a = document.createElement('A');
  a.href = "http://xn--e1aybc.xn--p1ai/";

  // a.href -> "http://тест.рф/"
  console.log(a.href);
  // a.getAttribute('href') -> "http://xn--e1aybc.xn--p1ai/"
  console.log(a.getAttribute('href'));
  // a.toString() =>  "http://тест.рф/"
  console.log(a.toString());

}
```
> _comments are the output on Palemoon 28.5_

### Chrome
![Screenshot from 2019-05-27 11-15-09](https://user-images.githubusercontent.com/713283/58409795-257b2d00-8071-11e9-982a-0c31b6cea87e.png)

### Firefox
![Screenshot from 2019-05-27 11-14-59](https://user-images.githubusercontent.com/713283/58409806-29a74a80-8071-11e9-99e5-5e92f7bb79ab.png)

### Palemoon 28.5

![Screenshot from 2019-05-27 11-15-32](https://user-images.githubusercontent.com/713283/58409810-2ca23b00-8071-11e9-8fbd-3d9f8a0caf5b.png)

The encoding doesn't match Chrome/FF ([USVString](https://developer.mozilla.org/en-US/docs/Web/API/USVString))

---------------------------

PS: Can you add a button **report an issue** on your website ?

**Comment by wolfbeast** [comment]
> Can you add a button report an issue on your website ?

Issues should be reported first and foremost on the forum.

**Comment by wolfbeast** [comment]
I don't think USVStrings have anything to do with this as those in fact do contain UTF, and the string type has nothing to do with punycode-or-UTF for an IDN.

Seems the root change was the one done in https://bugzilla.mozilla.org/show_bug.cgi?id=945240 The problem is that this also causes a lot of fallout because the internal representation of IDNs is used for the UI and e.g. history and bookmarks handling. We don't want punycode there, we want UTF as we have now. See dependent bugs on that one that, if we take this change, _must_ all be implemented too or our URL handling will be broken.

Is there a specific reason punycode is asked for in this situation, other than "other browsers do this too"? I would actually think that a.href being `http://тест.рф/` would be more helpful in just about all cases than punycode -- it would be translated to the proper punycode when navigating anyway.

**Comment by wolfbeast** [comment]
@dhoko Please take a moment to answer my question in the last paragraph. As it is I currently see no reason to change this behavior -- it needs a rationale which is currently lacking.

**Comment by dhoko** [comment]
> Is there a specific reason punycode is asked for in this situation, other than "other browsers do this too"? I would actually think that a.href being http://тест.рф/ would be more helpful in just about all cases than punycode -- it would be translated to the proper punycode when navigating anyway.

Well IE11 and Edge do it (as palemoon) ;) 
Issue is, when your inside the browser as a user of course it's not an issue, now when we talk about apps using the dom API etc. to create interaction here it comes.

Scenario (_we have it inside our WebClient_):

An email with links.
You want to intercept the click, to display a modal with the link. Why ? Because you want to ask to the user if it's really ok to go there.

Issue:
With a punycode link I can display google.com, if I open the modal to display google.com instead of xn-xxxxxxxx it's bad, for the user, for security etc. 
_Of course I can still have a fallback but it's better if the browser does it _

The dom API is able to give us the raw value of the string, even if the end-user won't need it, any dev using the API will need it one day or another ;) 
And as today we see more and more webapps, it's mandatory it have it inside the dom API imho.

**Comment by wolfbeast** [comment]
Sorry but that really isn't compelling. **Nobody can read punycode off-hand, so presenting that to a user serves absolutely no purpose.** You're apparently of the opinion that _all_ internationalized domain names are by their nature bad or trying to spoof. That's not the case.

Let me turn this around. You have an e-mail with a (valid) IDN in it and want to make sure the user goes to the intended domain. If you present the punycode version to the user, they will have no clue if the domain is correct or not.
In addition, in a web client it's also simple enough to get node content without using a "to string" conversion whether implicit or explicit, to get a raw URL. IMHO stringifying it should produce an as-legible representation as possible, meaning UTF-8 presentation.

In addition, this does nothing to mitigate redirections to IDNs or similar.

We also already have IDN information in the identity panel (which will display punycode for https IDNs by default, while leaving the URL in the address bar internationalized, so the user can easily see if the target website is a spoofed western character domain or not.

**Comment by dhoko** [comment]
> You're apparently of the opinion that all internationalized domain names are by their nature bad or trying to spoof

That's not the point, the goal is to ensure the user goes to the page he expects when he clicks on a link to prevent homograph attacks. We want to be able to confirm the action, nothing else [cf confirmation link](https://protonmail.com/support/knowledge-base/link-confirmation/). 

>  in a web client it's also simple enough to get node content without using a "to string" conversion whether implicit or explicit, to get a raw URL.

Voilà and with every browsers toString returns the raw URL, not Palemoon ;)

**Comment by mattatobin** [comment]
Okay, let's settle this.. Are there any frameworks and websites out there beyond your own that suffer from issues regarding this behavior?

**Comment by dhoko** [comment]
As a dev I want to use as much as I can a native API when the API works well. I don't like to polyfill even if it's only for one or 2 browsers. 
For IE11 I can understand as it's dead.
Edge is going to move to chromium so ok.
PaleMoon is based on a fork of Firefox (ESR right ?) it's alive, it should comes with the same API as Safari, Chromium and Firefox... At least follow Firefox (_which is the one with the best API for this use-case_).

Having to polyfill this modern is sad imho. It's not a major issue as we can load a lib if we detect there is no support for the feature, it should be useful for old or very bad browsers, not a modern one. 

And PaleMoon is not so popular, unless you test your code against it you won't see the bug. 
Today PaleMoon doesn't follow the standard (_if it's not, then the common behavior across all modern browsers_) and imho it should.

**Comment by wolfbeast** [comment]
> That's not the point, the goal is to ensure the user goes to the page he expects when he clicks on a link to prevent homograph attacks. We want to be able to confirm the action

It *is* the point. As stated if you present a punycode URL to a user in a confirmation doalog, does the user know it's the correct URL? No, he/she does not, because nobody can "read" punycode. You are going to assume that users "consider the URL malicious if it's an IDN", and are assuming IDNs are only used for homograph attacks and not for legitimate purposes.

Also, you've dodged @mattatobin 's question so we'll have to assume it's only in your code that this is an issue and not in any "standard" framework. In addition, if you want to use this method you still have one of the three options that gives you what you want (getting the attribute explicitly instead of relying on implicit implementation behavior of toString on an anchor element that is unspecified) so you can use that as a solution for browsers that use the more logical implementation.
