### ISSUE TITLE
Search bar works incorrectly in about:home with POST search plugins.

### ISSUE THREAD

**Issue by benjrjoseph** [MoonchildProductions/UXP#1134]
This bug can be found in the search bar of the page about:home. Details are as follows:
If a search plugin use the method "POST" to submit the query such as SearX (https://addons.palemoon.org/search-plugins/#searx), then no search result will be obtained, only the homepage of that search engine will be returned.
I have tested this bug in version 28.5.x.

**Comment by wolfbeast** [comment]
Hmm peculiar at least because we **do** have specific facilities for using POST methods in search engines in the aboutHome js code.

**Comment by wolfbeast** [comment]
Seems we lost some toolkit functionality required for Pale Moon's `about:home` code to function as-intended because it was stripped out of m-c in favor of the new search "panel" which doesn't use a raw representation of the url-encoded POST data (`postDataString`) anymore.
This should be easy enough to reinstate for pale Moon and any other application's code that requires it.

**Comment by wolfbeast** [comment]
Verified with searx -- although searx itself crashed because google complained (captcha required) the passing forward of search terms and using the POST method are working properly.
