### ISSUE TITLE
Strange file URI handling with nsIExternalProtocolService on Windows

### ISSUE THREAD

**Issue by Ascrod** [MoonchildProductions/UXP#1178]
While fixing [this issue](https://github.com/Ascrod/ambassador/issues/66) in Ambassador, I stumbled on an odd behavior with this service in Windows. The behavior does not manifest in Linux, and I haven't tested it in OSX. The issue is apparently long-standing and not specific to UXP, as I was able to reproduce this same bug in the standalone version of ChatZilla 0.9.92 for Windows (which builds on XULRunner 35.0.1). I have not yet tested this in Firefox on Windows.

**Method to Reproduce**
From any UXP application on Windows, run the following code in the Javascript Console:
`Cc["@mozilla.org/uriloader/external-protocol-service;1"]
    .getService(Ci.nsIExternalProtocolService)
    .loadUrl(Services.io.newURI("file:///C:/example.txt"));`

When the "Launch Application" dialog appears, pick a suitable application (such as Notepad++).

**Expected Results**
The URL passed to the external application is `file:\c:\example.txt`.

**Actual Results**
The URL passed to the external application is prepended with the application's working directory, e.g. `C:\Program Files\Example App\file:\c:\example.txt`, and causes it to be mishandled by most external applications.

**Comment by mattatobin** [comment]
Because the browser element its self isn't navigating you need to catch this with your contentAreaClick routine and either stop it or find something else to do with the file protocol.

Interlink has the same issue and I am going to simply throw up a message that reflects that.

**Comment by FranklinDM** [comment]
I don't think there's something wrong with the behavior of `nsIExternalProtocolService`. If you check the command line argument of the test program using Task Manager (in Details tab, with the Command Line column shown), `file:///C:/example.txt` was passed correctly.
![externalproto](https://user-images.githubusercontent.com/11641537/61184669-1bde7080-a683-11e9-8a1d-289696ad15ef.PNG)

Most Windows applications (like Notepad++) might treat `file:` as invalid when it is found. The `file:///` protocol or part should be stripped or use `nsIFileProtocolHandler` instead because that passes the argument to the target application correctly.

For example, with:
`Cc["@mozilla.org/uriloader/external-protocol-service;1"] .getService(Ci.nsIExternalProtocolService) .loadUrl(Services.io.newURI("C:/example.txt"));`

![notplus](https://user-images.githubusercontent.com/11641537/61184665-0b2dfa80-a683-11e9-8c79-a1864beedce8.PNG)
N++ will prompt you to create the file if it doesn't exist in the correct location.

**Comment by Ascrod** [comment]
@FranklinDM On further inspection, you are correct; the "file://" URI does get passed appropriately as indicated by Task Manager. I hadn't thought to look there - d'oh!

I did some further testing on Windows 7 with trying to open a text file with various applications, and while I still ran into issues with notepad.exe and N++, I found that explorer.exe would open the file in the default editor. (I haven't tested on W8 or W10, so maybe they've patched something to handle passing "file://" URIs to text editors.) I had not previously tested with different kinds of files or a wider set of applications, so that's on me. Sorry for the bugspam.

Thanks for looking at this. I'll close this issue now - please mark it as Invalid.
