### ISSUE TITLE
Arm optimization-specific issues

### ISSUE THREAD

**Issue by dimag0g** [MoonchildProductions/UXP#1247]
I have identified a couple of additional issues in the ARM build, which only appear when I use gcc-8.3 with various optimization options. Nevertheless, in my (limited) understanding those are genuine bugs which can be fixed.

The first one concerns a template function [defined](https://github.com/dimag0g/UXP/commit/345645b0e70d17e0a714ea889ae3ad32277de7f3)  in gfxFont.cpp. Since the definition is not in the header file, the instances calling it from different compilation units cause linker errors. The stopgap fix I made is to add the specific definition (unsigned char) to gfxFont.cpp. Another option would be to move the definition to the header file.

The second issue [concerns](https://github.com/dimag0g/UXP/commit/0dfbc9bc8bd95310ea099ba0685d3351cc9e1f1d) a function in xptcstubs_arm.cpp which is defined as static yet seems to be used elsewhere, again resulting in linker errors. Defining it with external linkage fixes the problem for me.

Could someone with good knowledge of the code comment on these?

**Comment by wolfbeast** [comment]
Why is the first concern ARM-specific? Which optimizations in gcc 8.3 are you talking about?

**Comment by dimag0g** [comment]
@wolfbeast The first issue seems to compiler- or optimization-specific, or triggered by the compiler options I have tried (notably -O3 and -flto) or by the use of gcc-8.3. It may be due to strict type aliasing (included in -O2 and up) forbidding a <char> template definition to be linked against and <unsigned char> invocation. Specifically, that invocation in `gfxTextRun::SetSpaceGlyph()`

**Comment by mattatobin** [comment]
Don't use -O3 and likely don't use -flto.

**Comment by dimag0g** [comment]
@mattatobin I know. Still, if what surfaced from my experiments are actual issues, I think they should be fixed. Unless of course there is a reason why a function used elsewhere is declared static, or why a template is inside a cpp file and not in the header file as  [this](https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl) cpp faq suggests.

In the end it's up to the repo owner to decide which changes are welcome and which are not. I'm totally fine with keeping those locally, but I don't want to do so without giving you a chance to see them first.

**Comment by wolfbeast** [comment]
We have tons of `template <>` definition in our cpp files throughout our tree. While not necessarily good practice for structured programming, it is also not an error doing so.

If it was due to strict aliasing then it would have come to light in our normal release builds that are built with -O2. For any sort of release build from our tree you should not be using -O3, it's known to cause multiple issues. Link-time code optimization is also strongly discourages since it can cause instabilities -- compilers simply have trouble dealing the sheer number of functions in our code base, and if you toss it all in one big heap for the linker to sort out... it will choke.
So, please don't use -O3 or -lto; check if your issue still exists with -O2 and if not, then we're unlikely to accept the change as it's more likely to be a compiler bug than a code bug. We can't force our code to be compatible with every compiler and combination of optimizations out there.

As for the second issue, that certainly seems reasonable, although you may end up with function ambiguity -- if they are meant to be two different functions depending on which module you're in, then making them equal isn't exactly the intended result ;)

**Comment by mattatobin** [comment]
So what is the status of this?

**Comment by dimag0g** [comment]
@mattatobin I have made half a dozen of test builds, all with sane options and without the changes being discussed, and they all passed. I'm still wondering how that template works when the declaration is in a different compilation unit, but since it does work, I think we can close this, at least for now.
