### ISSUE TITLE
Removing watch/unwatch classes breaks the statusbar (s4e) module

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#1261]
After watch/unwatch classes removal in #1257, the statusbar (s4e) module does not work properly.

Console error:
```
TypeError: this._window.XULBrowserWindow.unwatch is not a function
	buildBinding/< resource:///modules/statusbar/Status.jsm:130:7
	forEach self-hosted:282:13
	buildBinding resource:///modules/statusbar/Status.jsm:128:5
	updateWindow resource:///modules/statusbar/Status4Evar.jsm:123:5
	setup resource:///modules/statusbar/Status4Evar.jsm:57:5
	buildS4E chrome://browser/content/statusbar/overlay.js:14:3
```

See also: https://github.com/SparkyBluefang/S4E/issues/55.

**Comment by mattatobin** [comment]
We can likely incorperate/convert the polyfill into a jsm and provide the funtionality on demand for compoents and extensions that rely on watch.

I'd like to take a shot at it but I will almost certainly fail :P

**Comment by wolfbeast** [comment]
It should probably be rewritten using a [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)

**Comment by mattatobin** [comment]
Yeah, of course but I was thinking more about extensions and that if I could pull it off it could be used temporally for s4e and the Pale Moon status bar components as blocker repellent.

**Comment by JustOff** [comment]
Well, it seems that to fix the issue using [polyfill](https://gist.github.com/eligrey/384583), it should be embedded at the beginning of [browser.js](https://github.com/MoonchildProductions/UXP/blob/master/application/palemoon/base/content/browser.js). This ensures that `watch`/`unwatch` methods are defined before the `XULBrowserWindow` object is initialized, for which they are called later in [Status.jsm](https://github.com/MoonchildProductions/UXP/blob/master/application/palemoon/components/statusbar/Status.jsm).

It's likely that this approach can also provide sufficient compatibility for extensions, although this requires additional testing and is not really part of this issue.

**Comment by wolfbeast** [comment]
I'm pretty sure you can use a proxy to rewrite the way s4e code watches for changes to the various properties, but it'll be more work (and more something for the original author of the code to look at if he wants his extension to be usable on updated versions of the browsers out there), but honestly, there are multiple ways you can approach this problem.

All watch really needs to do is call a custom function when a property's value changes. The easiest way to achieve that is to override the setter function (since changing a property value is done through a setter) to something you control, and intercept the setting of the new value. Intercepting functions is exactly what proxies are for. The polyfill works by manually assigning values to properties if watch is used, but that isn't necessarily the right thing to do _globally_, so I'm not happy with the solution that it needs to be top-level in browser.xul; that's just exchanging one problem for another, although it _might_ work around `watch()`-dependent chrome scripts from extensions. We just can't have these functions persist in content because It Breaks the Web™.

It should be possible to just slot these watch/unwatch functions from the polyfill into `status.jsm` as an interim solution for -this- particular problem; I'll have a poke at that tonight.

**Comment by JustOff** [comment]
Although I agree that having a polyfill in `browser.xul` is definitely not the best solution, it is still not visible to the content, so the web is safe. And of course it will be great if you manage to slot it into `status.jsm` only.

**Comment by wolfbeast** [comment]
It wasn't that difficult to slot into `status.jsm`.
It only needs it on `S4EStatusService._window.XULBrowserWindow` so the easiest way was just to define the functions on-the-fly if they aren't defined yet (i.e. when `buildbindings()` would be re-called or it would be defined globally by something else, or what not), only on that object. The observed properties are simple so it's safe to do it the polyfill way (since it actually deletes and recreates the properties it wouldn't work on more complex properties that need e.g. custom accessors/functions preserved).

Also, considering we're not using it as an extension, we don't need the bit for regenerating bindings in case `XULBrowserWindow` would be changed because that never happens with it being part of the browser chrome itself; this allows us to skip the check and handler on the (otherwise nonconfigurable) `XULBrowserWindow` which would otherwise be a snag because you can't `defineProperty` on something nonconfigurable.

Patch incoming.
