### ISSUE TITLE
Graphics crash on systems missing gpu_shader5

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1354]
There are some systems on Linux that bork on not having shader model 5 support, causing crashes when ANGLE tries to use it anyway based on the detected GL version.

See forum discussion https://forum.palemoon.org/viewtopic.php?f=37&t=23512

This came to light when we enabled GPU acceleration by default on Linux.

**Comment by zqqw** [comment]
It still doesn't fix the problem. There could be some change or improvement because on the first run it went almost all the way though the paper, but still flickering a lot. Subsequent runs crashed or froze more quickly. Possibly some caching makes it crash quicker then? One made the left 80% of the Pale Moon window into a featureless gray block which I hadn't seen before.
Also it played https://threejs.org/examples/webgl_video_panorama_equirectangular.html for 4 or 5 loops before crashing.
I tried the latest Pale Moon stable on a friends computer, slightly older with not so good Nvidia graphics also using Nouveau. On the demos on the threejs homepage that would crash even with hardware acceleration deselected in preferences and layers.acceleration.disabled set to true. On that PC Chromium wouldn't play it and said you need a new driver, Firefox worked and played everything (slowly, but it worked) so I suspect there is more than one issue with this sort of content on Linux.

**Comment by wolfbeast** [comment]
I'm not sure what else can be done here aside from flat-out hard blocking WebGL...
Can't you install other drivers? doesn't NVidia provide drivers for Linux?
Anyone else have any other idea?

**Comment by zqqw** [comment]
Nvidia drivers often don't work, or break on updates. As they are closed source nobody can fix them or figure out what else needs fixing to support them. And Nvidia is always dropping support for older hardware sooner or later. So they are not worth worrying about and it's better to support open source software. There isn't really a problem for me personally when I disable layers acceleration, it would be nice to get it working for other Linux users though. I was thinking of searching for more threejs related Mozilla patches to try as it works there. mrdoob must be a Firefox user.

**Comment by wolfbeast** [comment]
The problem is we don't have enough data, here. Mozilla kept this in nightly for a while, then disabled it entirely on all channels, and only enabled it again when they made it dependent on people choosing WebRender (a different rendering back-end that we don't have in Goanna) so it's not known how many people would be affected by it. I think the best we can do is disable accelerated layers by default  based on the "nouveau" vendor since it doesn't properly identify itself with hex IDs and there's no way to determine device ID for blocklist purposes from the nouveau driver as it doesn't follow the industry standard.

The question is then: how many Linux users use these drivers? And if it's "pretty much everyone" then why should we bother to change anything?

**Comment by wolfbeast** [comment]
One thing you CAN try is disabling xrender to see if that stops the crashes with layers acceleration enabled.

**Comment by zqqw** [comment]
A lot of people use it I think, over a million Ubuntu installations:
https://popcon.ubuntu.com/
xserver-xorg-video-nouveau   installed  1205733 times
It's difficult to compare numbers with nvidia drivers as there are numerous variants. Nearly all distros ship with open source drivers as default, and when it comes to graphics 'cards' (or similar, as on laptops it might be soldered in now) Nvidia is the most common. Intel has more 'built in' budget graphics overall. Often you need to enable "non-free" repos to install the Nvidia drivers. Most gamers would probably want them but for regular web browsing there's usually no need.
Open source graphic support is an aspiration in Linux and it's improving a lot. Intel is most helpful so those graphics typically perform well, I've read.
Disabling xrender did not help.
Probably the main thing is to avoid the crashes and freezes. If some content doesn't display or isn't hardware accelerated it's less of a problem. It would have been nice to find a simple solution. If it was disabled on nouveau, could it be switched back on if desired rather than disabled completely, it might be OK on newer hardware?

**Comment by wolfbeast** [comment]
Following discussion over trillian/xmpp we'll be approaching this differently. New issue about that is #1360
Of course further improving general compatibility with various drivers/hardware is always desirable but I'll be closing this for now since there doesn't seem to be a further issue with this particular GPU feature after the committed changes.

**Comment by wolfbeast** [comment]
Regardless of the work being done in #1360 soon, I still have a few things to check that should help with crashes in this area/might potentially allow more users to enable HWA.

I won't land this straight away since it touches some DOM canvas stuff and I'm not going to interfere with the large ongoing DOM work that has absolute priority to land. I'll have a work branch to test soon, @zqqw.

**Comment by zqqw** [comment]
I'm happy to hear you have some ideas to resolve this and will be glad to try that out. Although there's apparently not that much of this sort of web content yet on most sites, outside of demos, it's worth keeping up to date I expect. I was reading about how threejs works, (presumably other webgl libs are similar) and it seems the library on GitHub can be included by url so the latest one will always be used. So even if the browser and website do not change, new things can be introduced on an existing site. I expect you knew that already, but it explained a bit to me.

**Comment by wolfbeast** [comment]
Please see if building from https://github.com/MoonchildProductions/UXP/tree/gl-work is any less crashy for you?

**Comment by zqqw** [comment]
gfx/gl/GLContextProviderGLX.cpp
     MOZ_ALWAYS_TRUE(mGLX->xMakeCurrent(mDisplay, X11None, nullptr));
Missing a closing ) bracket, build resumed now.

**Comment by zqqw** [comment]
It didn't seem to make any obvious difference. I tried running it with valgrind. It found some delete / free issue that is unrelated I think, and provided a backtrace when it crashed on the infinitown demo, with layers.acceleration.disabled=false. Here are some more output results.

[2020-01-22testing.tar.gz](https://github.com/MoonchildProductions/UXP/files/4095004/2020-01-22testing.tar.gz)
[valgrind-infinitown.tar.gz](https://github.com/MoonchildProductions/UXP/files/4094962/valgrind-infinitown.tar.gz)

**Comment by wolfbeast** [comment]
Well then. I tried what I could to resolve this -- it's clearly not viable at this time to enable layers acceleration by default on Linux and we'll go ahead with #1360 with a default-disable.
