### ISSUE TITLE
Improve performance of table drawing again

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1355]
Since we've implemented #146 to enable relative positioning and sticky positioning on table parts, the larger display lists resulting from table drawing have caused performance regression. @win7-7 has done research what has been done at the Mozilla side to follow up on this and improve performance.
This is a tracking issue to land perf improvements against which relate to table drawing post-implementation of #146

**Comment by mattatobin** [comment]
This will have to wait until #1344 has a partial landing or is completed unless it stays well out of the way of https://github.com/MoonchildProductions/UXP/compare/master...g4jc:custom_elementsv1#files_bucket which is actively being developed on at the moment.

**Comment by mattatobin** [comment]
@win7-7 You have a go to do the things.

**Comment by mattatobin** [comment]
@win7-7 If there is more to this it might be a good idea to step up the contribution.

**Comment by mattatobin** [comment]
Is this done yet?

**Comment by wolfbeast** [comment]
No, there's one more part but it's more involved.

**Comment by mattatobin** [comment]
Is there an eta on the finsl part of this issue?

Are we gonna let that final part block this milestone? What is the final part?

**Comment by wolfbeast** [comment]
Any further issues related to this should be their own issue. Performance of table drawing is close enough to what it was before -- some regression remains expected because of the larger display list generation with the new method required for table element positioning per-spec.

**Comment by wolfbeast** [comment]
Backed out #1463 for Busting the Web™

**Comment by mattatobin** [comment]
If you choose to revisit this please explain what you are going to do and preferably for a MozRefactor like this please follow an interpretation of the bug progression if that is how you are approaching this.

Additionally, this is now back in the queue and @g4jc 's `dom` work on `ShadowDOM` and `customElements` takes priority. It is ok if this doesn't make the milestone.

**Comment by win7-7** [comment]
@wolfbeast you want to restore Layout\reftests\table-background\reftest.list back to original version that was in UXP tree as like said in commit:  "Layout\reftests\table-background\reftest.list should have only additions to the end of it. Revert incorrect additions." I accidentally changed middle of it while intending change only end when comparing it to Mozilla version of file during attempting to get final part/table columns change done so it should be restored to original UXP version.

**Comment by mattatobin** [comment]
Could you do this?

**Comment by win7-7** [comment]
Sorry for noise. reftest.list file was already reverted back to original version of file by Moonchild when he reverted both "Layout\reftests\table-background\reftest.list should have only additions to the end of it. Revert incorrect additions." and "Issue #1355 - Better way to create display items for column backgrounds." commit also. So there is nothing to do and file was already back to original version before pull request. 

I have not found solution how to fix display items disappearing so for now this is on hold unless somebody else wants to try to do this final improvement to solve this issue.

**Comment by win7-7** [comment]
I have found solution to display items disappearing with earlier pull request. Reverting Bug 1404181 - Part 2 and removing ForceDescendIntoIfVisible check from part 10 of 1409114  allow performance improvement without display items disappearing.

This will need wait until g4jc Shadow DOM is done and merged first.

**Comment by win7-7** [comment]
After an incremental merge of shadow DOM in next few days is merged can I do another pull request to get this issue resolved?

**Comment by mattatobin** [comment]
You're gonna have to wait for Moonchild to complete his deunify sources work but feel free to share exactly what you intend to do.

**Comment by win7-7** [comment]
Does 154 files with 281 additions and 452 deletions sounds better?

That would be part 1/ https://bugzilla.mozilla.org/show_bug.cgi?id=1388161

Part 2 would have 28 files changed with 554 additions and 378 deletions and would include https://bugzilla.mozilla.org/show_bug.cgi?id=1409114, AutoBuildingDisplayList changes and 1512244 - Part 1 to make it easier to backport 1409114.

Since part 2 would include 1512244 - Part 1 that would mean that chronologically to do this properly https://bugzilla.mozilla.org/show_bug.cgi?id=1441796 would need be merged first before part 2. I already have tested https://bugzilla.mozilla.org/show_bug.cgi?id=1441796 and it works with 1512244 - Part 1.

**Comment by mattatobin** [comment]
@win7-7 see https://github.com/win7-7/UXP/commit/1bd76bea8e17bc72c12df17402f2908cd70fe221#commitcomment-38713358

**Comment by win7-7** [comment]
@wolfbeast take look to: https://github.com/win7-7/UXP/commit/cf08aae6747c5a07b2b76b40839335dca1a916c6 ( 258 additions and 430 deletions)

This would still be 154 files. It would just remove parameter.

Yes, 154 files is still lot of files changed but it is how Mozilla did it in https://bugzilla.mozilla.org/show_bug.cgi?id=1388161

It would be easier to review than https://github.com/win7-7/UXP/commit/1bd76bea8e17bc72c12df17402f2908cd70fe221 having less additions and deletions for each file.

Also:

https://github.com/win7-7/UXP/commit/c00a00d6df0d68b8e29d7ffea9e90164040112ae ( 15 files changed,  23 additions and 22 deletions),

Changes nsDisplayListCollection() : to explicit nsDisplayListCollection(nsDisplayListBuilder* aBuilder) and add (aBuilder); where needed.

Change to explicit would be necessary to avoid error during compiling 1409114.


https://github.com/win7-7/UXP/commit/8381eac0b37c86902965a3edb9084c5d6ef0a306 ( 3 changed files, 80 additions and 57 deletions)

1441796 and 1512244 - Part 1.

https://github.com/win7-7/UXP/commit/096900e6a176575f4418e6cd82577a3558f3aee5 ( 29 changes files, 491 additions and 340 deletions)

1409114 and AutoBuildingDisplayList changes.

**Comment by win7-7** [comment]
As follow-up to https://github.com/MoonchildProductions/UXP/commit/6d504711a01e9be34725f9add22cc7aa311cb14f 

https://bugzilla.mozilla.org/show_bug.cgi?id=1394249 should also be added. 


@wolfbeast could you please take look to win7-7@cf08aae if this is better way for column backgrounds work since it has much less additions and deletions for files and slightly less files changed so should be at least slightly easier to review than  win7-7@1bd76be although it still has 154 files changed because that is how Mozilla did changes in https://bugzilla.mozilla.org/show_bug.cgi?id=1388161

I can do PR for commit win7-7@cf08aae later if that looks suitable for you.

I did also test with De-unified layout and fixed build bustage with layout/XUL with commit https://github.com/MoonchildProductions/UXP/commit/ff657e4dcc886a0693d690b630a8f7a5b2155422

**Comment by wolfbeast** [comment]
Sorry for the delay in responding here. just been too damn busy with everything else.

They don't _have_ to be separate PRs, just separate commits inside the PR with each commit in a buildable state so each step can be reviewed as a logical unit separately. If you already set up to be separate PRs then you can do it that way, of course.
The total volume of changed files isn't the problem per se if there is a fundamental change to a call that is called from many places, but the problem with your initial approach was that it was that _and_ other code changes all rolled into one which makes it very difficult to properly review.

I -may- have time this weekend to look at your changes, but not sure. I'd also need at least a summary description of either way you are proposing (you are proposing 2 alternatives, right?) so I can make a judgement call on it...

**Comment by win7-7** [comment]
One PR with separate commits works for me as way to get this issue resolved.

Name for such PR could be: Better way to create display items for column backgrounds (Also includes: bug 1388161, bug 1394249, explicit change, bug 1441796 part 1 and 3 and bug 1512244 - Part 1)

I can do one PR with separate commits for you to review.

Also PR should have 1394249 in it to have that printing preview fix done also.

Also I will combine "Store the dirty rect on the display list builder rather than passing it as a parameter to BuildDisplayList" and  "Fix build bustage for De-unified layout/xul" as one commit in that PR to have buildable commit.

**Comment by mattatobin** [comment]
By George, I think he's got it. Good job @win7-7 Please submit a PR.

**Comment by win7-7** [comment]
@mattatobin Done.

@wolfbeast PR is open. Please review it when you have time to do so.
