### ISSUE TITLE
Remove the obsolete <marquee> element and its interface

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1525]
`<marquee>` has been [declared obsolete](https://html.spec.whatwg.org/multipage/obsolete.html#the-marquee-element) for quite a while but is still implemented by us.
Due to the code's age and complexity (it being the only in-element animated html element) this is a potential sec issue to retain (there have been more than a few marquee-related sec bugs); in general this kind of functionality is no longer in use nor required by websites, and its CSS alternative implementation has also been [abandoned](https://www.w3.org/TR/css3-marquee/).

We should remove the `<marquee>` element, its associated `HTMLMarqueeElement` DOM interface and layout code.

**Comment by mattatobin** [comment]
Maybe we should just treat `<marquee>` as an alias for a `<p>` block in the parser so that it doesn't just vanish any content inside it or whatever would happen if the tag doesn't exist.

**Comment by mattatobin** [comment]
What about xul or the marquee binding? There IS a use case for this tag or at least a css analogue of it no matter what the w3c says.

Security issues such as what historically?

**Comment by wolfbeast** [comment]
So what's the use case for this tag?

**Comment by wolfbeast** [comment]
I'd prefer to get rid of this entirely, including in XUL and bindings.
Some sec issues that were on my radar with it: 840098 1050049 1277475 1312272

Also, I find it pretty low that you're now using the same psychological tactic you detest from forum users "Oh you're touching this established behaviour so I'll spin a 'you're just like Mozilla and cutting things one by one until there's nothing left' by pulling in the "frames" bit. Understand that `<marquee>` is a special case that has _always_ been at odds with the way the parser and layout works, and there is a reason this code has hardly been touched since the Netscape days.
And fuck your fucking blink tag.

**Comment by mattatobin** [comment]
I just really dislike removing these really old things that have always been there but if it is that prone to security issues then alright. I won't obstruct further.

**Comment by wolfbeast** [comment]
I understand; they have always been there since the Netscape days, but if there wasn't a good technical reason to not want the element I wouldn't have raised it as an issue to begin with.

It's never been part of the XUL spec either (at least there is no mention of it anywhere in my documentation, not even as a non-standard thing) so it probably isn't even included in XUL or the bindings for it.

**Comment by wolfbeast** [comment]
To the other people who tossed a thumbs down on the original post, the same question before I move forward with this:

> What's the (realistic) use case for this tag? Have you seen it in pages lately? And if you have, why is it there and why couldn't it be replaced with something less oddball/risky from an engine point of view?

@adeshkp @athenian200 @almaember1098

**Comment by athenian200** [comment]
Well, it would be used for news/stock tickers of various kinds, presumably. Yes, I see it on sites like oocities (which I do browse more frequently than I should), and sometimes on sites generated using an old version of Frontpage or something. 

That said, if it is a security risk and this is the only way to mitigate it, then I trust your judgment and can accept that you know best. I was just reading the OP and thinking that I don't really care if a standards body declares something obsolete or deems something insecure because I don't respect the people running them these days. I also didn't realize it was you that opened this issue.

**Comment by adeshkp** [comment]
Thumbs down was my original reaction initially, and if there are security issues and unnecessary maintenance burden because of keeping `marquee` in the tree then I'm okay with its removal. Reaction remains as _ideally_ I'd like to see it retained.

Another thing is that I've some fond memories of using this element when I learned a little bit of HTML in my school days. This was the first of few things we learned and we used to show off its animation effects which were achievable with very little effort. Later I saw many government/informational/educational websites also making use of marquee banners extensively.
_Back then HTML was HTML and websites were actually websites._

**Comment by wolfbeast** [comment]
> I don't really care if a standards body declares something obsolete or deems something insecure because I don't respect the people running them these days.

And that's fine. But they weren't the ones deeming it insecure. It was mentioned to underline that mainstream has already said this should go for years (but all of them are waiting for others to "go first", and I think Chrome will likely not go first here anyway because of how they approach code changes -- as in they don't.). Neither `<marquee>` not `<blink>` have been part of standards; they have been Netscape-isms that were implemented because Netscape did, way back when.

Fond memories are all well and good but shouldn't hold back development.
If you want to view archaic websites, then you should probably do so in a just as archaic browser anyway to see it really as it was intended.

**Comment by wolfbeast** [comment]
I'll be moving forward with this since there are no significant other points raised.
