### ISSUE TITLE
uxp for lazarus ide

### ISSUE THREAD

**Issue by Reaper10** [MoonchildProductions/UXP#1579]
Can you build uxp for lazarus ide and/or  Free Pascal
https://www.lazarus-ide.org/
https://www.freepascal.org/
this way people can uxp and Goanna and lazarus ide together

**Comment by g4jc** [comment]
I believe for this to work we would need to have embedded `libxul` / `XULRunner` working again. Previous work was done via [GeckoPort](https://wiki.lazarus.freepascal.org/GeckoPort_version2), for FreePascal but they stopped updating it around Gecko v10. It would also be possible to use [Python](http://pyxpcomext.mozdev.org/no_wrap/tutorials/pyxulrunner/python_xulrunner_resources.html) and pretty much any other programming language to bind to `libxul` at that point.

While this bug should likely be closed as out of scope (we can't reasonably maintain a Delphi binding Library), the long-term ability of restoring `XULRunner` to it's former glory so that multiple projects would be able to embed it again is a worth while endeavor.

**Comment by mattatobin** [comment]
The XULRunner stub isn't actually required to compile the platform for use in embedding like this. The real issue is since "easy" embedding was killed by mozilla back during Firefox 4's development any embedding lib has to be uniquely rebuilt against every single version of UXP's release branch state. You couldn't just slide in one platform package for another like you could in the gecko/1.9.x days. Additionally, just building the same code state with different build options would require rebuilding the embedding lib against it as well.

That is why everyone dropped any support for embedding gecko. The burdon is too great. So literally we would have to provide a standard release for it for every platform and you would have to build your embedding lib against that for each target arch/os/distro.

So no it is not even reasonable for anyone anymore. All XULRunner's restoration would be good for is using the stub with a xulapp package not embedding.
