### ISSUE TITLE
Add Haiku support

### ISSUE THREAD

**Issue by extrowerk** [MoonchildProductions/UXP#1599]
Haiku is an emerging alternative operating system and the users at the Haiku forum expressed their wish to have Pale Moon available for Haiku for which we need Haiku support in UXP first.
Because you have the most experience with the codebase, please consider to support your users on Haiku too. The Haiku developers and the HaikuPorts team can give you some assistance to bridge the platform differences.

As Haiku have no X11 server and it is not planned to port it, the GUI will need more work than on *nix-like platforms where X11 is available.
Thank you!

**Comment by mattatobin** [comment]
I don't see this happening primarily from us since no one runs or knows the first thing about `BeOS` or its clone form. This will require extensive and unique code to even attempt it without a nix-type stack of technologies.

It is not impossible but it would require an extremely adept and dedicated maintainer to even attempt such a thing.

**Comment by CodeforEvolution** [comment]
Hello! I may be able to work on this sometime in the future! Even though Haiku does not have a X server available, Haiku is otherwise POSIX compliant and has many libraries found on other *nix systems. The primary work would be on the GUI toolkit side.

**Comment by mattatobin** [comment]
As I said it would require a lot of extensive and unique code. Have you looked through the code for other target operating system's widget code?

**Comment by wolfbeast** [comment]
So because I closed it on the Pale Moon repo with an explanation of the work needed from the user community side, it was copy-pasta opened here? I thought I was clear that the idea was to have more than some promises before opening an issue here.
I'll tag this appropriately for its current state since there isn't anything actionable for us here, at least not yet.

**Comment by mattatobin** [comment]
Mozilla removed `BeOS` support in 4.0b12pre and it was apparently already broken at that time. I don't know how much of that could even be used in UXP's codebase or even if it could be used as much of a reference.

See also: Bug 627277

**Comment by wolfbeast** [comment]
I doubt it can be used as much of a reference because pretty much everything has been changed since then in terms of /gfx, image support/handling, etc.

**Comment by extrowerk** [comment]
> So because I closed it on the Pale Moon repo with an [explanation](https://github.com/MoonchildProductions/Pale-Moon/issues/1807#issuecomment-648201114) of the work needed from the user community side, it was copy-pasta opened here? I thought I was clear that the idea was to have more than some promises before opening an issue here.
Sorry, i misunderstood you, language difference and with wishful thinking drove me to the wrong direction. Sorry.
> I'll tag this appropriately for its current state since there isn't anything actionable for us here, at least not yet.
That's great!

**Comment by hoper-a11y** [comment]
Hi. May I ask you if a X server is really needed or not if the Haiku people could have GTK working on it? A guy used to successfully ported GTK3 but because some unknown reasons I don't found it on our HaikuDepot: https://discuss.haiku-os.org/t/ported-gtk3-live/7687

Apart from GTK, which dependencies needed to have on Haiku? Please let us know. Thanks.

**Comment by mattatobin** [comment]
Yes, you need X on unix if you plan to use the unix stuff.

**Comment by hoper-a11y** [comment]
> Yes, you need X (or something that emulates X) on unix if you plan to use the unix stuff and not use BeOS stuff. However, I think it would be improper to do that.

I will ask the Haiku people if they could implement a X server and which appoach they prefer.

**Comment by diversys** [comment]
> A guy used to successfully ported GTK3 but because some unknown reasons I don't found it on our HaikuDepot: https://discuss.haiku-os.org/t/ported-gtk3-live/7687

GTK3 port is in its early stage, that's why it isn't available in the repo as a package yet.

**Comment by athenian200** [comment]
Basically, the situation is that Windows and Linux are the core focus of development, and all the other versions are maintained by UXP developers who happen to use an alternative OS and can compile UXP themselves. For instance, I run OpenIndiana and Oracle Solaris, and I got UXP to compile and run stable on that platform, so I was allowed to merge my changes into the tree. However, in my case I was just improving support for a platform that has good historical and modern support from Mozilla and Oracle, and which relies on the same X11/GTK stack as Linux does. You're going to have a much harder time.

First, what's the status of NSS and NSPR support for Haiku? UXP absolutely needs those libraries, and you will likely have to fix the Haiku/BeOS support yourself. That is a whole project in and of itself, and you'll likely have to work with Mozilla and/or the Haiku maintainers to get that done. A lot of projects depend on those libraries, and it's a requirement for a Firefox port, so there may be broad interest in porting them to Haiku. After that, the patches may need to be adapted to our in-tree versions of NSPR and NSS, but that's probably not as much work as getting them working initially.

Even after that's done, one thing I will say right out of the gate is that you absolutely _need_ knowledge of assembler to port this to a new OS.  Before you can even get started, you have to be able to write xptcall stubs for your OS on your architecture, that is to say, platform-specific assembler code for invoking XPCOM methods on native objects. Do you know enough about the Haiku kernel to write those? That's just the beginning, though.

About the memory allocator, how much do you know about the Haiku malloc libraries? I heard they did a lot of work on that last year. Is there a port of jemalloc to Haiku you could use as a base? If not, do you know enough about how Haiku manages memory to port it over yourself? For that matter, do you know the right way to get the native stack base implementation on Haiku? The stack base and the stack size? The JS engine needs that.

Now, let's talk about WasmSignalHandlers. Do you know how where and how Haiku implements various x86 registers so it can receive system signals? WasmSignalHandlers needs that information, look at all the Windows and Unix work there. For that matter, what about libffi? Do you have libffi on Haiku? I heard Haiku had trouble with getting libunwind to work properly, which depends on a lot of the same implementation details as things like WasmSignalHandlers and libffi.

There's also the matter of libevent. Does Haiku have a port of libevent at all? What about similar stuff like libev and libuv? The IPC subsystem requires that to know how your operating system handles event loops. Linux uses epoll, BSD uses kqueue, Windows uses I/O Completion Ports (which are conceptually similar to Solaris event ports), so what does Haiku use? What is your event completion framework called? You'll have to implement that into libevent.

That's what you have to get done before you can even start implementing support for whatever Haiku uses as a compositor (since I know it's not X11 or Wayland), and creating XUL bindings for whatever widget toolkit it uses on top of that.

You might be thinking it's hopeless, but I think you and the rest of the Haiku community need to make getting a port of UXP a long-term goal. Short-term, a lot of these libraries are required for applications besides UXP that have fewer dependencies, and not having them is really hurting your OS in terms of acceptance. Working towards porting UXP to Haiku is something that will probably result in your OS gaining a ton of common libraries and APIs that will be useful in porting other applications to Haiku. What I would recommend for each library is trying to find other Haiku users who want other applications that depend on that library, and work with them towards that goal, which will ultimately get you closer to your UXP port. 

If you can start making a lot of this happen within the Haiku community, and get at least all the low-level requirements done, then I would be willing to consider helping you the rest of the way, especially if you agree to help me out with SunOS once in a while in the bargain.

**Comment by hoper-a11y** [comment]
@athenian200

nss:

https://depot.haiku-os.org/#!/pkg/nss/haikuports/3/46/1/-/1/x86_64?bcguid=bc2-KTOX
https://depot.haiku-os.org/#!/pkg/nss_devel/haikuports/3/46/1/-/1/x86_64?bcguid=bc2-RYLV

nspr:

https://depot.haiku-os.org/#!/pkg/nspr/haikuports/4/19/-/-/1/x86_64?bcguid=bc2-OVPE
https://depot.haiku-os.org/#!/pkg/nspr_devel/haikuports/4/19/-/-/1/x86_64?bcguid=bc2-VHFN

jemalloc: none

libffi:

https://depot.haiku-os.org/#!/pkg/libffi/haikuports/3/2/1/-/6/x86_64?bcguid=bc2-JBUW
https://depot.haiku-os.org/#!/pkg/libffi_devel/haikuports/3/2/1/-/6/x86_64?bcguid=bc2-UPBX

libunwind: none

libevent:

https://depot.haiku-os.org/#!/pkg/libevent/haikuports/2/0/21/-/13/x86_64?bcguid=bc2-FSSL
https://depot.haiku-os.org/#!/pkg/libevent_devel/haikuports/2/0/21/-/13/x86_64?bcguid=bc2-DGTC

https://depot.haiku-os.org/#!/pkg/libevent21/haikuports/2/1/8/-/3/x86_64?bcguid=bc2-TGVT
https://depot.haiku-os.org/#!/pkg/libevent21_devel/haikuports/2/1/8/-/3/x86_64?bcguid=bc2-KGVW

libev:

https://depot.haiku-os.org/#!/pkg/libev/haikuports/4/31/-/-/1/x86_64?bcguid=bc2-GAWF
https://depot.haiku-os.org/#!/pkg/libev_devel/haikuports/4/31/-/-/1/x86_64?bcguid=bc2-KBWI

libuv:

https://depot.haiku-os.org/#!/pkg/libuv/haikuports/1/35/0/-/1/x86_64?bcguid=bc2-GLXT
https://depot.haiku-os.org/#!/pkg/libuv_devel/haikuports/1/35/0/-/1/x86_64?bcguid=bc2-XIXY

**Comment by hoper-a11y** [comment]
> If you can start making a lot of this happen within the Haiku community, and get at least all the low-level requirements done, then I would be willing to consider helping you the rest of the way, especially if you agree to help me out with SunOS once in a while in the bargain.

I don't have any coding skills so I can't actually do anything. I'm just a Haiku user that hope my favorite browser could be available on Haiku as well. The actual people that you could contact is the Haiku and HaikuPorts developers, not me! Of course I will try my best to persuade them to support the porting of PaleMoon as much as possible.

I have nothing to bargain with you. I will always ready to help you with testing your PaleMoon build on OpenIndiana without needing anything in return as long as I'm still an OpenIndiana user. My new job don't have anything to do with Illumos anymore but I still keep an OpenIndiana VM on VirtualBox.

**Comment by hoper-a11y** [comment]
I have opened a poll in the Haiku forum: https://discuss.haiku-os.org/t/port-palemoon-to-haiku/9702

You could see there are interests from users of having PaleMoon on Haiku. But the majority of people, users and developers included, seemed to don't care.

Even the guys opened this issue, he will not do anything about it other than asking: https://discuss.haiku-os.org/t/port-palemoon-to-haiku/9702/48

There was no plan or even agreement about porting PaleMoon: https://discuss.haiku-os.org/t/what-improvements-do-you-want-to-see-for-beta3/9562/59

This guy is more open and honest: https://discuss.haiku-os.org/t/port-palemoon-to-haiku/9702/5 https://discuss.haiku-os.org/t/port-palemoon-to-haiku/9702/22

And this guy clearly express his dislike for you because you don't support BLM: https://discuss.haiku-os.org/t/port-palemoon-to-haiku/9702/11 and also because he prefers to eat his own dog food, he is one of the developers of Web+, Haiku's native browser: https://discuss.haiku-os.org/t/port-palemoon-to-haiku/9702/10 I don't blame him all, as I'm the guy who spread misleading information about you and I have corrected it and post my apologize: https://discuss.haiku-os.org/t/port-palemoon-to-haiku/9702/31

This issue I posted on their HaikuPorts: https://github.com/haikuports/haikuports/issues/5132

This waddlesplash guy clearly has bias and prejudice about you, read his comment: https://github.com/haikuports/haikuports/issues/5132#issuecomment-647789823

After I already make corrections to him about his wrong idea about PaleMoon on the forum, when I asked to reopen this issue, he still refused: https://discuss.haiku-os.org/t/port-palemoon-to-haiku/9702/47

Quoted from him:

> I closed the issue for a specific reason and you have given no reasons to reopen it, so it shall stay closed.

This means he still doesn't believe my corrections and still insists that PaleMoon is an outdated Firefox derivative without being updated with security updates.

This guy is more straight forward, he clearly state if I want PaleMoon ported, I have to hire developers doing it for me, they will not do this: https://github.com/haikuports/haikuports/issues/5132#issuecomment-649539818

If you read the OP's issue more slowly, you will found that he want you to do the porting yourselves, they will only help by providing assistant on Haiku's specific bits. **He want you to do everything for them**. The same mindset as other Haiku people.

So, don't waste your time with them. Just close this issue and forget about Haiku. Even if someday they had to port a modern browser to fill the gap on Haiku since their Web+ is too primitive, they will port Firefox, or Firefox derivatives like IceCat, but not PaleMoon. They are not necessary bad people, this only show the fact that they don't treat you the same as Firefox or Chromium but just a group of people maintaining an outdated codebase. This mindset is common, you could found it everywhere. So, don't blame them. If someday they are serious about cooperating with you to port PaleMoon to Haiku, please don't ignore them. Bye.

**Comment by mattatobin** [comment]
A shame. Oh well, maybe one day.

**Comment by hoper-a11y** [comment]
I have asked them to remove my account on their forum. If they actually do it then many of the links above would be no longer valid. But I think it's no longer matter, isn't it?

**Comment by mattatobin** [comment]
Would be nice to preserve that though.

**Comment by wolfbeast** [comment]
> And this guy clearly express his dislike for you because you don't support BLM

What I _personally_ support or don't support is completely irrelevant. As explained the whole point is that I don't want everyone supporting Pale Moon to automatically support BLM and other political activists; that should be up to everyone individually.
As a project, Pale Moon neither supports nor doesn't support it. It's really not that complicated, but I guess it might be beyond people who think strictly in binary about everything.

As Tobin said: maybe one day -- it's clear there isnt enough concrete support in the haiku community yet to lead to actual work being done, so perpetually on hold and not considering an open issue until that changes.

**Comment by hoper-a11y** [comment]
> Would be nice to preserve that though.

I'm too stupid. You are a community that being hatred much because of rank on reddit. I'm one of the example that used to believe the story on reddit. If all of the links vanish, haters could use it to prove your _dishonesty_  and will have many views and comments on reddit supporting them, the propaganda will spread and your project will be hurted by it.

I tried to fix my stupid action but I no longer have access to this account, so I tried to took screenshots or print the web pages into pdfs but both failed. The way their website designed defeat the pdf printing of both PaleMoon and Firefox. In no way I could capture the whole page.

I'm too sorry for my stupidity. If you can, took a full page pdf or sreenshot of these pages, just in case...

**Comment by wolfbeast** [comment]
It doesn't really matter. If people don't believe what is a matter of public discourse here on Github then I think they have bigger issues than whether to talk smack about Pale Moon/UXP or not.
