### ISSUE TITLE
Consider disabling session identifiers for privacy reasons.

### ISSUE THREAD

**Issue by Peacock365** [MoonchildProductions/UXP#1609]
See header. Please consider setting _security.ssl.disable_session_identifiers_ to _true_, it's a hidden setting and set to false so far. Session identifies last up to 24 hours and can be used for tracking purposes. No rendering issues are expected if this is set to true. Would like to hear your opinion, thanks for your attention.

**Comment by wolfbeast** [comment]
Nope, sorry. Won't fix for reasons already explained on the forum when this was brought up in the past.
If you want this, you can individually set it. The default will remain enabled because it strengthens security.

**Comment by Peacock365** [comment]
@wolfbeast 

So, I researched this a bit in the Pale Moon forums and this came up: https://forum.palemoon.org/viewtopic.php?t=20702

You made an argument there that disabling session identifiers might have an impact on performance; I don't have a fast Internet connection at all and have session identifiers disabled, and I really struggle to see a tangible difference between those being enabled / disabled. What's more, you also disable prefetching for privacy reasons, this hits performance as well (and potentially much harder than disabling session identifiers does), yet it's disabled by default in Pale Moon (for good reason, no doubt, I agree with you there).

You are the developer, it is your decision, and I know that you are not of the type who changes his mind all too easily, but you should really reconsider things here. Again, the performance loss is likely not noticeable to the human eye, the privacy loss is clearly there, though. It's no web compatibility issue either, because rendering is not impacted.

You are usually very good at finding a compromise between privacy / performance / web compatibility, and I respect you for it big time, but in this particular case you are on the wrong side of the equation, I fear.

**Comment by wolfbeast** [comment]
Session identifiers not only impact performance, they also strengthen security (hijacking is complicated by them, because known-good and predetermined attributes of the SSL/TLS connection are used without being on the wire). Sessions are also bound to hosts, and can't be re-used for tracking across domains. The performance impact is not negligible. Having to re-negotiate SSL/TLS on every connection is a long handshake that especially on high-latency networks will severely impact the browsing experience. So, the default is enabled, but you can disable it yourself if you are worried about it and want to trade in performance and a bit of connection security for potential privacy.

By the way, that pref controls both session IDs and session tickets.

https://forum.palemoon.org/viewtopic.php?t=20702#p154898 still applies.

**Comment by Peacock365** [comment]
I see, thank you for the explanation. I understand now why this issue is resolved wontfix, since the change might potentially impact security. I have opened up another issue, which hopefully helps you in cleaning up about:config, I leave this to your expertise. Always trying to help here.
