### ISSUE TITLE
Use Intrinsic Aspect Ratio for Images

### ISSUE THREAD

**Issue by RealityRipple** [MoonchildProductions/UXP#1620]
Intrinsic Aspect Ratio support:

> If img's width and height attribute values, when parsed using the rules for parsing dimension values, are both not an error, not a percentage, and non-zero, then use the ratio resulting from dividing the width attribute value by the height attribute value.

These changes allow websites to specify the dimensions of an image via the HTML `width` and `height` attributes as well as CSS-based sizes, resulting in a ratio-preserved scale frame for images before they've loaded, preventing website reflow on dynamically sized images (most often by setting one dimension to `auto`). This only applies to image frames at present. If the image is loaded, the ratio defers to the actual image dimensions. If the image is unable to load, cross-browser-compatibility is retained by collapsing the frame.

This code includes changes to pave the way for css aspect-ratio. If it goes too far, please let me know. Particularly, `layout/style/nsCSSPropList.h` and `nsRuleNode.cpp` are not part of the Firefox code at all. I don't know if they're necessary for the existing limited implementation, but it seemed like the safest path to add AspectRatio to them.
Additionally, if any or all of the tests are not required, they can be omitted from the final commit.

Ref: BZ [Bug 1547231](https://bugzilla.mozilla.org/show_bug.cgi?id=1547231), BZ [Bug 1559094](https://bugzilla.mozilla.org/show_bug.cgi?id=1559094), BZ [Bug 1633434](https://bugzilla.mozilla.org/show_bug.cgi?id=1633434), BZ [Bug 1565690](https://bugzilla.mozilla.org/show_bug.cgi?id=1565690), and BZ [Bug 1602047](https://bugzilla.mozilla.org/show_bug.cgi?id=1602047)
Also possibly eventually, BZ [Bug 1621333](https://bugzilla.mozilla.org/show_bug.cgi?id=1621333)

Resolved in [PR 1613](https://github.com/MoonchildProductions/UXP/pull/1613)

**Comment by RealityRipple** [comment]
Working with the main testcase right now, running into some functionality differences I need to narrow down.

The script sets img css to `width:100%; max-width:100px; height:auto;` to test responsive sizing.

----

Three boxes are generated with JS to test pre-load sizes, all of which load `images/blue.png`:
1. `width=250` `height=100` 
    - This one works fine and results in `100` and `40` for the computed style.
2. `setAttribute('width', '0.8')` `setAttribute('height', '0.2')`
    - This results in a width of `100` and a height of `0`. Firefox apparently decided to support decimal width and height values which can be used to generate the ratio. They want this to result in a size of 100x25. If Pale Moon also supports decimal values, then I've done something wrong somewhere. Otherwise, this is going to be an expected difference, unless you want to add support for decimal value sizes, which... I'd vote no if my vote counted.
3. `setAttribute('width', '50%')` `setAttribute('height', '25%')`
    - which definitely fail to generate an aspect ratio and result in `100`x`0` on any browser.

Once these three boxes load, their sizes are as expected, plus or minus less than two hundredths of a pixel.

----

Five boxes are created via normal HTML:
1. `src=images/green.png`, no sizes set
    - `100`x`50` as expected.
2. `src=images/green.png`, `width=100` `height=125`
    - `100`x`50` as expected.
3. `src=""`, `width=100` `height=125`
    - `100`x`0` is the same as previous behavior. Collapse and keep the width, right?
4. `src=error.png`, `width=100` `height=125`
    - `100`x`125` is... not the way other browsers handle missing files. What exactly is Pale Moon's stance on image frames for broken images? If we're respecting set sizes, then I need to change the ratio code to allow `ShouldShowBrokenImageIcon`s to have an intrinsic size. And if so, Pale Moon's previous methodology let the `height: auto` CSS rule force the height of this img to `100` and... I don't know why. What is the right resulting size for this case?
5. `src=error.png` no sizes set
    - `100`x`100` is the same as previous behavior.

----

So, should anything be done about JS test 2? And what is our "right answer" for HTML test 4?

**Comment by wolfbeast** [comment]
Your description isn't exactly clear. Toss up the test files and we can have a look.

**Comment by RealityRipple** [comment]
[Pale Moon](https://github.com/RealityRipple/UXP/blob/AspectRatio/testing/web-platform/tests/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/img-aspect-ratio.html) | [Firefox](https://hg.mozilla.org/mozilla-central/annotate/tip/testing/web-platform/tests/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/img-aspect-ratio.html)

Note the differences between the expected values I've used and the expected values from Firefox:

Line 40 vs Line 39:
`- assert_ratio(img, 4);`
`+ assert_equals(getComputedStyle(img).height, "0px");`

Lines 55 through 57 vs Lines 54 & 55:
`- assert_equals(getComputedStyle(images[2]).height, "0px");`
`- assert_equals(getComputedStyle(images[3]).height, getComputedStyle(images[4]).height);`
`+ assert_equals(getComputedStyle(images[2]).height, "0px");`
`+ assert_equals(getComputedStyle(images[3]).height, "125px");`
`+ assert_equals(getComputedStyle(images[4]).height, "100px");`

**Comment by wolfbeast** [comment]
I'm sorry, do you have a -standalone- test file that I can look at? Because I can't do anything with stuff that relies on the test harness.

**Comment by RealityRipple** [comment]
Oh, yeah, no problem. https://uploads.realityripple.com/Projects/artest/

**Comment by wolfbeast** [comment]
For the record, here's the results on 28.12 -- looks like you're only changing something in the error situation.
![Image1](https://user-images.githubusercontent.com/3359132/89377026-4289a200-d6f1-11ea-8dd6-2ad204e9b615.jpg)

But I have a better understanding of what you're doing now and I think you're worrying about corner cases you shouldn't.
So what's happening here is you are having both CSS and image attributes fighting for dominance.
It would have helped if you didn't change the test to "fit our results" because I'm still unclear now as to what firefox/chrome think is correct and what we are doing now with and without your patch. Can you please change the rest expectations back in the live test so I can see what FF/Chrome thinks we are failing?

My feedback:
- Erroring images with a specified width and height attribute should **always** render the image frame. That is traditional behaviour that has always been the case and should **not** be collapsed to "just the icon" like Google does; that is just wrong.
- The image frame size for broken images in is, IMO, logically more correct after the patch:
A broken image has no width/height info, therefore no aspect ratio. Because the test foolishly sets both the attribute width and css max width to the same value, I can't see what's happening here with your patch, but assuming the attribs take over here. Our release version results in the css max-width squared, ignoring the attributes on the image; with your patch it seems to give precedence to the image attributes, which I think is more logical in this situation: non-existing image = css results in N/A metrics (100% of ? is still ?) and falls back to the absolute attributes of 100x125 on the image.
- w/h 0.8/0.2 -- The spec is absolutely clear that these values must be valid, non-negative integers, that is, they can't be fractions[1]. So what we do is correct to the HTML spec. What FF/Chrome does is not and absolutely a bug.

[1] The width and height attributes on img, iframe, embed, object, video, and, when their type attribute is in the Image Button state, input elements may be specified to give the dimensions of the visual content of the element (the width and height respectively, relative to the nominal direction of the output medium), in CSS pixels. The attributes, if specified, must have values that are valid non-negative integers.
https://www.w3.org/TR/2012/WD-html5-20121025/dimension-attributes.html

**Comment by RealityRipple** [comment]
I added a second file with links between them a few minutes ago. Kinda felt like you'd ask about it.
And yeah, I agree with all your conclusions.
