### ISSUE TITLE
libvpx and SQLite updates

### ISSUE THREAD

**Issue by smnthermes** [MoonchildProductions/UXP#1631]
Please, update to the latest stable releases of libvpx (1.8.2) and SQLite (3.33.0).

**Comment by mattatobin** [comment]
Why?

**Comment by smnthermes** [comment]
Both libraries have a relatively high attack surface, therefore they should be kept up-to-date.

**Comment by mattatobin** [comment]
Libvoc likely won't be updated very soon. There is busting api considerstions. Either shouldn't be very if at all vulnerable.

**Comment by wolfbeast** [comment]
There have been no security issues between our currently used release and the latest release of the SQLite library. In fact, most of the changes in the library related to code bugs are N/A since we explicitly control all SQL statements sent to the library and it is not exposed to content.

That being said SQLite is easily updated so I'll probably shove that in one of these days.

**Comment by mattatobin** [comment]
Also we specifically dictate what symbols are exposed to internal code.
