### ISSUE TITLE
Implement CSS flow-root keyword

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1641]
What it says on the tin. This was added to m-c shortly after our fork point so should be easy enough to port across lacking the incessant refactoring Mozilla has been doing. It's not in use on a lot of websites so low priority, but "nice to have" to complement our CSS3 support.
References: BZ [1322191](https://bugzilla.mozilla.org/show_bug.cgi?id=1322191) and follow-up [1325970](https://bugzilla.mozilla.org/show_bug.cgi?id=1325970)

**Comment by athenian200** [comment]
I actually tried porting this over after I saw the forum thread. 

For some reason, this implementation doesn't appear to work, even though we haven't really changed the surrounding code since our fork point. It just crashes the browser. It compiles fine and the code looks sane, it just doesn't work for some reason. I thought maybe I made a typo somewhere so I tried resetting and trying to copy everything in again. Same result. 

I was planning to look into this so I could learn more about the layout engine with an easier bug closer to our fork point, but I have a feeling either someone else will figure it out quickly or it will take me an embarrassingly long time.

**Comment by wolfbeast** [comment]
can you toss me your patches so I can see what this crash is?

**Comment by athenian200** [comment]
Actually, it turns out the patch does work without additional tweaking. I needed to clobber and I mistakenly thought I already had. I can't quite tell if it does what it's meant to, though. I can tell that this test looks better than before:

http://wpt.live/css/css-display/display-flow-root-001.html

And on my implementation, it now matches this reference:

http://wpt.live/css/css-display/display-flow-root-001-ref.html

So I think the mission is accomplished. I really need to start learning to check if something that's not working was broken _before_ I started working though.

**Comment by wolfbeast** [comment]
From your PR:

>  It really seems to add/create a new way to access existing code relating to block formatting and floating elements

It's not like creating these layout structures is new, it just needs to wrap it in an additional block context, is all. It being straightforward and close to our fork point would make it comparatively easy, indeed.

**Comment by wolfbeast** [comment]
Verified fixed
