### ISSUE TITLE
Implement percentage for CSS opacity keywords

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1647]
We currently support the standard float values for various `opacity` CSS keywords, but the spec has been changed to also permit percentages.
We should add parsing of percentages for `opacity` keywords to translate/serialize to the corresponding float value when read (as a percentage of "1")

This would involve changing `nsCSSPropList.h` to use `VARIANT_HPN` instead of `VARIANT_HN`, and adding or changing serialization from percentage to float for it. I haven't exactly found where this serialization happens for Opacity, yet, so that will require some searching.

**Comment by athenian200** [comment]
Well, I've managed to get the style system to support opacity as a percentage without a problem. I just added support for that case into nsRuleNode.cpp and everything worked flawlessly from a visual perspective. Apparently we actually had support for this in some form a long time ago and it was simply removed.

The problem is that... well, as far as I can tell, if you change nsCSSPropList.h to VARIANT_HPN, the value _will_ serialize as a percentage, and if you don't change it, then percentages will be rejected as valid values right out of the gate. I could be wrong here, but the style system doesn't appear to support the concept of having a data type serialize as something different than what the user inputted, because there's a very rigid syntax in place designed to automate the adding of new elements and this violates the assumptions that framework makes. This can be changed of course, the hard part would be changing this for opacity without also changing it for the whole style system.

While you can easily convert between data type representations immediately after serialization, tests will fail because it technically serialized as a percentage even though the style system is actually converting the percentage to a float before anything happens internally.

**Comment by wolfbeast** [comment]
Hmm... but the same thing happens with using percentages as alpha in `rgba()` -- that _does_ serialize to the float equivalent while the user has put in a percent value. So where is that conversion done then?

Or maybe the tests just need to be changed, or what do you mean, exactly?

**Comment by athenian200** [comment]
> Hmm... but the same thing happens with using percentages as alpha in `rgba()` -- that _does_ serialize to the float equivalent while the user has put in a percent value. So where is that conversion done then?
> 

Yeah, that's why this took me so long to figure out. There's a completely separate implementation of opacity for rgba() that already supports percentages. It serializes as an <alpha-value> instead of a <number> to begin with. I believe the serialization (or at least the conversion) for the rgba() function is done in nsComputedDOMStyle.cpp. It does have its own keyword, VARIENT_COLOR, there's stuff like eCSSUnit_PercentageRGBAColor, and a ton of specialized helper functions that allow it to serialize in a totally different way from _normal_ percentages or floats. If you look at all the color-based CSS keywords, you'll notice they're marked VARIANT_HC rather than VARIANT_HN or VARIANT_HPN. In other words, they can do that in color because there's a ton of plumbing treating color and its alpha values as a special ParseVariant case with its own units. That is why I'm thinking I would need to implement something along the lines of VARIANT_OPACITY and eCSSUnit_Opacity to be able to make this work.

> Or maybe the tests just need to be changed, or what do you mean, exactly?
> 

What I mean is that the code I wrote passes all the "computed" tests:

https://wpt.live/css/css-color/parsing/opacity-computed.html
https://wpt.live/css/filter-effects/parsing/flood-opacity-computed.svg
https://wpt.live/svg/painting/parsing/fill-opacity-computed.svg
https://wpt.live/svg/painting/parsing/stroke-opacity-computed.svg
https://wpt.live/svg/pservers/parsing/stop-opacity-computed.svg

But fails the "valid" tests, saying it doesn't serialize in a canonical way and is actually a percentage:

https://wpt.live/css/css-color/parsing/opacity-valid.html
https://wpt.live/css/filter-effects/parsing/flood-opacity-valid.svg
https://wpt.live/svg/painting/parsing/fill-opacity-valid.svg
https://wpt.live/svg/painting/parsing/stroke-opacity-valid.svg
https://wpt.live/svg/pservers/parsing/stop-opacity-valid.svg

[https://i.imgur.com/ZG0QtXf.png](url)

> Do note that my suggestion to change the serialization was just based on assumptions reading surrounding code and I may be wrong that it needs that. Ultimately all I care about is that it works.

Well, the spec tests do actually test for a specific serialization, and that serialization is rather weird. It specifically says that you have to let the user enter a percentage but serialize it as a float. I'm not sure if there are any ill effects as a result of this, or if they did this to make it emphatically clear that they're _not_ bringing back the old version of percentage opacity described in this bug that everyone hated:

https://bugzilla.mozilla.org/show_bug.cgi?id=195883

**Comment by wolfbeast** [comment]
I don't really understand then. So we had percentage opacity, people hated it, it got removed, and now they want it back after all despite people hating it, and somehow twist it into being more complicated?

Also, serializing percentage to float should be easy in this case as it's just divide by hundred as opacity 100% is always `1.0`. A helper function to that effect would be a one-liner. So what's the problem? Why would it affect other opacity values?

**Comment by wolfbeast** [comment]
I'm actually fine with adding a separate type if it needs to be handled "differently than usual" with the conversion. `VARIANT_OPACITY` would be clearest, handling the serialization of both number and percent to a float. Think you can make that happen? I really don't care about all the shortcuts Mozilla has made; if the spec no longer treats a percent as a percent in this case it can't be generalized.

**Comment by athenian200** [comment]
I think I've gotten it working. While was looking into this more, I discovered something... interesting in `nsCSSScanner.cpp` in the two places where it deals with `eCSSToken_Percentage`:

`case eCSSToken_Percentage:
  aBuffer.AppendFloat(mNumber * 100.0f);
  aBuffer.Append(char16_t('%'));
  break;`

And:

'// Check for Dimension and Percentage tokens.
  if (c >= 0) {
    if (StartsIdent(c, Peek(1))) {
      if (GatherText(IS_IDCHAR, ident)) {
        type = eCSSToken_Dimension;
      }
    } else if (c == '%') {
      Advance();
      type = eCSSToken_Percentage;
      value = value / 100.0f;
      aToken.mIntegerValid = false;
}'

If I'm reading this correctly, it means that all percentages are ALREADY stored as floats internally for computation purposes, and for whatever reason they just get read back out as percentages. The code that reads them in divides them by 100.0f, and the code that pushes them to a buffer multiplies them by 100 and slaps a percentage sign on the end... in other words, the style system appears to have been setup to prevent exactly what I'm trying to do. It's almost like someone wanted to cover up the fact that percentages are stored as floats internally by using a separate type so it can make sure to throw a percentage back out to a buffer. That's why my final implementation never has to divide by 100 anywhere (I did try that initially while working on my first patch, and saw everything was 1/100th the size it should be before realizing this). 

So, I'm just creating a case where I take eCSSToken_Percentage and store it in eCSSUnit_Number (which works because they're both floats). It looks a bit silly because I'm going out of my way to take a percentage token and store it in the "wrong" container, but it now passes all tests.

**Comment by mattatobin** [comment]
Be sure to comment heavily on your changes to that effect.

**Comment by wolfbeast** [comment]
Tested and verified with https://jsfiddle.net/Moonchild/4hk6ucz7/4/ that all works as-intended.

**Comment by wolfbeast** [comment]
@athenian200 potential regression in parsing flex as a result of this, see https://forum.palemoon.org/viewtopic.php?f=70&t=25308&p=200547#p200547

**Comment by wolfbeast** [comment]
Follow-up uplifted in [e50094ab0]
