### ISSUE TITLE
Encrypted Media Extensions is not optional

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#26]
- [x] No-op `EME` so that it is non-functional when not --enable-eme
- [ ] Isolate `EME` from `GMP` and DOM Media

----
Blocks #35 - Make Gecko Media Plugins optional when not building EME or WebRTC

**Comment by wolfbeast** [comment]
As discussed this can't be done this way and we're changing our approach to do it the same was as in Möbius. I'll take this from here.

**Comment by mattatobin** [comment]
Can you make EME an enable bool please when you send it back to ac configure?

**Comment by wolfbeast** [comment]
Commit 507827c207dda138f22ce47ca988708986d17006  makes it an enable bool.
`--enable-eme` or `--enable-eme=adobe/widevine` enables it.
`--disable-eme` or not specified in `.mozconfig` disables it (`MOZ_EME` undefined)

**Comment by wolfbeast** [comment]
Considering Pale Moon 28 disables EME at build time and Basilisk enables EME and both work fine with the proper APIs enabled/disabled, I'm closing this as solved.
Any further isolation of the EME code that's still desired should be a follow-up as this is no longer a beta blocker.

**Comment by g4jc** [comment]
Note: If --enable-tests is set, it conflicts with --disable-eme since this bit of eme gtest code is not ifdefined out, causing a build failure. I am not entirely certain why it was reverted, but the code @mattatobin had originally committed on this particular file fixes it:
https://github.com/MoonchildProductions/UXP/commit/0cdd647abc53f7db3aa16f67bf0b2f8f3825db61#diff-c430106b56df118743a25bec7a6a03df

**Comment by mattatobin** [comment]
Mozilla tests save layout reftests and possibly js spec tests are slated for removal. So it doesn't matter.

I beleve you were already told that already so not sure why this is relevant.

**Comment by mattatobin** [comment]
We can use this a very loose (and potentially incomplete guide).

----

https://github.com/Feodor2/Mypal/commit/6bd59d4de4335b1c01a9a16e6a872be06926b676

**Comment by wolfbeast** [comment]
I've been working on this for a bit, seems we're having a small issue preventing us from isolating `EME` from `GMP` since it got intertwined with a generic module in [Bug 1290830](https://bugzilla.mozilla.org/show_bug.cgi?id=1290830). Thankfully, that was only added to cater to something we're no longer supporting anyway (Fennec) so that can be backed out.
It's not going to be a clean separated set of commits because I've already put in a lot of work otherwise and will have to just slide this revert into my main patch.

**Comment by wolfbeast** [comment]
@trav90 I'm going to hold off on this for the moment because I have the distinct feeling I'm going to muck up your progress otherwise, which is the last thing I want to do at this moment. Please let me know if you are actually building on top of the changes in 1290830 which genericified GMP specific types to `mozilla::dom::*` types (e.g. `mozilla::dom::MediaKeyMessageType`) or if that is reversible. If it's too entwined then we'll have to consider EME always being built in the platform a necessary evil at this point.

**Comment by mattatobin** [comment]
I for tge record I am fine with the trifecta of WebRTC-GMP-EME if that is the way it must be for a good long while if not forever. It would just be nice if it wasn't.

**Comment by trav90** [comment]
@wolfbeast to the best of my knowledge it is reversible. I do not recall anything that would require this (though it is possible something may have slipped my mind).
