### ISSUE TITLE
[BASILISK] Vertical stripes in tabs at high DPI display resolutions

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/UXP#268]
<div align="justify">At a number of higher DPI display resolutions on Win7x64, particularly at the two native system settings of 120 and 144 DPI (and also after changing value of the pref <tt>layout.css.devPixelsPerPx</tt> to e.g. <tt>1.3</tt> or <tt>1.5</tt> while at the default 96 DPI), tabs in Basilisk become noticeably afflicted with vertical stripes, with their density and placement depending on the amount of opened tabs, on the width of the browser's window, as well as on the preferred DPI value. The stripes can be seen if using the classic Windows theme on the system as well.

Below is a couple of examples for one and the same window.</div>

<div align="center"><h4><tt>Medium - 125%</tt> (120 DPI) display setting:</h4>

<img src="https://user-images.githubusercontent.com/26753987/39250862-909133a0-48aa-11e8-9310-577940978d5c.gif" alt="{image}">

<h4><tt>Larger - 150%</tt> (144 DPI) display setting:</h4>

<img src="https://user-images.githubusercontent.com/26753987/39250904-acf871fc-48aa-11e8-8557-925f49d15206.gif" alt="{image}"></div>

<div align="justify">It appears that in both Basilisks the issue was caused by rounding subpixel border widths to nearest integer instead of nearest-below integer:</div>

https://github.com/MoonchildProductions/UXP/blob/6662cdbeb39d9bad15efedd37cf97f5e7adff853/layout/style/nsStyleStruct.h#L1200-L1203

**Comment by wolfbeast** [comment]
Just needs a theme adjustment.

**Comment by wolfbeast** [comment]
The issue was caused by bad design of the "fuel-efficient tabs" on Australis. The way these tabs is constructed is a bad hack (surprise surprise) that has the rounded start/end parts be positioned just flush against the center part (the actual tab) with as-minimal background. Positioning of these parts is from the outside in (margins) so if there are rounding discrepancies based on width of the tab/width of the curve based on DPI, it could create a 1px visual gap.

Creating a 1 px overlap (shrinking the wide transparent border by 1 px) fixed this.

**Comment by Lorienna** [comment]
Thank you, MC. :+1:
