### ISSUE TITLE
[minor fix] After update on NSS 3.35 - fix a test

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#29]
FIPS can no longer be toggled:
[bug 1419721](https://bugzilla.mozilla.org/show_bug.cgi?id=1419721) - a part of the [upgrade NSS 3.35](https://github.com/MoonchildProductions/UXP/issues/28)

Some test/personal branch/commit (with the expected result):
https://github.com/janekptacijarabaci/UXP/commit/0703730fe6a1bed7356dec7a65bf2f67cebdabee
(also: https://hg.mozilla.org/mozilla-central/rev/45e4387bc585)

An example (for Scratchpad):
``` javascript
function ok(a, b) {
  if (a) {
    alert(b);
  }
}

var gModuleDB = Components.classes["@mozilla.org/security/pkcs11moduledb;1"]
    .getService(Components.interfaces.nsIPKCS11ModuleDB);
ok(!gModuleDB.canToggleFIPS, "It should NOT be possible to toggle FIPS");
```

Expected results:
Not shows: `It should NOT be possible to toggle FIPS`

**Comment by janekptacijarabaci** [comment]
canToggleFIPS is actually turned on on Basilisk. I'm sorry.

**Comment by wolfbeast** [comment]
I traced through the code to see where exactly this decision is made, and it's made at build time with the define `NSS_FIPS_DISABLED` -- which is never set in our build system, ergo never disabled in NSS. Your test is incorrect because it SHOULD be possible to toggle FIPS compliance mode and install/remove the FIPS module.
