### ISSUE TITLE
Backport FF58/TBB Canvas Protection

### ISSUE THREAD

**Issue by gitbugged** [MoonchildProductions/UXP#30]
These patches prevent Canvas Fingerprinting for added privacy/security.
https://bugzilla.mozilla.org/show_bug.cgi?id=967895

Further info: https://thehackernews.com/2017/10/canvas-browser-fingerprint-blocker.html

**Comment by mattatobin** [comment]
We have the ability to poison canvas data.. Wouldn't out right blocking it with a doorhanger no one will actually read or remember how to undo cause all kinds of problems like busted sites and endless "Why isn't this site working"?

**Comment by wolfbeast** [comment]
Wontfix. Canvas fingerprinting mitigation is already present in a NON-breaking way.

**Comment by joey04** [comment]
This is a meta comment for tag usage on feature request issues like this one.

Could you add a new "Status: Declined" tag? The "won't fix" label implies it's a bug that one has to live with or workaround, whereas "declined" is better for feature requests, like this issue.

**Comment by mattatobin** [comment]
Is that better? As in it isn't a bug at all.. It is invalid because we have our own canvas mitigation technique that is non-breaking.

**Comment by joey04** [comment]
I don't think it's better, tbh. "Invalid" implies the issue is fundamentally invalide, e.g. PEBCAK or similar. But this issue is not invalid; it's a feature request that is declined. That should be its own, distinct status in the tracker.

**Comment by mattatobin** [comment]
Well, you don't get to make those decisions.

`RESOLVED INVALID`

**Comment by wolfbeast** [comment]
"Invalid": It's an invalid issue, meaning "it's a non-issue", "doesn't apply to our code"
"Wontfix": Any reason why this issue is applicable but will not be addressed, including "declined", "impossible", "undesired", "workarounds are fine".

This feature request fits both because in this exceptional case we already have different mitigation in place (making this N/A), but in general declined feature requests would be `wontfix` which is why I labeled it as such.
