### ISSUE TITLE
Removal of sandboxing constructs.

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#302]

**Comment by wolfbeast** [comment]
GMP uses the sandbox. Wouldn't this be a security issue for DRM/EME by having the CDMs run unsandboxed?

**Comment by mattatobin** [comment]
This is for content sandbox the thing we don't use.

**Comment by wolfbeast** [comment]
`MOZ_SANDBOX` is the master switch for the sandboxing machinery. This drives sandboxes for content `MOZ_CONTENT_SANDBOX` and for GMP `MOZ_GMP_SANDBOX`.
`MOZ_CONTENT_SANDBOX` is e10s and can definitely go.

How the GMP sandboxing fits together needs research. 

Hopefully it is optional (it is only used on Linux and Mac) in which case `MOZ_SANDBOX` can go in its entirety, but otherwise the machinery itself needs to either be pulled apart to only keep those parts needed for DRM-capable applications, which would be similar to using plugins OOP. Alternatively in that case diverted to NPAPI constructs to segment out CDMs.

**Comment by wolfbeast** [comment]
@trav90 can you tell me if you've been building Linux with sandboxing explicitly enabled or not?
(either `.mozconfig` or `MOZ_SANDBOX`)
Since Tobin flipped the default for this in Feb and I was still assuming we would build this by default, it may save a lot of work for me if you can confirm it's been off (since DRM works in Linux)

**Comment by trav90** [comment]
No I have not been explicitly enabling sandboxing at all.

**Comment by wolfbeast** [comment]
Awesome. Means this can all just go, and saves me a ton of research.

**Comment by mattatobin** [comment]
http://xref.palemoon.org/uxp-trunk/search?string=MOZ_(.*)SANDBOX&regexp=1&case=on

**Comment by wolfbeast** [comment]
Thanks but I know how to use xref.

**Comment by wolfbeast** [comment]
Situation after removal will be: EME/CDM will be loaded the same way as NPAPI plugins. 

- On windows, they will reside in the restricted plugin-container process. 
- On Linux, system-provided process sandboxing will be used, with an extra check that if the system does NOT provide this, EME CDMs will never be allowed to load (for security reasons), unlike normal plug-ins. On those systems, EME will not be available.

**Comment by mattatobin** [comment]
I don't think the linux situation will be a huge issue due to the fact most distros would provide the facilities coupled with the general objection of drm from most linux users.

**Comment by wolfbeast** [comment]
As far as I know users will be notified; at least an error message is specifically thrown in that case from what I understood of the code.
