### ISSUE TITLE
Full-screen nav bar doesn't hide when focused during switching.

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#336]
Separated from [#270](https://github.com/MoonchildProductions/UXP/issues/270#issuecomment-385694204), since it's not a release blocker:

> The CSS animation [..] isn't being triggered at all for blank (or about:logo) pages. When that happens even if you switch to a tab with content it doesn't ever trigger the hiding..

This issue exists in both Basilisk and Pale Moon (and Firefox Nightly 20180506).

**Comment by mattatobin** [comment]
For some reason you can use escape to exit normal fullscreen on Windows which is incorrect behavior. Linux does not seem affected though.

**Comment by JustOff** [comment]
> you can use escape to exit normal fullscreen on Windows

I can't reproduce this, could someone else check it, please?

**Comment by wolfbeast** [comment]
I can't reproduce it in Basilisk-release. I haven't built any UXP PM lately so couldn't check that.

**Comment by janekptacijarabaci** [comment]
> could you please check if UXP PM exits from browser full-screen (F11) when you press Esc?

No, this does not work for me (only the F12 key).

**Comment by JustOff** [comment]
@janekptacijarabaci, thanks.

@mattatobin, could you please double-check or provide more info about your windows version or perhaps share the UXP PM binaries  if the issue is still reproducible?

**Comment by mattatobin** [comment]
Yeah, I will check it out.

**Comment by mattatobin** [comment]
All seems as it should be now.. Sorry for the confusion.

**Comment by khronosschoty** [comment]
I am able to reproduce this issue. When full screen is called from a bank tab the navigation tool bar stays open.

**Comment by wolfbeast** [comment]
I think this is by design, actually. Any "Blank" URL (`about:blank`, `about:logopage`, `about:newtab`) will keep the focus on the address bar and will not focus the content. As such the navigation toolbar will stay visible until you navigate elsewhere.

**Comment by wolfbeast** [comment]
Ah, but I see the bug now. While it _should_ hide when the toolbar loses focus (by clicking content or navigating away), it doesn't. 
I've filed an [upstream bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1470665) for this as well.

**Comment by FranklinDM** [comment]
I can reproduce this also on other sites if you focus on the certain elements on the navigation bar (i.e. location bar); navigating to other tabs won't hide the navigation bar anymore. After a while of testing, I think I've found the solution to this problem.

Adding this check to `browser-fullscreen.js` after `line 55` does the trick:
```js
      // If it is not safe to collapse, add the mouse position tracker or
      // else it won't be possible to hide the navigation toolbox again
      if (!this._safeToCollapse(document.mozFullScreen)) {
        let rect = gBrowser.mPanelContainer.getBoundingClientRect();
        this._mouseTargetRect = {
          top: rect.top + 50,
          bottom: rect.bottom,
          left: rect.left,
          right: rect.right
        };
        MousePosTracker.addListener(this);
      }
```

**Comment by wolfbeast** [comment]
Awesome hunting, @FranklinDM :)

Could you make a PR of this for both?

**Comment by wolfbeast** [comment]
It doesn't look like this is completely solved; when hitting F6 (focus URL bar) + F11 (FS), then clicking the content, the navbar still doesn't hide (which would be the most common case, I think). Switching tabs re-enables the hiding.

**Comment by wolfbeast** [comment]
I'm going to try a different approach to see if I can get this fixed.

**Comment by wolfbeast** [comment]
My attempted approach[1] didn't work. It helps with this specific situation but causes other focus issues and unresponsiveness when trying to toggle. not entirely sure how to go forward myself with this so unassigning myself -- if anyone has another/better idea, feel free to try!

[1] Based loosely on https://bugzilla.mozilla.org/show_bug.cgi?id=1477525

**Comment by FranklinDM** [comment]
I'm testing an alternative fix - this involves using `mousemove` events instead of `MousePosTracker` and restores the `collapseCallback` function similar to the previous fullscreen implementation.

**Comment by wolfbeast** [comment]
I'm not sure if mousemove is a good idea because it'll rapid-fire events, but reinstating the callback (and fixing the unresponsiveness of F6 as well as esc for DOM fullscreen) is definitely a better solution. Would there be a better solution using click and/or keypress to check the collapsibility?

> Actually, it's enough to raise the mouse cursor to the top of the screen and then move it down.

This is unintuitive behavior and completely unexpected. It's expected that a click on the content or any focus shift to content will hide the nav bar which doesn't happen if the mouse hasn't been in the navbar area.

> it breaks once again add-ons like TMP/TST, etc.

I'm sorry but we can't hold back fixes to the UI because it's breaking extensions. What should be done is, once a complete fix lands on unstable, to notify the extension devs and ask them to make the necessary changes to their code to deal with it.

**Comment by JustOff** [comment]
My primary concern  is the potential loss of better usability provided by MousePosTracker (top: rect.top + 50). Maybe we can try to combine this method with click and/or keypress check to address the remaining F6 flaw?

**Comment by FranklinDM** [comment]
I've tried using both in my first try with this and it introduced some inconsistency:
* If URL/search bar is focused and pressed F11 to enter full screen mode:
  - The navigation toolbar would collapse just fine.
* Mouse is on content while focused on the URL/search bar and in full screen mode:
  - The issue is present again: you have to hover over the navigation toolbar to hide it.
  - Using the `mousemove` listener here would conflict with the MousePosTracker.
Based on these, I've thought and decided if we could simply use the `mousemove` event everywhere as used in the previous full screen implementation.

It is possible to use a click check to hide the navigation toolbar but for the F6 - it is already being checked by `_keyToggleCallback` but something seems to be blocking it and is somehow solved by using `mousemove` everywhere.
