### ISSUE TITLE
Firefox add-ons with strictCompatibility can't be installed in Pale Moon, regardless of the correct range.

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#391]
As reported [here](https://forum.palemoon.org/viewtopic.php?f=46&t=19244#p142082) on forum, [IDM](https://getidmcc.com/) can't be installed in PM28, while there is no such problem in PM27.

This add-on has the following in the `install.rdf`:
```
<em:strictCompatibility>true</em:strictCompatibility>
...
<!-- Firefox -->
<em:targetApplication>
  <Description>
    <em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
    <em:minVersion>27.0a1</em:minVersion>
    <em:maxVersion>52.*</em:maxVersion>
  </Description>
</em:targetApplication>
```
Installation in PM28 is possible only if we disable `strictCompatibility` or set `maxVersion` to `*`.

**Comment by wolfbeast** [comment]
This is as expected.
Pale Moon is not Firefox. Pale Moon requires a Pale Moon `targetApplication` block.

**Comment by mattatobin** [comment]
I know why this is. The Dual-GUID system which allows installation of Firefox-only targeted extensions is set to fake now fake Firefox 56.9 thus strict compatibility mode sees 27.0a1 to 52.* as NOT being in that range.

Remember that strict compatibility disables the compatibility-by-default hack Mozilla put in place because of rabid release. Strict Compatibility is literally the original and TRUE compatibility checking criteria.

@wolfbeast is incorrect in that Pale Moon 28 absolutely accepts Firefox-only extensions. As stated, this has been expanded to pretty much cover the entire spectrum of Firefox extension version ranges but within those rules, strict compatibility is still obeyed. So it is expected just not for the reasons one would think.

As an aside, `27.0a1` is a version that never existed. An acceptable solution is to remove strict compatibility from install.rdf. A better solution is to make this extension a Pale Moon extensions. The WORST solution regardless if it works or not.. Is to set maxVersion to `*`.

RESOLVED WONTFIX

**Comment by wolfbeast** [comment]
You're correct. I was wrong. Sorry for the noise.

**Comment by JustOff** [comment]
@mattatobin, thanks for the detailed explanation.
