### ISSUE TITLE
Tracking protection blocklists not displayed in Basilisk preferences

### ISSUE THREAD

**Issue by Ascrod** [MoonchildProductions/UXP#425]
When Basilisk is built with safe browsing disabled, several constants in [blocklists.js](https://github.com/MoonchildProductions/UXP/blob/271c7b598d2daa42a8cc25ca72ecb538953bcfd8/browser/components/preferences/blocklists.js#L9) are ifdef'd out but are still used in the code. Thus, when the user goes to change what blocklist they're using for tracking protection (Preferences > Privacy > Tracking > Change Block List), the list of available block lists fails to load.

**Comment by wolfbeast** [comment]
Looks like tracking protection isn't working when safebrowsing isn't built, even with this restored -- Some preferences should be filled with values which they aren't, so that needs to be un-ifdefed as well.

**Comment by wolfbeast** [comment]
It doesn't look like we can use disconnect tracking protection at all unless we build safebrowsing, since it combines Google SB and Mozilla's custom lists. The original commit was OK, but additionally we need to remove the tracking protection controls from the UI if safebrowsing isn't built.

**Comment by JustOff** [comment]
It seems we cannot simply remove the tracking protection controls from the UI if safebrowsing isn't built, because they provide the only way to control DNT in private windows. I propose just remove the blocklist access button and assume the tracking protection in Basilisk without safebrowsing is the same as DNT.

**Comment by wolfbeast** [comment]
We can't do that, because the DNT flag is not tracking protection in any way, shape or form. We should not misinform people about preferences.

**Comment by wolfbeast** [comment]
How about:
```
#ifdef MOZ_SAFEBROWSING
  {{ current controls}}
#else
  {{ DNT-specific checkbox only with its own string }}
#endif

**Comment by JustOff** [comment]
It's easy to add a three-state radio checkbox for DNT (send always;only in private mode;never) and update `privacy.donottrackheader.enabled` and `privacy.trackingprotection.pbmode.enabled` accordingly (see [bug #1258033](https://bugzilla.mozilla.org/show_bug.cgi?id=1258033): DNT is added when `privacy.donottrackheader.enabled` is true or tracking protection is enabled). 

The problem is that I can't figure out **what exactly tracking protection do if safebrowsing isn't built**, so I'm not sure we can safely change its state just to control DNT and do not mislead users, because, as you rightly noted above, "DNT flag is not tracking protection in any way".

**Comment by wolfbeast** [comment]
If safebrowsing isn't built, then tracking protection is (should be!) always off (since it can't be used without it) and as such you don't have control over "only sending in private browsing mode". It's either off or on depending on the state of `privacy.donottrackheader.enabled`

**Comment by JustOff** [comment]
> If safebrowsing isn't built, then tracking protection is (should be!) always off

Well, then [we need to disable](http://xref.palemoon.org/uxp-trunk/search?string=privacy.trackingprotection.pbmode.enabled&find=all.js&tree=uxp-trunk) `privacy.trackingprotection.pbmode.enabled` if**n**def `MOZ_SAFEBROWSING`.

> [DNT is] either off or on depending on the state of privacy.donottrackheader.enabled

This sounds like a plan, I take it.

**Comment by wolfbeast** [comment]
Just flipping the pref or making it hidden in all.js won't actually remove it, and people knowing about it can still flip it on -- but I guess that would be their own risk of undefined configuration, I guess ;)

**Comment by JustOff** [comment]
Perhaps we should completely remove tracking protection if safebrowsing isn't built, not just from the UI, but this is a separate task.

**Comment by wolfbeast** [comment]
Indeed, that could be a follow-up but shouldn't be a release blocker (while this is).
