### ISSUE TITLE
Windows Firewall Inbound rules creation

### ISSUE THREAD

**Issue by Gittyperson** [MoonchildProductions/UXP#462]
On every install/update, Pale Moon 28 (all alpha versions) creates two WF inbound rules (TCP and UDP), just as Firefox does. Are these required for any particular service?

(Windows 10 Pro x64)

**Comment by wolfbeast** [comment]
Some research suggests these were first created specifically for some screen casting functions.
"Add 'Send Video To Device' to the context menu for sending videos from desktop to a second screen"

Any SDP discovery or WiFi scanning initiated from the browser may also pop up a firewall dialog otherwise. Considering the browser should be trusted with inbound traffic anyway, adding these rules prevents unnecessary headaches for current and future functionality.

**Comment by wolfbeast** [comment]
I don't think there's anything to do here. These rules prevent unnecessary need for support/questions.

**Comment by Gittyperson** [comment]
Ok, I thought they might have been there for allowing Mozilla to "push" hidden services, extensions etc. to the user in the background. To be honest I've never required an inbound rule for a browser but as you say, they may be needed for some purposes.

**Comment by wolfbeast** [comment]
System extensions and experiments and other things Mozilla might download and install on Firefox without the user's consent is always done with a standard GET or XHR, initiated from within the browser, and never using inbound connections (that wouldn't work very well anyway).

Inbound rules may not be -required- per se, but what happens then is that certain features simply won't work, or they will pop up a Windows Firewall permission dialog that users generally don't know how to answer to, especially if it's something they might not expect.
