### ISSUE TITLE
Security Backports: mozbug 1453795 / 1437600

### ISSUE THREAD

**Issue by gitbugged** [MoonchildProductions/UXP#527]
Thought to suggest these security issues for possible cherry-picking.

https://hg.mozilla.org/mozilla-central/log?rev=1453795
> Entire codebase: Initialize member fields in classes/ structures [still in progress upstream]

https://hg.mozilla.org/mozilla-central/log?rev=1437600
> JS Core: Use mprotect to prevent mutations of inaccessible regions

**Comment by wolfbeast** [comment]
Since we are using a zeroing allocator (that Mozilla decided not to), obsessive initialization of member fields is not required. Everything is by default null/zero/empty/false and only those fields that need specific non-null values have to be initialized. I'm honestly surprised it took them 9 cycles to finally clean up and stop using potentially uninitialized memory.

As for the second bug, that is a big fat N/A -- it's a clear bug in the code shown in the diff, but it was one of the many rearchitecturing bugs that were introduced AFTER our fork point.

As an aside: Unfortunately Mozilla Security does not give me access to sec bugs unless they have been published in the release channel -- I'm not going to blindly cherry pick code changes, as you may understand. Context _is_ required beyond just a diff for most bugs (especially if they don't graft cleanly, which is almost always the case).
