### ISSUE TITLE
"Restart in Safe Mode…" while already in Safe Mode?

### ISSUE THREAD

**Issue by projectBoy** [MoonchildProductions/UXP#571]
This is a quite old issue and in my opinion, it's time to be fixed. 
These menu items not only seems funny while already in safe mode, it's very possible 
to confuse some users and also, they are completely useless now in safe mode, since 
their action just leads to an endless restart loop in safe mode. 

I have fixed this, the result applies in both app menu and file menu items, but i don't 
know how to submit code here. 

If you accept my suggestion, you can find my work in the link below. 
It is less than ten lines of changes in total in five files. 
In the zip file you will find the original and modified files to see the diferences by 
comparing them and a ready to use omni.ja file (browser) to test it directly. 
The files are from the latest version of Pale Moon 28. 

version 2 below

**Comment by SpockMan02** [comment]
To submit code changes, commit them with git, push to a branch on GitHub, and open a pull request.

**Comment by wolfbeast** [comment]
To submit code changes you can also just use the GitHub web interface.

1. Fork the repo
2. Make changes in the files through the web interface
3. Open a pull request against our repo

**Comment by projectBoy** [comment]
I am sorry but i don't know how to do it the right way. 
Maybe someone else to do it on behalf of me? 
I am new here and i have to find the time to explore github to see how it works. 
Maybe also, after you test my suggestion, you would like to make some change. 

Below is v2 of my suggestion, which is based in latest version of Pale Moon 28. 
There is also one change, without any difference in behavior. Just better practice 
in code syntax. 

[PMv28_files-v2.zip](https://www.dropbox.com/s/dqg9favwerprkl0/PMv28_files-v2.zip?dl=1)

**Comment by wolfbeast** [comment]
I'm sorry but I don't agree with this approach. You'd end up with multiple restart menu items doing the same thing; in addition, embedding the alternative label as a non-standard XUL element attribute is not the way things are normally done when strings should be changed. To avoid multiple menu items and string changes, one could much simpler disable the menu item instead, from an implementation-technical perspective.

However, implementation aside, I don't think this is a bug per se and shouldn't be "fixed", because disabling Safe Mode restart while in Safe Mode doesn't allow for the following situation:

1. User has a problem and restarts in Safe Mode, not using recovery prompt options and continuing in Safe Mode
2. In Safe Mode, user sees the potential problem and wants to use one of the recovery options to correct it
3. User wants to restart in Safe Mode again, this time to use one of the recovery options, without having to restart in normal mode first to make that menu option available again (which might cause data loss).

This is a common case scenario because "Safe Mode" in Pale Moon serves 2 purposes in one: either correct common errors (Recovery) or actually start the browser in its Safe Mode operation.

I suggest we make this a Wontfix.

**Comment by kn-yami** [comment]
> embedding the alternative label as a non-standard XUL element attribute is not the way things are normally done when strings should be changed

I must say that I was surprised when I saw that. Should not XUL parser abort if it encounters an unknown label?

Anyway, I agree that making this wontfix if probably the best approach.

-----
To @projectBoy: Next time I would suggest to edit browser source directly. Some of the files bundled with the packed browser are created from other files when the browser is being build (in this case `browser.inc` is preprocessed to `browser.js`). If you make the the changes to the source code you can then make a diff and show it to the developers. This would make reviewing your patches easier. For example my #577 would look like this: [normal-mode-patch.diff](https://gist.github.com/kn-yami/9deb00fb1f2e69e67d2a1cbddb6082de).

**Comment by SpockMan02** [comment]
Maybe there's a good way to explain in the Safe Mode menu that the browser is already running in Safe Mode, and give the user the options of restarting in Safe Mode again, or restarting normally. Obviously you can already do this, but they're in different places (File --> Restart... vs. Help --> Restart in Safe Mode...). With a little explanation, there's less ambiguity, and both options are still open.

**Comment by wolfbeast** [comment]
It's not possible to guide users through troubleshooting workflows within the browser without making it over-complicated, nor should we try to, or try to cater to all possible unguided user scenarios in what is an advanced diagnostic mode to troubleshoot issues.

If a user isn't comfortable enough with operating in safe mode without guidance, then they should get guidance in the form of instructions by a knowledgeable person or persons.

If you want to discuss this further, please take it to the forum and get a broader audience.
