### ISSUE TITLE
Extension buttons created using Add-on SDK do not keep their position when placed right before space, flexible space or separator

### ISSUE THREAD

**Issue by jg-github** [MoonchildProductions/UXP#574]
Description of the bug
-> In "Text" mode, when an addon adds a button that's moved to the MenuBar, and then Flexible Spaces are inserted to the left and right of the MenuBar, when the browser is closed and reopened, the right Flexible Space is to the left of the added button rather than the right. This "pushes" the added button to the right edge of the display.

Affected versions/features
-> The last couple of unstable versions (portable). I'm now using 28.0.01b (64-bit) (2018-06-25)
    
Steps to reproduce the bug
a) In "Text" mode, install an addon that adds a button to the Navigation Bar.
b) Move the new button to the MenuBar
c) Insert Flexible Spaces to the left and right of the MenuBar
d) Close and reopen the Browser

Expected result when performing the steps
-> All the items on the Menu Bar should be centered (i.e., there should be equally wide spaces to the left and right of the Menu Bar).

Actual result when performing the steps
a) The right Flexible Space is to the left of the added button rather than to the right. 
b) This "pushes" the added button to the right edge of the display.
c) There is a large horizontal space between the "original" Menu Bar buttons (File, Edit, View, History, Bookmarks, Tools, and Help) and the "added" button (in this case "Cookie Shield).

For my testing of the issue, I've just done the following 
a) I just downloaded "palemoon-unstable-latest.win64.portable".
b) I installed only one extension (Cookie Shield 0.4.0), which I know adds its own button to the Navigation Bar.
c) I moved the button to the Menu Bar.
d) I added Flexible Spaces to the left and right and restarted the browser.
e) When it reopened, the added button was all the way to the right, confirming the problem. 

A fuller discussion of the issue, including images, can be found at
https://forum.palemoon.org/viewtopic.php?f=63&t=19544&p=144555&sid=fa9365b5246efa64f9d4e17299337de2#p144555

**Comment by janekptacijarabaci** [comment]
I know the cause of the bug - I will look at it.

**Comment by jg-github** [comment]
OK. Thank you.

**Comment by mattatobin** [comment]
Can you elaborate @janekptacijarabaci ?

**Comment by janekptacijarabaci** [comment]
Positions UI buttons (SDK extensions) are stored in a preference
`extensions.sdk-button-location.toggle-button--[id button]`:
[toolkit/jetpack/sdk/ui/buttons.js#L18](https://github.com/MoonchildProductions/UXP/blob/PM28.0.0b2_Unstable/toolkit/jetpack/sdk/ui/buttons.js#L18)

But `nextItemId` (`id`s) for:
`toolbarseparator`(`separator`)
`toolbarspring`(`spring`)
`toolbarspacer`(`spacer`)
are generated dynamically:
[toolkit/content/widgets/toolbar.xml#L357](https://github.com/MoonchildProductions/UXP/blob/PM28.0.0b2_Unstable/toolkit/content/widgets/toolbar.xml#L357)

e.g. `spring15303666700623` after the browser start no longer exists because this `toolbarspring` has another id.
The button (for an appropriate extension) moves to the outer right - behind `currentset` nodes:
[toolkit/jetpack/sdk/ui/buttons.js#L54](https://github.com/MoonchildProductions/UXP/blob/PM28.0.0b2_Unstable/toolkit/jetpack/sdk/ui/buttons.js#L54)
because `getElementById(id[i])` -> `getElementById("spring")` - and this id does not exist:
[toolkit/jetpack/sdk/ui/buttons.js#L62
](https://github.com/MoonchildProductions/UXP/blob/PM28.0.0b2_Unstable/toolkit/jetpack/sdk/ui/buttons.js#L62)

The following fix:
[_testBranch_...](https://github.com/janekptacijarabaci/UXP/tree/_testBranch_pm_sdk_buttons_toolbars_custom_dynamically-id_1)
changes the saved `id`
from (e.g.): 
`spring15303666700623`
to:
`spring[1]`
where `1` means the order of springs (`spring[0]`, `spring[1]`, `spring[2]`...) - as well as for `separator`s and `space`s - in this toolbar.

But it's test branch. `button.js` made by @JustOff and I leave it to him. Or to you.

:-)

IMHO: It must be thoroughly tested (also).

**Comment by JustOff** [comment]
Good catch @janekptacijarabaci! It turns out that `sdk/ui/buttons` does not really handle spaces, flexible spaces and separators properly. I'll take a closer look tomorrow.

PS: This also means that all my non-sdk add-ons also have this flaw for years ;)

**Comment by wolfbeast** [comment]
So who will work on this then? @JustOff ?

**Comment by JustOff** [comment]
Since this is my fault, I'd prefer to correct it myself.

**Comment by jg-github** [comment]
Unfortunately, the unstable of 06 July 2018 on partially fixes the issue. Please see my latest post to https://forum.palemoon.org/viewtopic.php?f=63&t=19544&p=145026#p145026

Thank you.

**Comment by jg-github** [comment]
Please excuse me, I made a mistake. The problem has indeed been solved.
