### ISSUE TITLE
Page Info / [PALEMOON] Permissions Manager - "Offline Storage" permissions (for individual pages) was removed in the backend

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#582]
`Offline Storage` (`IndexedDB`) permissions (for individual pages) in the frontend does not make much sense because it was removed in the backend. Even if `Clear Storage` (and display the size) will still work but only in some cases.

Ad
https://forum.palemoon.org/viewtopic.php?f=63&t=19558#p144684

> Even if I set Twitter to allow, it wont work.
> ALL sites need to be allowed.

See also [bug 1334411](https://bugzilla.mozilla.org/show_bug.cgi?id=1334411) - Obsolete UI for IndexedDB in Page Info/Permissions.

I propose to remove this code (altogether):
[_testBranch_...](https://github.com/MoonchildProductions/UXP/compare/master...janekptacijarabaci:_testBranch_pageInfo_permissions_indexedDB)
(tested for `Pale Moon` and `Basilisk`)

**Comment by SpockMan02** [comment]
So without per-site permissions, how does it work? Allow for all pages or none?

**Comment by wolfbeast** [comment]
According to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1147821) it's now all controlled by the third party cookies preference. I.e.: third party cookies also includes site storage now.
Individual controls are no longer present and actually not desired (because all it would do if not aligned is break things in various colorful ways).

Removing the control from the permissions manager/page info is the correct action here. Please make a PR, @janekptacijarabaci since you already did the work ;)

**Comment by SpockMan02** [comment]
Will the cookies preference be renamed?

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.
