### ISSUE TITLE
Flying images ie testdrive regression

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#626]
https://testdrive-archive.azurewebsites.net/Performance/FlyingImages/Default.html

Performance regression in UXP platform and in Pale Moon 28 beta 3 when 256 images are selected. In Tycho/Pale Moon 27 it works with 60 fps. In UXP it works around 15-20 fps. Same regression also happens with all amount of images other than 36 images.

This regressed in Firefox 42.

last good: Firefox 42 ( 15.7.2015)

first bad: Firefox 42 ( 16.7.2015)

https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=16e30af059b7&tochange=72835344333f

**Comment by wolfbeast** [comment]
This is probably not a bug -- that benchmark hammers the surface cache with images at all scale levels, which is very a-typical behavior for use on the web.

**Comment by wolfbeast** [comment]
It's a performance/efficiency trade-off. It regresses this particular benchmark, but improves normal use.
I do however see a potential flaw in the logic in that bz patch though. I'll have to try a few things to see if I'm right.

**Comment by wolfbeast** [comment]
No, the image surface cache handling is correct. 

This is something else -- I compared and the slow-down is because we're high-quality scaling these images (there's a significant visual difference!), which points this to https://bugzilla.mozilla.org/show_bug.cgi?id=1182929 in that regression range.

The benchmark test uses `position:absolute` on the images for each iteration of the image, which means the hq scaling algorithm on a non-layered image is used (the source images are 540x540 (or 1800x1800 in the case of the large IA logo!) and are down-scaled past the threshold where layer use is refused). not leveraging HWA layers and HQ scaling is expensive, and that causes the drop in FPS.
**Not** doing this (and using optimized layers) would cause `position:fixed` and `position:absolute` images to become aliased if scaled down from a very large size, because we can't use HQ scaling on HWA image layers.

Now, it's possible to kill that threshold and always use layers, of course, but then you'd have quality issues in normal use for downscaled images. Since fixed/absolute positioning is a very common use I'm not willing to kill image quality in regular webpages just to satisfy a benchmark. if absolutely necessary it can be made configurable, but what's the point?

**Comment by mattatobin** [comment]
How much work would it require to make it a pref?

**Comment by wolfbeast** [comment]
> How much work would it require to make it a pref?

Not too terribly much (it should be added to the gfxPrefs); because this is a relatively hot path, it shouldn't be made a "live" pref as the lookup would cost us more perf in that case.
