### ISSUE TITLE
Pale Moon can't load about: pages from about:support and about:about when the latter is loaded via various "load in new tab/window" UI actions

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#679]
It seems this issue is related to the following bugs:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1329032
* https://bugzilla.mozilla.org/show_bug.cgi?id=1331686
* https://bugzilla.mozilla.org/show_bug.cgi?id=1333726

I also found that while these bugs are targeted to Firefox 53-54, they are somehow already partially implemented in the current UXP tree.

At the same time Basilisk doesn't have this problem.

**Comment by Vangelis66** [comment]
@JustOff 

Many thanks for filing this; I had reported what appears to be the same issue [here](https://msfn.org/board/topic/177125-my-build-of-new-moon-temp-name-aka-pale-moon-for-xp/?do=findComment&comment=1152539), running the _New Moon 28.0.0b4_ **fork**, but was hesitant to post the bug here in GitHub, as (probably) not being entitled to (I can only run the fork, being on **Vista**, not the official PM28 builds)...

Best regards

**Comment by janekptacijarabaci** [comment]
I'm working on it...

**Comment by JustOff** [comment]
I confirm the PR above resolves this issue.

@Vangelis66 
Vista is a supported platform for Pale Moon UXP, so actually you don't need any forks.

**Comment by Vangelis66** [comment]
[Apologies to all in advance for this obviously off-topic comment (it doesn't add/contribute to the bug reported/discussed); however, I had to get things straight (and possibly vent a tiny bit, for which I apologize profusely...)]

@JustOff wrote: 

> @Vangelis66
> Vista is a supported platform for Pale Moon UXP, so actually you don't need any forks.

I hold the greatest respect for you, @JustOff, for being the head of the Pale Moon localization team and the maintainer of various valuable XUL extensions for Pale Moon, Basilisk and pre-Quantum Firefox; much respect, of course, goes to the main Moonchild Productions Team, too (TBH, somewhat less respect to a certain dev who, in the recent past, used foul language when referring to Vista users, but that's water under the bridge...).  

So I was quite miffed when you posted the afore-quoted claim/statement, evidently without checking first its validity: **UXP (Take 2) as a platform and Pale Moon 28 (built on it) never had, by design, any Vista support whatsoever** :angry:

When the Mozilla ESR 52.6.0 platform was forked as the foundation of current UXP, yes, it came with full Vista (and XP) support, but one of the first tasks of the Moonchild team was to irradicate that support; you can have a look at the relevant commits, it's highly probable I missed some: 

Vista EOL:

https://github.com/MoonchildProductions/UXP/commit/4c697043da9fe3f58a7e070dad74eab6972695a0
https://github.com/MoonchildProductions/UXP/commit/fd9d8c20d21f527d99bf9ce3d3f0f25f85fb029c
https://github.com/MoonchildProductions/UXP/commit/9ecbf33313eee5c4e068e61451634cbfe4790694
https://github.com/MoonchildProductions/UXP/commit/5d1eb0d3aa590338930553cb7e09c43c4840ef1a
https://github.com/MoonchildProductions/UXP/commit/a930db1c9e8444ed89754c5a79085d59c7295952
https://github.com/MoonchildProductions/UXP/commit/f1e863a490ae20173210a53f516e146ebc677a36
https://github.com/MoonchildProductions/UXP/commit/da8f20a3b05387aaa1c7c81543f1aae6dd1ca99d#diff-0b08792398c408a93dd2a72b4b61cab5
https://github.com/MoonchildProductions/UXP/commit/38ec1c796d64fcf9d73a897685cadbf0ad74fed0
https://github.com/MoonchildProductions/UXP/commit/f297ef798e3b4577bb82119161ea9628f37ba796
https://github.com/MoonchildProductions/UXP/commit/13a9ea6486df49cee94a5e5a23b02dca13968eb7
https://github.com/MoonchildProductions/UXP/commit/4f82d71df070e813927893fc20aa7954fbae997d
https://github.com/MoonchildProductions/UXP/commit/39578317eebdc75fb25f6b434772a11e724c1ebd
https://github.com/MoonchildProductions/UXP/commit/2e0f80af425efae17416064bf1427bdfb1dd0fee
https://github.com/MoonchildProductions/UXP/commit/ee70e3a3661748efbf713e3469e3ee33feae3978
https://github.com/MoonchildProductions/UXP/commit/3d37f61816aafcb0ae817003a9f4822e81252d3a
https://github.com/MoonchildProductions/UXP/commit/039f3e49c7ba28dcf00cffb76e7af62fe52b1026
https://github.com/MoonchildProductions/UXP/commit/2b01522cf3cda6343fab8a6e3482636d0fb6c4bd
https://github.com/MoonchildProductions/UXP/commit/e52c019ec8377859b6df5e50ca40a40ea20702b9
https://github.com/MoonchildProductions/UXP/commit/c7668971968e044e85446d79362d7744846efdd0
https://github.com/MoonchildProductions/UXP/commit/85edb1c711f7816ed1a30edd07b37d314fac216a
https://github.com/MoonchildProductions/UXP/commit/a24398e42d2f300b5979d1fb45a481e2912fd4f3
https://github.com/MoonchildProductions/UXP/commit/b55f0e7f0d3c66b609ac8979265c62bd1fa85bb6
https://github.com/MoonchildProductions/UXP/commit/47b8c58d47bae45d723ef22665e8f13ecc66725f
https://github.com/MoonchildProductions/UXP/commit/b62fce0dc0c77a5788c331db32b3996e4020e2a5
https://github.com/MoonchildProductions/UXP/commit/756b27f58d6961457989cd02bb45bc6465aedce7

In addition to the UXP platform not supporting the Vista OS, when official win32 Pale Moon 28 binaries were made available in the unstable channel, compiler optimizations were such that **they excluded NT 6.0** kernel (Vista + Server 2008) from being compatible with the binaries; not only do the official PM28 binaries require `subsystem version >= 6.1`, but even if that limitation is lifted off (easily done with specialized PE apps), the binaries themselves make several (6 to 8) API calls to functions not present in either kernel32.dll/shell32.dll of the Vista OS... And even if these calls were to be stubbed (not an easy task, if at all possible), the binary would be severely misperforming under Vista, due to the underlying platform code not supporting the OS... 

The above remain valid even with latest official **PM 28.0.0b4 (2018-07-20) (32-bit)**, **buildID=20180720133932** binary on the Pale Moon unstable channel. 

Tycho (now EOL'd) is/was the last MC platform to support Vista (with some limitations present on the PM27 64-bit binaries for the x64 flavour of Vista); current (and probably last) stable release of Pale Moon 27.9.4 32-bit runs flawlessly on my Vista SP2 32-bit OS (PM27 my main browser for the last 10 months here); the last PM unstable channel build to run here was **27.9.1a1-git-20180503-g57f668c.en-US.win32, buildID=20180503064227** (of course on Tycho...).

Drop of Vista support on PM28 has been already documented in [MSFN forums](https://msfn.org/board/topic/177123-palemoon-crash/?do=findComment&comment=1151447); there has also been some [vague talk](https://forum.palemoon.org/viewtopic.php?f=3&t=19524#p144333) over at the PM forums about UXP+Vista, but nothing has, as of yet, materialized, not at the platform code level nor at the binaries offered level... 😞 Excellent analysis can be found in [this](https://msfn.org/board/topic/175262-last-versions-of-software-for-windows-vista-and-windows-server-2008/?do=findComment&comment=1151617) MSFN forum post...

So, to conclude, I **do have to use the forks**, the _New Moon 28.0.0b4 (2018-07-27) (32-bit)_ one and the _Serpent 52.9.0 (2018-07-27) (32-bit)_ one (using it now to type this), both kindly compiled and offered by @roytam1, instead of the official MC ones... 

Unless one uses the Vista OS itself or has installed it in a VM (+ 2 Service Packs + platform update supplements + all M$ updates until Apr 2017, to be followed optionally by manually installing WinServer 2008 updates that M$ makes available till Jan 2020) and test there **latest** Basilisk52 and PM28 official releases, one should not proceed to making claims of Vista being supported in UXP...

I meant not to insult anyone, just wanted, beyond any doubt, to clarify on what is actually an inaccuracy... 
Perhaps, in the near future, @wolfbeast will have a change of heart with regards to UXP on Vista; until that time, the _forks_ it is here... 😉 

Best regards

**Comment by JustOff** [comment]
Although I do not use Vista myself, I was absolutely sure this platform is supported by UXP, because this was stated in [this announcement](https://forum.palemoon.org/viewtopic.php?f=62&t=19269) and in [this comment](https://forum.palemoon.org/viewtopic.php?f=3&t=19524#p144333) from Moonchild.

@wolfbeast, perhaps you need to update the [minimum platform requirements](https://forum.palemoon.org/viewtopic.php?f=62&t=19269) to Windows kernel 6.**1**+?

**Comment by wolfbeast** [comment]
The "minimum platform requirements" post was a discussion post.
I never posted any system requirements for Pale Moon 28 yet. Sorry about the mixed signals in that other post but Vista isn't supported by UXP and anything building on it.

What's more relevant is [this thread](https://forum.palemoon.org/viewtopic.php?f=61&t=18253&p=134148&hilit=no+overlap#p134148)

**Comment by wolfbeast** [comment]
Here. an update. https://forum.palemoon.org/viewtopic.php?f=62&t=19790

**Comment by JustOff** [comment]
Thank you for the clarification.

**Comment by Vangelis66** [comment]
> Here. an update. https://forum.palemoon.org/viewtopic.php?f=62&t=19790

The unstable channel "**Downloads**" section will also have to be updated, to reflect the above. 

Currently, http://www.palemoon.org/unstable/ states under "**Minimum System Requirements:**"
```
Windows Vista/Windows 7/8/10/Server 2008 or later
Windows Platform Update for Vista/7 strongly recommended
```
> What's more relevant is [this thread](https://forum.palemoon.org/viewtopic.php?f=61&t=18253&p=134148&hilit=no+overlap#p134148)

=> 

> there is no actual lifetime overlap between Vista and a new product released in 2017/2018.

 To be brutally honest, I never in the life of me understood the strength of that argument; practice has shown that older OSes become really deprecated by the loss of supported browsers (while newer versions of browsers try to keep up with the ever changing web standards); PM would have been the perfect browser choice for these slightly older platforms, once the big browser vendors, aligning themselves behind M$, drop support. 

 Win7 is in its last leg of Extended Support, getting only security updates; Vista SP2 can be argued that it is in a similar state - no feature updates exist for it, only security updates can be (manually) applied to it (via the WinServer 2008 update path); at the end of the day, I simply don't fall for that "lifetime overlap" reasoning and acknowledge other factors were decisive towards Vista being chopped... 
But this has been already beaten to death over in the PM forums, so I'll end it here; it was **Moonchild**'s final call and we'll have to live with that, no more questions asked... 

I still wish the best for UXP (after all, the _forks_, too, build upon it...) ! 

@wolfbeast 
Can a person running a Vista compatible fork report issues in this tracker, or is it off-limits for such a person?

**Comment by wolfbeast** [comment]
So you don't understand software development not targeting anything that is still **actively** supported as a platform? Well sorry but that's just how things are. Whether you do or don't understand it has unfortunately no bearing on our design decisions.

**Comment by wolfbeast** [comment]
Also there is no argument -- Vista is past EoL. Win 7 is not. That is a hard line we drew when we started on UXP last November.
Thanks for pointing out the discrepancy on the unstable channel -- I did not update that since we moved from Tycho and I'll correct that in a minute.

**Comment by wolfbeast** [comment]
Reporting issues on this tracker when on Vista should be done with due care -- if it's unknown or likely to be a platform related issue it's better to post on the forum first, and if confirmed by someone on a supported platform, then create an issue on the repo for it; just to keep bugspam to a minimum, if you understand.

**Comment by wolfbeast** [comment]
Please direct further Vista discussion to the forum. Thanks.
