### ISSUE TITLE
Pale Moon status/link text popup obscures find bar

### ISSUE THREAD

**Issue by Ascrod** [MoonchildProductions/UXP#715]
When the status bar is configured to show the status or link text in a popup, the popup displays in front of the find bar. The popup should display above the find bar, as it did in PM 27.

This was reported on IRC. The original reporter's OS is Windows 10. I see the same thing on Linux Mint 18.3.

Reporter's screenshot:
![](https://a.doko.moe/twqpjn.png)

**Comment by wolfbeast** [comment]
Cause; Since the Find Bar element is no longer part of the main browser XUL window and becomes part of content (which is normally overlapped by the pop-up), the pop-up now overlaps the Find Bar when present while previously it would sit above it since the content window would shrink when opening the Find bar.

We need to adjust the position of the pop-up tooltip when the Find bar is open as straightforward solution. This could be done with an offset, or alternatively, we could make the status pop-up a child of the tabbrowser tab instead of the browser window which is structurally neater but probably more work to achieve.

**Comment by JustOff** [comment]
*/offtopic mode on*
I wish we could return the findbar back to the main window ... I still can not get used to it after the June changes.
*/offtopic mode off*

**Comment by wolfbeast** [comment]
@JustOff I tried retaining it but it was just not possible. The platform rearchitecturing simply doesn't allow for it to be a global toolbar any longer.

**Comment by mattatobin** [comment]
Why do we still support the status popup at all? Logic follows that if someone doesn't want a statusbar they don't want status text.

**Comment by wolfbeast** [comment]
It is per tab because I couldn't get it to work properly as a global on UXP. I spent 2 full days trying and had to give up. The fact that the underlying reason is rearchitecturing done for e10s doesn't matter, because the rearchitecturing was done and if you want to go back to global, then you HAVE to revert everything that was done in the rearchitecturing over many Firefox cycles. With Tycho it was still doable, but this lies at the core of how content browsers are slotted together. So there is no "just revert it" here.

**Comment by wolfbeast** [comment]
With the findbar being made global again with the merge of the work branch in b07b08f9db6ac66f8b7526a0cd835bec931b0423 , tip of the master branch should have this resolved now.

**Comment by JustOff** [comment]
> tip of the master branch should have this resolved now.

I confirm this.
