### ISSUE TITLE
Tab history does not store the "about:newtab" page, but the "about:logopage" is stored

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#719]
As reported on the forum, [users can no longer go back in history to QuickDial](https://forum.palemoon.org/viewtopic.php?f=3&t=20024) (`about:newtab`). At the same time, the `about:logopage` is now stored in the tab history, while it should not.

**Comment by wolfbeast** [comment]
Following the discussion on the PR, moving it here.
@mattatobin is right that these internal pages should not be in the history chain because it is a security risk due to those pages having chrome privileges. A script on a page navigated to from newtab can exploit this by paging back in history and having privilege escalation that can be exploited with some trickery.

It was most certainly not a "screwup" and very much deliberate to remove about:newtab from the history chain. Before we add this back to it, we have to make sure about:newtab isn't chrome-privileged because that would just be an accident waiting to happen.

**Comment by JustOff** [comment]
A lot of internal pages with chrome privileges are stored in the history, not only `about:newtab`, but this never led to security issues I know about. Moreover, all the "start pages" provided by add-ons are also chrome-privileged, and I also never heard of an attack vector that would use this.

So, as long as we can't completely exclude all chrome-privileged pages from the history, I don't see any practical sense to restrict `about:newtab` specifically, especially given the purely hypothetical nature of "some trickery" mentioned above.

**Comment by wolfbeast** [comment]
The difference is that navigating to a new page from the newtab page is **common**. Doing so from "add-on start pages" is **not** common and those are normally closed after taking note of the information/message displayed on it. "Some trickery" is also most definitely not hypothetical (since you can access the initial page through e.g. `opener.history.back()` from a spawned window), although because there is (for now) no directly exploitable vulnerability through e.g. cross-object wrappers it's only a moderate security issue, but one that could easily become critical if a new exploit vector is found. Keeping the door firmly closed on that kind of vulnerability is a Good Thing™.

**Comment by JustOff** [comment]
Sorry, but `window.opener` is always `null` when navigating from `about:newtab` (also with #720 applied), and `window.history` does not provide any *access* to the pages or we could not trust the browser at all.

**Comment by wolfbeast** [comment]
`about:newtab` doesn't have to provide an `opener`. I don't think you understand the risk.

**Comment by JustOff** [comment]
I created a test page (potential attacker) and checked `opener` from this page, loaded from `newtab`.

**Comment by wolfbeast** [comment]
The `opener` is only used as a handle to the history chain from a spawned window so navigation can happen without losing the malicious content (since it'd live in a spawned window).

`about:newtab` -> malicious page -> spawned window.
The spawned window can use the `opener` (pointing to malicious page) that has history to go `back()` into said history to `about:newtab` if recorded in that history, leaving the chrome-priv page in what is pointed to by `opener`.

**Comment by JustOff** [comment]
Sorry once again, but if someone find a way to force the browser to act the way you described above, then they will be able to completely get over the data from all sites in the navigation history. And that would be such a big security hole that everything else just would not matter.

**Comment by wolfbeast** [comment]
It's not that simple, though.
I did verify that permissions are set properly (so e.g. opener.location.href throws an access denied, and `Object.getPrototypeOf(Object.getPrototypeOf(opener))` throws because the prototype returns null, but it is most definitely possible to spawn a window and have that window trigger navigation in the opener.

If there's -any- vulnerability in the opener (window) object after navigation that will allow access then that would risk chrome level code execution if `about:newtab` is in history. That is many times more dangerous than having direct access to other pages in the tab's history. So it most definitely **does** matter if such a security hole would be found.

Consider this a defense-in-depth measure that I would like to maintain.
If it's an absolute breaking level of inconvenience for people we can always put it behind a pref to allow `about:newtab` to be a history entry, but the default should be to not put it in history.

**Comment by JustOff** [comment]
> Consider this a defense-in-depth measure that I would like to maintain.

I can't fully agree, but you decide, and I appreciate you took the time to explain the reasons in detail.

> If it's an absolute breaking level of inconvenience for people we can always put it behind a pref to allow `about:newtab` to be a history entry, but the default should be to not put it in history.

Does the name `browser.newtabpage.add_to_session_history` look appropriate?

**Comment by eNdEmiOn** [comment]
So is it going to get fixed or not? I can't tell from what's said here.

**Comment by wolfbeast** [comment]
Completely irrelevant, @Veneth9 

@eNdEmiOn yes it will be "fixed" in as far as that the option will be available to make it have a history entry, at your own risk.
