### ISSUE TITLE
Bookmarks, cache and download/upload of data

### ISSUE THREAD

**Issue by Felipefpl** [MoonchildProductions/UXP#724]
Hi, i want to report problems with bookmarks with both pale moon/basislisk:

Bookmarks arent imported in alphabetical order, neither you can organize them clicking in the column of names or using the "views" -> "sort" setting that is in the bookmarks manager, you have to use cut/paste or move the bookmarks with the mouse to organize them alphabetically.

Both browsers keep downloading data once you press ESC or the X button, this is FAR worse on pale moon, this is most noticeable when you have slow speeds like 128 kbps.

We should be allowd to have more than 1024 MB of cache, also, in this day and age we should have GBs instead of MBs, i'd set 99 GBs if i could but we have this limit that doesnt make sense at all, specially for ppl with hundreds or thousands of bookmarks. The only limit should be the free space in the hard disk.

**Comment by wolfbeast** [comment]
Multiple issues, but all have a simple answer:
1. You can organize bookmarks and sort them, but you have to do this for each folder individually (it's not recursive) -- this is by design.
2. The modern web relies on background downloads in many cases (DHTML, workers, AJAX, etc.). Pressing Esc or pressing the X will stop the main document request but does not stop other downloads -- this is because that would completely break many web applications.
Pale Moon offers an alternative stop (Shift+ESC) which stops everything: background downloads, network connections, incomplete downloads and animated images. Not the above: most web applications will not like this and break.
3. The size of the cache brings with it cache management. Having a mega-cache would require so much management overhead that the browser would become unworkable due to constant indexing and updating of the cache bookkeeping. This is already very noticeable at 1GB, and the main reason why the default is less than that to balance out cache vs. overhead. In addition, a mega-cache would result in the vast majority of cached data being stale and therefore quite pointless to keep. Cache also has nothing to do with how many bookmarks you have -- they are 2 completely different things.

**Comment by Felipefpl** [comment]
wolfbeast - i see, thanks for the explanations and for the shift+esc hint, i didnt know about it.
