### ISSUE TITLE
Change mozilla.pdf to a dated format.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#744]
As discussed in #729 the default name for saving PDF files when no file name is supplied by the server should be changed to `document-yyyymmddhhmmss.pdf`.

This will need a bit of code to grab the system datestamp and convert it to the desired filename format, but otherwise straightforward and low-risk.

**Comment by zqqw** [comment]
I've made some progress on this, to update this issue a little:
`
diff --git a/widget/gtk/nsDeviceContextSpecG.cpp b/widget/gtk/nsDeviceContextSpecG.cpp
index 0bd87bd85..39ffba8b1 100644
--- a/widget/gtk/nsDeviceContextSpecG.cpp
+++ b/widget/gtk/nsDeviceContextSpecG.cpp
@@ -410,14 +410,20 @@ NS_IMETHODIMP nsPrinterEnumeratorGTK::InitPrintSettingsFromPrinter(const char16_
   /* Set filename */
   nsAutoCString filename;
   const char *path;
+  char *datestring;
+  GDateTime *gdt;
+
+  gdt = g_date_time_new_now_local();
+  datestring = (char*)g_date_time_format(gdt, "%FT%R:%S");
+  g_date_time_unref(gdt);
   
   if (!(path = PR_GetEnv("PWD")))
     path = PR_GetEnv("HOME");
   
   if (path)
-    filename = nsPrintfCString("%s/mozilla.pdf", path);
+    filename = nsPrintfCString("%s/document-%s.pdf", path, datestring);
   else
-    filename.AssignLiteral("mozilla.pdf");
+    filename = nsPrintfCString("document-%s.pdf", datestring);
 
   DO_PR_DEBUG_LOG(("Setting default filename to '%s'\n", filename.get()));
   aPrintSettings->SetToFileName(NS_ConvertUTF8toUTF16(filename).get());

`
But although that builds and displays what you would expect, firstly it is now too long for the box it is in, so I need to find that and extend it. And it does not save the file in my test build, firstly it printed this error twice at each attempt to print to file:
`
/opt/pmtest$ ./palemoon/palemoon -no-remote -profile ~/testing123profile/

** (pale moon:3029): WARNING **: 19:55:54.165: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Avahi was not provided by any .service
files

** (pale moon:3029): WARNING **: 19:55:54.166: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Avahi was not provided by any .service
files
`
So I installed avahi-openrc and enabled the avahi daemon, which got rid of the error message, but it still wouldn't actually save the file, even when I installed pdf viewer from Isaac Schemm like in my regular unstable Pale Moon. So either there is an issue with my build or the code change. I also have noticed the latest unstable version does not appear in the tag list, I built on the head and the resulting tar.bz2 showed the latest version number.
I have yet to figure out how to do incremental builds rather than rebuild from scratch, so that's a bit of a delay too.

**Comment by zqqw** [comment]
There could be some issues with this little section of code in general, the no pdf written has been a recurring bug in the past:
   if (!(path = PR_GetEnv("PWD")))      <testing 'if not' an assignment, not == equality ?

**Comment by wolfbeast** [comment]
You need to use CStrings for `nsPrintfCString()`, not the hacky `char*` pointer.

As for the assignment inside an `if`, that's a little hacky. No, they are not testing for equality -- they are testing if the assignment succeeded. It could be rewritten in a more standard way but you'll have to check what `PR_GetEnv` returns if the Env Var doesn't exist. I'm assuming it's `null`.

**Comment by wolfbeast** [comment]
You probably do want to use the date and time functions already provided in our code though, and not glib-isms as it won't be portable. See `GetFormattedTimeString` and `PR_Now()`.

**Comment by wolfbeast** [comment]
@zqqw Are you still interested in finishing this or not?

**Comment by zqqw** [comment]
Sorry, I've been busy and only had a few minutes spare computer time now and again lately.
I found that function in dom/base/nsDocument.cpp, and sort of figured out how to use it perhaps. But with these undocumented internal functions and types, and a build time over an hour it might still take some considerable time!

**Comment by wolfbeast** [comment]
If you'd feel more confident someone else takes it for it to be done in a reasonably short amount of time, let us know.

**Comment by zqqw** [comment]
OK, I have got back to it again, and have improved my build process too! 
mk_add_options MOZ_MAKE_FLAGS="-j1"
allows it to run in the background, also I thought that because I couldn't get it to stop clobbering it wouldn't help to rebuild the previous attempt, but actually it does reduce the time a lot on subsequent runs.
I've found a new bug that had been confusing the issue - when you print to file, it will seem to work but not actually create a file if there is a colon ":" in the name. My date had 2 so whatever I did failed! I will look into it some more.

**Comment by zqqw** [comment]
Apparently the colon was/is a reserved character in Windows and Mac, it can't be used in file names, while it can in (current) Linux.

**Comment by wolfbeast** [comment]
Why aren't you sticking to `document-yyyymmddhhmmss.pdf` as stated in the first comment here?

**Comment by zqqw** [comment]
There are colons in most standard date - time representations, and that is what GetFormattedTimeString returns:
if (SprintfLiteral(formatedTime, "%02d/%02d/%04d %02d:%02d:%02d"
It is the internationally recognised ISO 8601 format:
https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations
As a mostly Linux user I was just unaware that you couldn't have a colon in a filename on some OS's or that in this case it would fail to write the file silently, so the colon negated anything I did. But I'll drop them now.

**Comment by wolfbeast** [comment]
Clearing milestone - this is obviously going to take longer than intended.

**Comment by zqqw** [comment]
It could be changed to document.pdf for the default value easily. But I hit a new snag for the date. The print dialogue seems to be created as a fairly standard GTK print dialogue. The first time you enter a value, it is cached in the profile and that name and dir is shown the next time you save a file. This is mostly helpful behaviour. But it means the first time a file is saved with a date and time, that is cached, and the same date and time is shown thereafter. So you could get rid of the caching, every time you save a file it shows document-yymmddhhss.pdf. But that is not so good as what's there. Or the print dialogue could be rewritten so there was a checkbox allowing yymmddhhss to be automatically added as a prefix for example. But that might be quite difficult (perhaps) because GTK sometimes does a lot very simply, but only if you accept what it does as standard. The caching behaviour seems to be in the GTK code, not the Pale Moon code.

**Comment by wolfbeast** [comment]
I'm surprised that if you feed a specific file name to the save dialog box, that GTK ignores that and displays the cached value. I doubt that is intended behavior. Is the value passed properly to the dialog?

**Comment by wolfbeast** [comment]
Also, is this a Linux-only issue? if this filename creation also applies to Windows, then similar changes need to be made there.

**Comment by zqqw** [comment]
``  // To be convenient, prefill the textbox with the existing value, if any, and select it all so they can easily
  // both edit it and type in a new one.
  const char* current_text = (const char*) g_object_get_data(G_OBJECT(changed_box), "custom-text");

(widget/gtk/nsPrintDialogGTK.cpp)

**Comment by zqqw** [comment]
The bit in nsDeviceContextSpecG.cpp is just a first run initialization of the value. I haven't really figured out the gtk caching so far. widget/gtk is pretty much the only area of gtk code in the source, and it has compatibility stubs for GTK2 & 3 in there. GTK is supposed to be multi-platform so it might be universal, I don't know yet. My current idea would be to have a new check box allowing a date to be added as an uncached prefix (that would help file sorting more than a suffix) and set the initial value to "document" and leave the rest as it is. It's just a plan so far, I've been studying this folder to gain some overview of it first.

**Comment by kn-yami** [comment]
In UXP GTK is only used for Unix-like operating Systems, Windows builds use WinAPI and macOS use Cocoa, IIRC.

**Comment by mattatobin** [comment]
SO is this ever gonna happen or should we just change it to goanna.pdf?

**Comment by zqqw** [comment]
Well I am still looking at it when I get a chance, but I have been busy lately, so anything.pdf would be quick and easy. Changing the name was simple which was why I originally suggested it, but adding a date involved several things beyond my existing knowledge, although it seemed straightforward at first. The value gets cached in about:config as print.print_to_filename so that's possible to use with some internal functions, and the print dialog can be modified, but only by adding another tab:
https://developer.gnome.org/gtkmm-tutorial/stable/sec-extending-print-dialog.html.en
The gtkmm doc source package contains the only example I can find of a modified print dialog and I've got as far as building the example. It would also only work on LInux, but should not affect other builds, whatever.pdf would help them too.

**Comment by mattatobin** [comment]
Why not just modify the preference before you read it. Simple hack that is good.. enough.

**Comment by zqqw** [comment]
![P4220795](https://user-images.githubusercontent.com/18177475/56476753-bec48b80-6494-11e9-9e11-7e4ec1b67044.JPG)
I made some progress with custom tabs and options in GTKMM, so I'm now heading towards a GTK3 version.

**Comment by wolfbeast** [comment]
Please keep it simple. The "Good enough hack" suggested by Tobin sounds fine.

I wouldn't want to end up with a completely custom dialog that nobody on our team knows how to maintain and that can break at any point distros decide to do something different than last week.

**Comment by zqqw** [comment]
![P4220807](https://user-images.githubusercontent.com/18177475/56523424-5c749500-653f-11e9-9664-fd910db16322.JPG)
OK, here was a GTK3 custom dialog tab test example. Although I have been getting somewhere on the GTK side of things I haven't even really looked at connecting it to Pale Moon and doing useful stuff yet. And it will only work for the Linux build too. So if you are (understandably) tired of waiting and Matt has a good solution, go for it!

**Comment by mattatobin** [comment]
I have an idea for the solution which is a simple hack as I stated. I am not gonna do the work though.

Also, please call me Tobin.

**Comment by wolfbeast** [comment]
@mattatobin Can you at least provide a detailed description of the solution, even if you don't want to do the code work?

**Comment by wolfbeast** [comment]
Since EVERYONE dropped the ball on this one, I'm closing this.
