### ISSUE TITLE
adding DNS over HTTPS support

### ISSUE THREAD

**Issue by Azizb750** [MoonchildProductions/UXP#798]
Hi there, today I downloaded your Basilisk Browser, it was faster than Firefox as it seems, but when I was exploring about:config, I noticed that "network.trr.*" values was missing, which are existing in the latest Firefox, is possible to add DNS over HTTPS support in Basilisk? without them i can't even add DNS over HTTPS. thanks!

**Comment by khronosschoty** [comment]
I know its not a solution or anything but have you considered something like https://github.com/jedisct1/dnscrypt-proxy ?

**Comment by wolfbeast** [comment]
There are many issues with the concept of this, not in the least the fact that you will be leaking potentially-private network requests to a public resolver (think corporate LAN) and all the resulting issues with preferring a public resolver over a system-defined one.

It's a potential solution for a very specific case of untrusted local networking that is better solved network-wide instead of on a service-by-service basis. It has no place here.

Wontfix. Please take further discussion to the Pale Moon forum, thanks.

**Comment by Azizb750** [comment]
OOhh, I didn't knew that DNS over HTTPS was a threat for privacy(especially that fact about Cloudflare, which was advertised as the safest and fastest DNS option exist), while I knew that it was an safer option to use DNS on a browser
Today I learned something important from you, thanks a lot!

**Comment by wioxjk** [comment]
Why was this closed?
There is no reason to close this issue only because Mozilla chosed Cloudflare as their default provider.

There is alot of different providers that supports DoH - you can also self-host a DoH server if you want to.

I would like to see that DoH was supported by Basilisk/Pale Moon, but disabled by default and the default Cloudflare option was removed.

**Comment by wolfbeast** [comment]
> Why was this closed?

https://github.com/MoonchildProductions/UXP/issues/798#issuecomment-425670414
