### ISSUE TITLE
Non-working notifications

### ISSUE THREAD

**Issue by mimecry** [MoonchildProductions/UXP#817]
1. When I click on a notification, the focus is not switched to the tab of the notification's origin

2. The following button has no effect

![image](https://user-images.githubusercontent.com/10742312/46582350-646f5a80-ca6f-11e8-9d66-04e657bad104.png)

This error appears in the console when a notification appears. No other error message appears, despite my attempts to interact with the notification dialog.

![image](https://user-images.githubusercontent.com/10742312/46582367-a9938c80-ca6f-11e8-8cda-8cea2e73ed3c.png)

Windows 10 x64 1803, PM 28.1.0, fresh profile

**Comment by Vangelis66** [comment]
This is a regression of Tycho issue [#1641](https://github.com/MoonchildProductions/Pale-Moon/issues/1641) due to change of platform to UXP; it is already reported in the forums at least twice: 

https://forum.palemoon.org/viewtopic.php?p=151120#p151120

> I think this fix was somehow lost in 28.0.x. After I updated, the pop-ups no longer switch me to the browser and/or tab.

and 

https://forum.palemoon.org/viewtopic.php?p=151769#p151769

> couple of notification bugs i noticed:
> - clicking on one doesn't direct you to the associated tab (TST bug?)
> - nothing happens when clicking on 'Notification settings'

but it went somehow unnoticed by the devs... FWIW, this is not a platform bug, but it is specific to application **Pale Moon**; Basilisk 52 behaves correctly... 

STR: 
OS: Win7 SP1 Home Premium 32-bit
Browser: Pale Moon 28.2.0a1 32-bit unstable, buildID=20181007063016
Test page: http://www.bennish.net/web-notifications.html

1. Click **Authorize** and grant notifications permissions (either for session/permanently)
2. Click **Show**; a web notification is shown for some seconds in the lower right of the GUI; if you are quick enough to click the gear button => Notification settings, this does not bring up any notification settings dialogue, but instead hides the whole notification...
(NB: On **Basilisk**, clicking the gear button takes you to **about:preferences#content** (in-content prefs tab), where you can indeed access **Notification Settings**;
Pale Moon does not have in-content prefs (Options), nor, to my knowledge, any equivalent notification setting in its GUI...
3. Click **Show in 5s** and then shift focus to another browser tab; as expected, the notification will pop-up soon; clicking on the body of the notification will hide it, without changing focus back to the tab that generated the notification (and this is the most annoying part of the bug; I am logged-in to several forums open in some of my 35+ tabs, any new message/reply/comment added to one of them triggers a notification OK, but I then have to hunt the specific tab (forum) that generated the notification)...
(NB: On **Basilisk**, clicking the body of the notification instantly takes you to the relevant tab...). 

Many thanks to the devs in advance for the eventual fix... 

(OT: My own laptop runs Windows Vista SP2, so I have to use the Vista compatible forks - New Moon 28.2.0a1 & Serpent 52.9.0 - there, but for the purpose of this bug report I borrowed my sister's laptop with aforementioned OS...)

**Comment by FranklinDM** [comment]
Notification settings _might_ not be opening because Pale Moon's nsBrowserGlue.js doesn't observe the `notifications-open-settings` topic (see [xref](http://xref.palemoon.org/uxp-trunk/search?string=notifications-open-settings&tree=uxp-trunk)) which gets notified when the Notification Settings button is clicked.
I suggest that it open the `about:permissions` page as that contains controls for showing notifications.

> 2. Click **Show**; a web notification is shown for some seconds in the lower right of the GUI; if you are quick enough to click the gear button => Notification settings, this does not bring up any notification settings dialogue, but instead hides the whole notification...

The gear button doesn't show up because for some reason, the origin of the notification doesn't get set. Without the origin, the gear button is hidden.

**Comment by Vangelis66** [comment]
@FranklinDM wrote: 

> The gear button **doesn't show up** because for some reason, 
> the origin of the notification doesn't get set. 
> Without the origin, **the gear button is hidden**.

First, thanks a bunch for your attention to this annoying bug... 
For me, the gear button _does not display_ only in Tycho platform (PM 27.9.4, 32-bit): 

![tycho](https://user-images.githubusercontent.com/9669492/46910701-6e9ec680-cf51-11e8-816c-c7483fab622a.jpg)

In UXP platform (PM unstable 28.2.0a1, 32-bit), **the gear button always displays**, as expected, and is _clickable_: 

![uxp1](https://user-images.githubusercontent.com/9669492/46910714-d05f3080-cf51-11e8-8799-989ee69c7db4.jpg)

As already reported by @mimecry, it is when clicking the gear button that the context selection (Notification settings) appears to not function... 

![uxp2](https://user-images.githubusercontent.com/9669492/46910755-d275bf00-cf52-11e8-8844-891b267913bc.jpg)

... And any comment on your part about the major issue with this bug, i.e. **not changing focus to the originating tab when the body of notification is clicked**? 

Sadly, I can't code at all, so my only contribution into making Pale Moon even better is making detailed bug reports and hoping that the devs will find the time and resources to address them, if at all possible that is... 

Many thanks to the whole team for what we have already, much appreciated indeed 👍

**Comment by FranklinDM** [comment]
Sorry, disregard my second point on the issue - An extension, gNotifier was the cause for the missing gear icon.

As for the not changing focus to the originating tab, I cannot reproduce it on a clean profile. I was able to reproduce it on my default profile but fixed it by resetting my toolbar configuration to default (deleting xulstore.json)

**Comment by mimecry** [comment]
@FranklinDM, your fix sadly has no effect on my profile

**Comment by Vangelis66** [comment]
@FranklinDM wrote: 

> As for the not changing focus to the originating tab, 
> I cannot reproduce it on a clean profile. 

... Am afraid this isn't so here 😞 ... But I already knew that because I had tried with, first, Safe Mode and then with a pristine new Pale Moon 28.2.0a1 32-bit profile; just to humour you, I just rechecked this now, and with only 3 tabs open (new clean profile, default xulstore.json, i.e. GUI setup), when clicking the notification popup I am not shifted to the originating tab: 

![clean](https://user-images.githubusercontent.com/9669492/46919505-f683df80-cfe8-11e8-9492-2e9ccd9e5749.jpg)

> I was able to reproduce it on my default profile 
> but fixed it by deleting xulstore.json 
> (which will reset your toolbar configuration and window positions).

I backed-up my regular profile before trying this, but it had no effect on the issue discussed... 

@mimecry wrote: 

> your fix sadly has no effect on my profile; 
> then again, i don't see why it would work, 
> considering that the same issue also appears
> for me on a fresh profile

... Likewise here... 

Perhaps @janekptacijarabaci, who was responsible for fixing [this issue](https://github.com/MoonchildProductions/Pale-Moon/issues/1641) on Tycho, is, hopefully, able to shed some more light on this...

**Comment by wolfbeast** [comment]
@janekptacijarabaci seems to have vanished without a word.

**Comment by mattatobin** [comment]
He had mentioned a few times this might happen ever since Tycho. For the record.

**Comment by mimecry** [comment]
@makotokato only temporarily i hope? any and all PM contributors are too valuable to lose

**Comment by FranklinDM** [comment]
I think I've found a solution to this. I'll send a PR but it needs to be verified first.

**Comment by mimecry** [comment]
both 1. and 2. from my original post are working as expected in the latest portable unstable (28.2.0a1 2018-10-24), with a fresh profile.

waiting for @Vangelis66's report before closing this issue

**Comment by Vangelis66** [comment]
@JustOff & @mimecry 

Apologies, as said I am on _Vista_ and don't have ready access to a Win7+ machine whenever I please...
There's some chance I can test the new PM28 unstable build sometime tomorrow (26/10/2018), in any case the Vista compatible fork is updated once weekly every Saturday, so, fingers crossed, coming Saturday's (27/10/2018) New Moon 28 build will have integrated the upstream fixes (#838, #845) and I'll be definitely in a position to test whether the issue here is indeed resolved; but I have no reason to distrust the findings of OP nor the expertise of the "fixers" themselves, so Saturday's test will simply be a formality for me... 😉 

Best regards and many thanks to all devs involved 👍

**Comment by mattatobin** [comment]
Umm.. We don't support Windows Vista and since the system requirements for Windows 7 are identical to Vista there is no excuse for using a half-assed compatibility fork that won't bother to distingish its self from us on a fundamentally unfinished operating system.

**Comment by wolfbeast** [comment]
@Vangelis66 Unfortunately I don't consider tests performed on a fork to be valid for verification of an issue in our tree. Since it was verified by mimecry, considering this verified and closed.

**Comment by Vangelis66** [comment]
@JustOff wrote: 

> @Vangelis66, please check if both issues are resolved in the unstable (20181024044650).

@mimecry wrote: 

> waiting for @Vangelis66's report before closing this issue

@Vangelis66 wrote: 

> There's some chance I can test the new PM28 unstable build sometime tomorrow (26/10/2018),

... At long last, late tonight I got hold of a Win7SP1 64-bit machine where I could test the latest **official** PM28 unstable build: 

![notifications1](https://user-images.githubusercontent.com/9669492/47597385-eb409480-d996-11e8-917e-65876e8cb4a6.jpg)

I repeated the tests outlined in my original [comment](https://github.com/MoonchildProductions/UXP/issues/817#issuecomment-427697783) in a portable 32-bit installation, both in a new/clean and an old/existing PM28 profile (latter appearing in screengrabs) ... 

![notifications2](https://user-images.githubusercontent.com/9669492/47597469-c1d43880-d997-11e8-85d0-356f163bb927.jpg)

Clicking the gear button in the bottom-right of the notification, I am now directed to newly opened tab `about:permissions?filter=www.bennish.net` where indeed I can manually set notification settings for that site... 👍 : 

![notifications3](https://user-images.githubusercontent.com/9669492/47597562-71110f80-d998-11e8-857a-8b4d4e2c80cb.jpg)

As for issue 2, I triggered a "5 sec" notification, then changed focus to one other (among 20) tab; when the notification popped up, _**clicking the body of it successfully shifted me back to the originating (test) tab**_  👍 

So, many thanks indeed to @FranklinDM & @JustOff for addressing both notifications bugs 🥇 

PS1: @wolfbeast 
Your point is noted and **understood**, but I knew that already... Perhaps the wording in my previous comment wasn't clear enough and for that I apologise... 
What I meant was that in the event I wasn't able to "verify" the fixes with the official unstable build (on an officially supported OS) by Saturday Oct 27th, I could test **locally** on Saturday with the (much frowned upon) fork on my (unsupported) OS; but **for the purposes of this official issue tracker, I would have never used that "local" test as a verification claim of a fixed bug** - I would have waited till I could "officially" verify (like I did now) and then post here... 
PS2: 
It well appears that the simple mention of the terms (Vista | fork) is enough to get (some) people here agitated and/or vexed; I promise henceforth to meticulously refrain from bringing those terms up again, so _these_ people could have their ease of mind back... 

Kind regards
