### ISSUE TITLE
Cross-compile win32 code from linux

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#833]
This would allow applications built on the toolkit to be cross-compiled. Due to the fork point, much of the code needed to get this working is already in the tree.

However, we missed several patches which were added after the fork point. The point of this ticket is to track what changes are needed and to get it building again without error. 
I may also post documentation on how to do this once I figure out it.

This is not high priority, but something I will attempt to do in spare time.

**Comment by mattatobin** [comment]
Why is this needed? Cross-compiled from what to what? If you are thinking linux to windows then no thanks.. It will never provide as good of binaries as Visual Studio and thus worthless.

**Comment by wolfbeast** [comment]
I'd like to know which cross compiling we're talking about here as well. From what to what?

@Sa-Ja-Di  there is no "unfortunate chain" here. Visual Studio communiy edition is freely available, and the fact is that using Microsoft's compiler to compile for Microsoft's operating system is an optimal pair. Compiling with GCC and targeting Windows will produce slow and generally undesirable binaries. I know some purists want to use only Libre software in their toolchain but I think you should always use the **best** tool for the job, even if it isn't free or gratis.

**Comment by g4jc** [comment]
This would allow cross-compiling from GNU/Linux to Win32. It is not intended to be a replacement to MSVC. I agree that MSVC creates better and more optimized binaries for Windows.

However, this also would allow the toolkit to target ReactOS/Wine without any issues.

**Comment by mattatobin** [comment]
We cannot target ReactOS until they switch their subsystem compatibility to NT 6.0+.. Also, running Windows Pale Moon on WINE has worked in the past but may not now because of the NT subsystem version.

I am interested in the possibility of course on a personal level and am tentatively gonna say go forward with your experiment but there shall be much scrutiny when/if the time comes when you want to contribute your little lab experiment back.

I am concerned this could make things more complicated and/or be a big ol' mess. So be weary that if you do pursue this it may not be accepted into the Unified XUL Platform.

**Comment by wolfbeast** [comment]
WINE should already be able to run Pale Moon on UXP since it can run complex binaries that target Windows 7 and above that are compiled with MSVC. I'm sure we would have heard otherwise the moment v28 was published.

So that only leaves ReactOS targeting, which is a no go as long as it's not NT 6 (and probbly 6.1 at that) compatible. Otherwise I really see no reason to cater specifically to building known-poor binaries. The whole FLOSS-only purist argument is moot anyway if you're targeting Windows...

**Comment by mattatobin** [comment]
Let's see what he comes up with.. At the very least it can be documented and handed it out to someone who wants to do this for some ungodly reason.. However, unless it is virtually trivial I don't see it getting accepted.

**Comment by g4jc** [comment]
I have located the list of applicable bugs that affects compiling with mingw-64-gcc 7.3.0. 
The history of meta bugs over at m-c helped some here, along with a lot of web searching.

I will try to list these in the order I bumped into them.

Build System:
Required:
* Bug 1314979 - Support cross compilation with MINGW in windows.configure 

* Bug 1355584 - Make NSIS an optional requirement for MINGW builds
- Note: Upstream took a wrong turn on this patch. It's incomplete.
Skipping NSIS allows it to pass the check, but the skip was not fully implemented, resulting in MAKENSISU = 1.
This causes the build to fail during packaging of the uninstaller after a successful build.

To resolve this, they forced NSIS to be required in 1367847 which in turn depends on a custom depend_if=where implementation in 1316956. 
After all that was implemented, the installer is built corruptly as mentioned in the [comments of the "fix"](https://bugzilla.mozilla.org/show_bug.cgi?id=1367847#c3).
From what I can tell this was never fixed in M-C so the problem remains.

The proper solution here seems to be simply adding a set_config check against nsis. It saves a lot of uneeded rewriting / hacks and builds successfully using existing ifdef code and without NSIS.

e.g.
				diff --git a/moz.configure b/moz.configure
				index c91c8b196..8a1e524cf 100644
				--- a/moz.configure
				+++ b/moz.configure
				@@ -258,7 +258,9 @@ def makensis_progs(target):
				 
				     return tuple(candidates)
				 
				-nsis = check_prog('MAKENSISU', makensis_progs, allow_missing=True)
				+nsis = check_prog('MAKENSIS', makensis_progs, allow_missing=True)
				+
				+set_config('MAKENSISU', depends_if(nsis)(lambda _: True))
				 
				 # Make sure the version of makensis is up to date.
				 @depends_if(nsis)
				-- 
				2.19.1


Recommended: 
* Bug 1420350 - Enable jemalloc on MinGW. r=glandium, a=jcristau (optional)

Toolkit:
Required:
* Bug 1305396 - Replace memmove with std::copy_backward in a file that doesn't include cstring explicitly.
* Bug 1331349 - Fix printf formatting errors in MinGW compilation r=froydnj
* Bug 1332747 - Change MOZ_ALWAYS_INLINE to MOZ_ALWAYS_INLINE_EVEN_DEBUG to fix MinGW Debug build
* Bug 1372870 - Compiling with mingw-w64 based on GCC 6.3.0 breaks (operands to ?: have different types)
* Bug 1372965 - GetCurrentTime causes errors in MinGW and needs to be undefined. See also 1433705. (upstream implemented the guard inside a function, probably should be only for mingw and at the top for clarity)
* Bug 1389965 + 1407601 - Compiling with mingw-w64 based on GCC 6.4.0 fails with std::moz_xcalloc being not declared
* Bug 1443823 - Apply no-keep-inline-dllexport to MinGW x64 also.
* Bug 1448749 - Resolve undefined references to '_imp__mozalloc_abort' in the MinGW build

Recommended: 
* Bug 1365047 - Turn on the Windows DLL Blocklist in MinGW (optional)
* Bug 1372959 - Fix broken mingw-w64 build with --enable-accessibility. (optional)
* Bug 1406736 - Match MinGW's macro so we declare gmtime_r under MinGW too (optional)

Third-Party:
Required:
* Bug 1331335 - Add SSE2 Flags to all of libANGLE. r=jgilbert, a=ritu
* libyuv:744 - mingw fix ifdefs to use gcc source

Cavaets:
The compiled binary seems to only support running with an msvcrt from Win8.1+, if you are trying to run with one that is Win7 compat or prior...

Two unresolved bugs:
* icu 12896 - mingw-w64 gcc 6.2.0 no reference for function _free_locale and _create_locale
* Bug 1460801 MinGW x64 build does not run on Windows 7 due to _create_locale entry point missing

Build instructions and PR can be forthcoming if interested.

Proof this finally worked, although the file size is unfathomably larger than with MSVC: https://i.imgur.com/PVDaj2s.png

**Comment by wolfbeast** [comment]
- Does the resulting binary employ ASLR and DEP?
- Does the resulting binary have a proper embedded PE manifest?
- Re: file size; did you indicate --enable-strip in your mozconfig?
- Which runtime libraries are required?

Also please explain the msvcrt Win 8.1+ caveat. I'm not sure I understand what exactly you're saying. msvcrt is part of the Visual Studio runtime library packages...

**Comment by mattatobin** [comment]
Addotionally, what about standard linux and windows builds as we do them today.

I still would like to compile linux builds of applications with gcc4.9 through gcc7+.

**Comment by wolfbeast** [comment]
@g4jc If you don't have time to answer the questions, please toss me the resulting binary so I can examine the result.

**Comment by mattatobin** [comment]
Not having NSIS makes no sense because we MUST be able to build `helper.exe` for the shell service to work properly not to mention the installer.

So basically, your unoptimized crippled 8.1+ builds with busted shellservice dependencies and no installer isn't very useful.

Plus whatever other hidden side effects to building for all compilers on all systems this may introduce. I find it excessively troublesome and with virtually no benefit except to satisfy some fascist GNU agenda that could end up harming the entire codebase.

**Comment by wolfbeast** [comment]
Usability in a practical sense aside with the current setup, it is an interesting experiment and I was already clear that it must not affect our current toolchain for building Windows and Linux (and Mac) binaries in any way, so no need to drive home that point, @mattatobin - I'm sure we're all aware of the experimental nature of this and it may actually give rise to something useful as well for the way we do things now.

Shell integration is kind of a hackjob in the Mozilla codebase; the fact that it relies on the installer's helper.exe is something that has been a thorn in my side for a long time - and I wouldn't want to dismiss an otherwise interesting experiment just because of that quirk. We don't need NSIS to set file associations 
at all; registry manipulation is actually already in our code base as a usable component afaik.
Even if for some reason it _has_ to be a separate executable, we are still not bound to NSIS, per se, and it can be an external tool -- it can even be included in our tree as a supplied binary if the build tools to create it are "non-free".

That said I want to remain realistic about the current status of this effort and I'm currently not seeing much benefit to have this build option added to our code tree (it might add to the maintenance burden too, after all). Perhaps maintaining this as a fork for the time being is a better practical solution and if it converges more we can look at mergability.

**Comment by wolfbeast** [comment]
Another question is, of course: How did Mozilla solve the NSIS issue? Did they solve it at all?

**Comment by wolfbeast** [comment]
This has gone stale. Is this still being looked at or not? Do you have a binary for me to look at?

**Comment by g4jc** [comment]
> How did Mozilla solve the NSIS issue? Did they solve it at all?

The root issue remains unsolved. [m-c 1367847](https://bugzilla.mozilla.org/show_bug.cgi?id=1367847#c2) wrongly enforced nsis for the mingw build. This results in a broken setup. NSIS should be completely disabled on mingw builds, unless upstream NSIS has plans to support mingw, which is unlikely.

> Is this still being looked at or not? Do you have a binary for me to look at?

I never found a solution for the NSIS blocker mentioned above, since I haven't been able to properly detect mingw exclusively, and the resulting code I tried earlier affected Visual Studio which is unacceptable. NSIS should be required for Visual Studio builds.

In any case, I'll try to re-apply the patches against current trunk and get a binary to test with in the next few weeks.

**Comment by mattatobin** [comment]
@wolfbeast do we REALLY want this? Cause I don't.

**Comment by g4jc** [comment]
Alright...

* Got patches applied against latest trunk (updated mingw64 branch)
* Here's a **Windows binary compiled with mingw64 on Debian 9.** --enable-strip helped a lot on the file size.
https://framadrop.org/r/FJbbd_cSIw#cKNtMLugY6iK5JXgKp8tLtjjqiyNII5VQ4HAmcOd1NQ=
*  Heavily stripped down mozconfig due to limitations: https://dpaste.de/jxMT/raw
* Current NSIS "hack": https://dpaste.de/pijb/raw

Going to get my Windows toolchain setup again to see if the latest NSIS patch attempt breaks VisualStudio or not.

**Comment by wolfbeast** [comment]
So, at first glance it looks like the "binary" isn't packaged, since you have everything unpacked instead of using an omnijar. Was this just a raw copy of the dist/bin folder?

Secondly, it doesn't run.
![Image1](https://user-images.githubusercontent.com/3359132/56094064-1a5cab00-5ed0-11e9-9c6e-5cedbc311523.png)

**Comment by g4jc** [comment]
Yes, no packaging is done in Mingw builds, just dumps everything into the bin folder.

The error you bumped into is [m-c 1460801](https://bugzilla.mozilla.org/show_bug.cgi?id=1460801), the build only works on Windows 8.1 or higher. I believe this is the same as upstream bug [ICU-12896](https://unicode-org.atlassian.net/browse/ICU-12896)

**Comment by wolfbeast** [comment]
You **must** package properly, otherwise this is completely pointless. MSVC also creates a dist/bin with the same stuff in there, but that's just a raw compile output that also has a bunch of tools in there that do not belong with the browser, and a flat/unpacked browser chrome has absolutely abysmal performance because of raw file I/O. You have to create a properly packaged result with `mach package` if you ever want to publish a compiled version of this.

As for the error, it's clear you're not building/linking against correct libraries. "msvcrt.dll" is a generic name for the visual c runtime, but what you really want to build and link against is the specific vcrt dlls from the platform SDK you are using to build, and supply those dlls WITH the browser (compare with how we build our Windows binaries with MSVC, specifying a `WIN32_REDIST_DIR` to get the appropriate dll from.
In your case it will require a copy of the mcvcrt.dll you are using to build against (whatever it is you're using, WINE or w/e, that includes the win8.1 platform API, apparently) to end up in dist/bin (and any dependencies), alongside the browser binaries. If you don't, then whatever is the system dll will be used which will fail on versions of Windows where this dll does not export the expected functions linked against, and might also cause issues where the functions are exported but implemented differently.

**Comment by g4jc** [comment]
Thanks for the pointers. After some more digging around I found the problem. A helpful tip left on the [icu bug tracker](http://icu-project.org/trac/ticket/12896#comment:9) explains the situation. It seems Mingw applied a fix with their opensource MSVCRT, but any package using ICU continued to be a problem on Windows 7. I applied the patch mentioned there, stubbed out the NSIS helper.exe and it properly went through `mach package`. Tested working on Windows 7.

Give it a try and check out about:buildconfig - https://framadrop.org/r/mwSPlVDR9M#ffLqmo3+Vjd6NsruKcNKMGI5w7iMxk+8me3I3ZCsUq4=

**Comment by mattatobin** [comment]
What do you mean stubbed out helper.exe? helper.exe is essential to the shell service working properly.

**Comment by g4jc** [comment]
OK, I finally found a better way that no longer "stubs it out", now it just uses the proper #ifdef if MAKENISU is not found and works on Windows and Mingw64 Cross-Compiler.

You can have a look at this branch for a list of all required and relevant commits: https://github.com/g4jc/UXP/commits/mingw64

**Comment by mattatobin** [comment]
Without helper.exe shellservice is crippled which is a major function for system integration. Without nsis the installer cannot be built and without the installer mar files cannot be generated and without mar files updates cannot be created.

Plus, it still likely runs worse than platform  native msvc builds.

So not interested.

**Comment by g4jc** [comment]
Pretty much. Non-breaking patches would be up until that last NSIS commit, so if a "Part 1" would interest anyone, that will get you as far as the packaging step. After which you can either disable NSIS *or* try and get NSIS to support MinGW. Some random posts on Sourceforge claim that it is possible, so maybe they will at some point have it working.

**Comment by wolfbeast** [comment]
This is dragging on quite a bit and has multiple blocking issues that would not make me amenable to landing patches on our repo for, and I've still to be able to investigate a resulting binary that is properly packaged and runs on Windows 7.

So, I think I have a solution that will keep our tree free from edge-case compilation hacks and still allows people to cross-compile if they insist:
**Create and maintain a page on the [development wiki](https://developer.palemoon.org/) where you outline build and patching instructions for people who want to cross-compile from Linux to Windows. You are free to further investigate in that context how to solve the issues and update instructions and the page as-needed, including the blockers like Win 7 compatibility, installer compatibility, mar generation, etcetera.**

I think doing it this way everyone can have their slice of cake in an orderly fashion.
