### ISSUE TITLE
Lightweight Themes aren't applied as they should

### ISSUE THREAD

**Issue by Felipefpl** [MoonchildProductions/UXP#846]
Using basilisk from 09/27 plus Win7 x64.

When applying themes to basilisk most of times the browser will set wrong colors for it, either they will be white or black, sometimes drawing vertical lines that are seen in the tabs. In a few rare situations the correct colors will be set. See below:

https://addons.mozilla.org/en-US/firefox/search/?q=windows+7+blue&cat=themes

Here is a case where a color will be set correctly:

https://addons.mozilla.org/en-US/firefox/addon/windows-xp-default/

**Comment by mattatobin** [comment]
This is regarding Personas not True Themes.

**Comment by Felipefpl** [comment]
I dont understand, there is no mention of personas in the search or windows xp default's site, what's the difference between one and another?

**Comment by kn-yami** [comment]
Persona is basically two images that the browser would download and display as background for tabs and the status bar. True theme is a special type of extension containing style sheets and other assets that can be used in place of browser defaults.

**Comment by Felipefpl** [comment]
Thanks for teh info kn-yami, too bad no difference is shown at mozilla's site, i tried to search for full themes but no success.

**Comment by kn-yami** [comment]
The difference is shown: [personas](https://addons.mozilla.org/en-US/firefox/themes/), [true themes](https://addons.mozilla.org/en-US/firefox/complete-themes/).

**Comment by Felipefpl** [comment]
Thanks for both links kn-yami, but in my previous searches for extensions i found and tried some of those in the "true themes" link and i couldnt change the theme, the complete theme is installed but nothing is changed plus the "enable" button isnt shown so i cant enable the skin, only remove it.

**Comment by kn-yami** [comment]
True themes work on my end, I have just checked it with [this one](https://addons.mozilla.org/firefox/downloads/file/621329/ft_deepdark-14.3-fx-windows.xpi). The green button should read "Add to Firefox" regardless of browser used to browse AMO, unless you are using @JustOff's _MTT_ that is available only for Pale Moon - you can not install it in Basilisk.

**Comment by Felipefpl** [comment]
I see, too bad it doesnt work with me, i'm not using mtt from justoff.

**Comment by mattatobin** [comment]
Nor should you. It wouldn't do anything for Themes or Personas.

Your issue is that some Personas you are trying to use (which will be going away for Firefox as they are gonna switch to "Static WebExtension Themes" which are the same result via different mechinism) either don't have the right detected text/accent color or don't have the correct persona provided text/accent color on Basilisk.

What we need is more examples of the Personas you are using and some screenshots.

**Comment by Felipefpl** [comment]
Sorry wolfbeast but the title is a bit misleading, i also tried complete themes and it didnt work. :/

**Comment by wolfbeast** [comment]
...
Are you using a high-contrast system theme, by any chance? If so, there's nothing we can do about it as those are specialized accessibility modes of the OS that override colors in applications.

**Comment by Felipefpl** [comment]
Nope, i'm using only the winxp default theme which link i pasted in the 1st post. I also tried several complete themes, dark ones, win7/w10 ones, both walnuts and the result is what i reported above.

**Comment by mattatobin** [comment]
We don't support ancient operating systems. If you are running on Windows XP then you do not qualify for support or consideration. There are no official/branded builds of any Moonchild Productions products for those operating systems. Please talk to whomever are providing the builds to you.

**Comment by ibuprophen1** [comment]
Wow @mattatobin... that was brutal... LOL! 😨

@Felipefpl, he was correct regarding a piece of software that surpassed its EOL a billion years ago +/- but, you should think about upgrading to at least Windows 8/8.1. 

One inexpensive option is taking a look at Amazon or eBay for Official (unused of course) product license keys for Windows 8/8.1. They are really inexpensive and affordable. 

When you obtain the product key, you can download the Official Windows 8/8.1 ISO to burn on a DVD or USB thumb drive. 

This is only one option that you can always consider. 

Just a recommendation/suggestion... 

I wish you the best of luck! 👍 


~Ibuprophen

**Comment by wolfbeast** [comment]
I was under the impression that the "Windows XP default" theme is actually just a theme, since it was linked to on AMO, and not that the user is actually running on Win XP.

@Felipefpl can you please clarify what exactly your environment is that you are running in?
Also, I was talking about your **system** color scheme (in Windows), not any theme you have applied to the browser, when asking about the high contrast theming.

**Comment by mattatobin** [comment]
Well I am confused now too.. We need detailed info, environment, os, arch, versions, etc.

This is the second or third issue by this person and getting them dealt with since they should have been reported to the forum before hitting github requires background and clairification.

I wanted screenshots remember? Didn't get any.

**Comment by mattatobin** [comment]
So you're not going to provide info and clarify your questions or answer ours. K. I say this gets put back in the invalid category.

**Comment by Felipefpl** [comment]
kn-yami - i had serpent installed, i removed it and now it seems to work fine, thanks for the help. This one can be closed now.

Now i'm having another problem and i'm wondering if unluckly i'm the only one going through this:

https://github.com/MoonchildProductions/UXP/issues/864
