### ISSUE TITLE
increasing the addons popup size (feature request)

### ISSUE THREAD

**Issue by leedoyle** [MoonchildProductions/UXP#875]
It would be nice to be able to maximize the popup in many addons like uMatrix, uBlock or Conex. The default size forces one to tediously scroll down what could have perfectly fit into the screen. On a 1920x1080 (and thus on a 1280x1024, too) screen, default popup size could be increased in height by at least 1/3. The problem is, it can't grow more than 600px in height:  It will grow to a size of 800x600 pixels at most if that fits on the user's screen.  I understand you have a very tight schedule and a big to-do list, but if you could give any insight into this issue - any at all - I would be very grateful. Perhaps it would not even be difficult at all to patch.  That would allow webextensions addons to have the UI similar to tab groups tab preview and enhance usability of other addons like uMatrix. 
![2018-11-18-063933_636x461_scrot](https://user-images.githubusercontent.com/25978190/48668380-e043d480-eafc-11e8-9000-327f887cd68c.png)

**Comment by mattatobin** [comment]
This is a feature the extensions will have to implement as these are all custom and specific to their respective extensions.

**Comment by leedoyle** [comment]
@mattatobin no,  it's hardcoded in the browser. Extensions can't create popups larger than  800x600 pixels

**Comment by wolfbeast** [comment]
These are doorhanger-style (layer) pop-ups. They have a maximum size hard-coded in the browser because unrestricted layer size will cause massive issues in the rendering back-end. It is up to the extension devs to work around this necessary restriction (either by using a XUL window (i.e. the way tab previews are presented) or working within the confines of the pop-up layer size).

So although the problem is subtly different, it is still not something that we can "fix". The choice of a layer pop-up to present a large amount of data was not a smart design decision for uMatrix and it will have to change that approach if more space is needed.
