### ISSUE TITLE
Avoid false positives in preprocessor-checker

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#912]
At the end of our build process, we have a check that verifies if all files in the objdir that need preprocessing are actually preprocessed.
In Interlink, this causes a false positive error because a `%`-prefixed DTD reference in an XML file is seen as a preprocessor command.

`%`-prefixed commands are only valid in CSS -- checks for that should be restricted to CSS. Similarly, `#`-prefixed commands should be restricted to other files and not checked for in CSS files. I.e.: the script needs to be a little smarter.

@JustOff this is your script; assigning you to improve it :)

Tag #429.

**Comment by mattatobin** [comment]
At the very least since in no way is the check materally fatal to the build process even if a file is practically a failure and won't work the error text should be changed to indicate that..

Don't call it a build failure and maybe say:
Warning: The following files may need to be preprocessed please verify build configuration or some shit.

Just in case of false positives.

**Comment by mattatobin** [comment]
I wouldn't call it an error on your part perse. Simply improving something because a case exists now that needs handling.

I still think the message should still say "Warning" and suggest one check the file.

**Comment by JustOff** [comment]
> I still think the message should still say "Warning" and suggest one check the file.

In this case, I think let @wolfbeast, as an acknowledged master of wording, judge it.

> Also, are you sure awk works the same on mozillabuild as it does on generic linux?

This has been verified.

**Comment by wolfbeast** [comment]
Probably better to keep it as an `error` since it -will- be a broken application as a result.
