### ISSUE TITLE
[Question] Is Pale Moon 100% Free Software?

### ISSUE THREAD

**Issue by gjhklfdsa** [MoonchildProductions/UXP#923]
I've been hearing some rumors that Pale Moon is [non-free](https://www.wikipedia.org/wiki/Non-free_software), that is to say not [free software](https://www.wikipedia.org/wiki/Free_software). Is this true? If so, what portion of the software is [non-free](https://www.wikipedia.org/wiki/Non-free_software) and how is this different than competitor's licensing like [Firefox](https://www.wikipedia.org/wiki/Firefox)?

**Comment by wolfbeast** [comment]
The binary redistribution license is not really an answer. It only highlights the restrictions on branded redistribution.

Pale Moon is free software. Just like Firefox and other applications with trademarked branding the software itself is free, but the official branding is not. Pale Moon is fully Open Source under the MPL and a smattering of other open licenses for different components that are being used (see about:license in the browser) and classifies as free software, and there is no difference in licensing structure compared to Firefox as regards the source code.

See also: http://www.palemoon.org/licensing.shtml where all of this is already explained.

Feel free to counter the rumors or ignore them.

**Comment by gjhklfdsa** [comment]
@wolfbeast I personally, do not consider images software. Most other software do enforce their trademarks. The question is does it affect the actually freedom-ness of the software.
Basically, show me the code. You can enforce your images, but the software should be mine.

**Comment by gjhklfdsa** [comment]
@wolfbeast The most common rumor appears to be the installer is non-free. Could you comment more on this?

**Comment by kn-yami** [comment]
The NSIS scripts that are used to make the installer are in this repo and AFAIK are provided under the same license that rest of the UXP code uses (obviously excluding libs and branding). Also the software is not yours, you are simply licensed to use it.

**Comment by Ascrod** [comment]
By FSF's defintions, Pale Moon is Free Software. There are a few tools for Pale Moon that are not open source, but use of them is not required to use the browser. The comment about the installer being nonfree may be referring to the web installer stub. See also [this topic](https://forum.palemoon.org/viewtopic.php?f=4&t=7818) on the forum, specifically the sections "Rumor: Pale Moon is not truly Open Source" and "Rumor: Pale Moon's tools are proprietary".

**Comment by gjhklfdsa** [comment]
> The NSIS scripts that are used to make the installer are in this repo and AFAIK are provided under the same license that rest of the UXP code uses (obviously excluding libs and branding). Also the software is not yours, you are simply licensed to use it.

I meant meant [metaphorically](https://www.dictionary.com/browse/metaphorically), obviously I didn't write it and was not claiming so. 

UXP is not in the [public domain](https://www.wikipedia.org/wiki/Public_domain) in which everyone in theory owns it, just [free software](https://www.wikipedia.org/wiki/Free_software).

**Comment by gjhklfdsa** [comment]
> By FSF's defintions, Pale Moon is Free Software. There are a few tools for Pale Moon that are not open source, but use of them is not required to use the browser. The comment about the installer being nonfree may be referring to the web installer stub. See also [this topic](https://forum.palemoon.org/viewtopic.php?f=4&t=7818) on the forum, specifically the sections "Rumor: Pale Moon is not truly Open Source" and "Rumor: Pale Moon's tools are proprietary".

I just want to clarify, these non-free "tools" are not automatically installed?

The FSF generally condems recommending non-free software, I just want to clarify it won't "pop-up" and ask me to install it without warning (like Brave warns before installing DRM).

**Comment by Ascrod** [comment]
@gjhklfdsa 
> I just want to clarify it won't "pop-up" and ask me to install it without warning
Of course not! They are not advertised or pushed in any way by the browser; nor are they required to use the browser. They are simply provided free of charge as a convenience.

**Comment by mattatobin** [comment]
The code IN the repository sans official and unstable branding assets are open source even by the Free Software Foundation standards.

However, do not think that we collectively are under their authority or claim to be.

The free propriety supplimental tools like the profile backup tool or web installer downloader stub despite their relationship with Pale Moon remain separate tools and utilities that are targeted for Windows not Linux. Windows versions are likewise compiled with Visual Studio and bundle the redistribution libraries. Again, this applies to Windows not Linux. The same can be said for NSIS, whatever license it uses.

If you use Windows then the whole "moral" stance put forth by the Fascist Software Foundation is quite moot.

**Comment by wolfbeast** [comment]
The browser and all components are completely Open-Sourced. As stated none of the optional utilities are part of the browser and none of them are included or required by the browser's standalone installer or binary archives. None of these tools will be downloaded or installed without your explicit action to do so.

Run-time and system libraries may be supplied under different licenses -- as stated, on Windows, several run-time libraries are included with the browser as part of the package, which are redistributables provided by Microsoft. This is required because not all Windows installations may have these run-time libraries installed.
On *nix, depending on system configuration, the browser may also make use of libraries that are non-free, although in that case they will not be provided by the package itself. That being said, some components of the browser are also patent-encumbered (like libvpx) but with a grant for use and disclosed source; this applies to all platforms. So if you want to take the moral high ground and be a purist, then you have to examine the licensing of the various components in `about:license` and decide whether you consider Pale Moon's components (and in turn the browser) "non-free" or not.

The web-installer has always been **completely optional and a convenience utility** -- and in fact is no longer in use at the moment due to some concerns about unsafe loading of DLLs by the executable spit out by the RAB used to build it. I've never seen any reason to disclose its source since, once more, it was supplied merely for convenience for non-technical Windows end users wishing a more user-friendly installation interface than the standalone installer (always available as a direct download), especially back when adding checks for processor capabilities to run the software was still much more of a requirement.
