### ISSUE TITLE
Add an ABI specific incompatiblity error message

### ISSUE THREAD

**Issue by kn-yami** [MoonchildProductions/UXP#944]
Currently when installation of an extension fails because of OS/ABI incompatibility add-on manager uses the same error message ([`addonErrorIncompatible`](http://xref.palemoon.org/uxp-trunk/source/application/palemoon/locales/en-US/chrome/browser/browser.properties#73)) that is used to indicate an min/maxVersion version mismatch. While the current error message is true in both cases, I think that it may be better to give OS/ABI incompatibility its own error message.

**Comment by mattatobin** [comment]
I have just had a looksee and this would NOT be trivial because of how the checks are implemented.

**Comment by wolfbeast** [comment]
If this is still desired as an enhancement, someone please indicate interest in implementing this because it's just going to go stale otherwise.
Note that the situation where this applies is an edge case to begin with (binary components in extensions) and extension authors often clearly mark their extensions in file name with the OS if it applies.

If no interest by the end of May, we'll close this as wontfix.

**Comment by wolfbeast** [comment]
Closing issue due to lack of interest and marginal use case.
