### ISSUE TITLE
Disable/alter the feature to indicate security level in URL bar with various colors

### ISSUE THREAD

**Issue by mopsafe** [MoonchildProductions/UXP#947]
Please, **PLEASE** make an option to NOT SHOW the url`s host in the left side on te address bar (where the URL is colored based on the security level).

Now the address bar looks ike this: https://forum.palemoon.org/download/file.php?id=8837&mode=view

Why, why do I need to see the "palemoon.org" to the left from the URL? That palemoon.org occupies a lot of adress bar`s space and useless:  You want to show the security level for the site? Good - change the color/background of the lock. But please do not occupy the address bar space.

**Comment by mattatobin** [comment]
I believe you can already control the style of the so called identity/security chip vis preferences. I also believe there are old Firefox extensions that have a GUI for said preferences. As well as there are other ways you can manipulate it via userChrome with a little help from DOMi.

So please calm down. If I find the exact preferences I will update this issue.

**Comment by wolfbeast** [comment]
> Why, why do I need to see the "palemoon.org" to the left from the URL?

Because that is the domain you are visiting over TLS. Visually, that is also not always equal to what your URL might show in the case of an IDN-masked name, for example, and the identity panel will in that case always show the actual domain name. It indicates which domain the certificate is validated for, and in the case of an EV certificate, it will show the registered organization the certificate was issued to.

This identity panel has been like this for a very long time and will not be changed. The information displayed by default is considered essential for https traffic.

You can, however, control if this extra information is shown or not, at your own discretion and risk.
`browser.identity.ssl_domain_display` controls how much of the visited domain is emphasized in the identity panel. `0` means don't display, `1` (default) means display the eTLD (effective top level domain), and `2` means display the entire host.
If you want a GUI solution, Pale Moon Commander has this option under the Security category, tab SSL, at the very top.
