### ISSUE TITLE
Graphical issue: Progress indicator kicks in whenever a new tab is opened.

### ISSUE THREAD

**Issue by Peacock365** [MoonchildProductions/UXP#950]
Just wanted to report an odd occurence in the status bar / add-on bar: When you open a new tab, the progress indicator at the bottom right of the screen pops up for the better part of a second and then vanishes quickly. It doesn't make sense to show the progress indicator when a new tab is opened. After all, no content (aside from about:blank) is being loaded yet.

Please fix.

**Comment by wolfbeast** [comment]
Any page, even internal ones, need to be loaded and therefore have a loading progress.
Depending on your extensions, initializing and opening a new tab (even just about:blank) can take some time, making the progress a visible occurrence.

All of this is by design; theoretically it's possible to make a specific exclusion for "special pages" but I don't really see a point in doing so -- some do have a longer load before they are "ready" and the indicator is useful in that case.
