### ISSUE TITLE
Feature Request: Duplicate tab

### ISSUE THREAD

**Issue by elig0n** [MoonchildProductions/UXP#984]
Right click on a tab -> Duplicate tab

**Comment by kn-yami** [comment]
You can duplicate tabs by middle-clicking the reload button,  by holding control when pressing the reload button and by holding control and dragging the tab. If you want an entry in the tab context menu then there is an add-on for that - caa:addon/duplicate-in-tab-context-menu.

**Comment by elig0n** [comment]
Thanks. Where can I find this addon ?

**Comment by ibuprophen1** [comment]
@eligOn, the following section should help you out... 

https://addons.mozilla.org/en-US/android/addon/duplicate-tab-webextension/

https://addons.mozilla.org/en-US/android/addon/new-tab-context/

Good Luck! :-) 


~Ibuprophen

**Comment by kn-yami** [comment]
Since "legacy" add-ons were removed from AMO about a year ago it is impossible to find a working version of this extension there. Instead you can install Classic Add-ons Archive form [here](https://github.com/JustOff/ca-archive/releases/download/1.2.3/ca-archive-1.2.3.xpi) and then navigate to the `caa:addon/duplicate-in-tab-context-menu` URI to download a "legacy" version from there.
